### ISSUE TITLE
Blockstream Jade fails to show address on device and sign with multisig

### ISSUE THREAD

**Issue by seedhammer** [sparrowwallet/sparrow#661] opened 2022-08-20 13:29 UTC
Using Sparrow 1.6.6 and Jade 0.1.34, I can display single sig wallet addresses on the Jade device, but trying to show multisig addresses fails with an RPC error:

"device reports readiness to read but returned no data (device disconnected or multiple access on port?)*

or

"JadeError: -32600 - Invalid RPC Request message (Data: b'213')"

Similar errors happen if I attempt to sign a transaction.

To reproduce, I created a new 2-of-3 wallet with 2 shares generated by Sparrow, and one share being the Jade.

**Comment by craigraw** [comment] 2022-08-22 07:45
I'm not able to reproduce this. Jade successfully displays the a multisig wallet address (after registering the wallet initially). Signing a multisig transaction works fine too. Same firmware version. 

I suspect a USB bus/kernel issue might be involved, at least for the first result you obtained.

To debug this further, I suggest using HWI (the library Sparrow uses for USB communications) directly. For example:
```
./hwi --device-type='jade' --device-path=XXX --desc 'wsh(sortedmulti(2,[06722fd4/48h/0h/0h/2h]xpub4FAFKj.../0/1,[d43a1b59/48h/0h/0h/2h]xpub4FhbZ.../0/1))' displayaddress
```

HWI can either be found in the Sparrow home folder (OSX or Windows) or by looking at the Tools > Install Udev Rules in Linux. Alternatively, get it from https://github.com/bitcoin-core/HWI. The device path can be found using `hwi enumerate`.

**Comment by seedhammer** [comment] 2022-09-03 18:22
I tried

```
$ cd /Applications/Sparrow.app
$ find . -iname hwi\*
$
```

but found nothing.

> (after registering the wallet initially)

How are you doing this? Maybe that's the missing step, because I started with a factory reset Jade device. That is, I'm only using Sparrow and a Jade, and in particular not the Green wallet.

**Comment by craigraw** [comment] 2022-09-04 07:30
Take a look at https://help.blockstream.com/hc/en-us/articles/900005443223-Why-is-Blockstream-Jade-not-recognized-by-my-computer-

It does appear that a specific driver is used, which is probably installed by the Green wallet. I did install Green when working on the Jade integration (to update the firmware) so that may be a key difference.

Re HWI, the location of the Sparrow home folder is described here: https://sparrowwallet.com/docs/faq.html#where-does-sparrow-store-data

**Comment by craigraw** [comment] 2023-02-15 11:51
Closing this off.

**Closed by craigraw** 2023-02-15 11:51 UTC
