### ISSUE TITLE
[Feature Request] Add an option to show the fiat value in the transaction / UTXO list

### ISSUE THREAD

**Issue by PrinceOfEgypt** [sparrowwallet/sparrow#1120] opened 2023-10-05 23:17 UTC
Pretty much what it says in the title :)

here's an example of how Specter does it - perhaps you could add a configurable option to show the same thing?

![image](https://github.com/sparrowwallet/sparrow/assets/2649235/1396fe88-b10a-4f99-9c3f-9b0528eeb1f4)

Thank You!

**Comment by craigraw** [comment] 2023-10-06 11:54
Duplicate of #1095. Note also the bitcoin values would no longer be in vertical alignment with this proposal, making their values more difficult to read.

**Closed by craigraw** 2023-10-06 11:54 UTC

**Comment by PrinceOfEgypt** [comment] 2023-10-06 12:20
Thanks for the response. I did look to see if there was already an issue open for this, but didn't think to check closed ones.
