### ISSUE TITLE
Small rendering of UI in Linux (Ubuntu) on Macbook HiDPI/Retina display

### ISSUE THREAD

**Issue by xFvl** [sparrowwallet/sparrow#323] opened 2021-11-22 21:08 UTC
Running Ubuntu 20.04 on an old Macbook 2013 13".

I've definitely run into this before with a few other programs. See attached (terminal and cursor for comparison).

Not unusable, just wanted to bring it to attention.

Cheers

![Screenshot from 2021-11-22 12-44-18](https://user-images.githubusercontent.com/29760774/142935435-f6353832-ab8b-4b99-bd3f-7a697f386e7f.png)

**Comment by alaznem** [comment] 2021-11-22 23:13
I can confirm this issue.

The background of this issue is that java applications don't scale according to the system wide scale settings for high-res (like Retina) displays (at least in Ubuntu).

As a workaround (but not so smooth overall display usage) you can disable scaling and turn down the screen resolution accordingly in the `Settings > Displays > Resolution & Scale`.

As an example: lower the screen resolution but keep the screen ratio. For example from 2880 x 1800 to 1440 x 900 (1/2 of the max display resolution).

**Comment by craigraw** [comment] 2021-11-23 06:19
Duplicate of #175. Please could you try the suggested fix in https://github.com/sparrowwallet/sparrow/issues/175#issuecomment-966405907 and comment there if it works?

**Closed by craigraw** 2021-11-23 06:19 UTC
Labels: duplicate
