### ISSUE TITLE
[Bug] Unable to RBF on Badbank account due to "Insufficiant funds" warning

### ISSUE THREAD

**Issue by RequestPrivacy** [sparrowwallet/sparrow#541] opened 2022-05-10 16:37 UTC
# Steps to reproduce

- Enable RBF
- Send funds from Badbank account
- Before first confirmation go to Badbank transaction tap and either right-click "Increase Fee (RBF)" or directly click on the hand symbol with the cross above it
- Send tap on Badbank account opens with everything filled out for Replace by fee (specifically the transaction amount is pulled from the original send)
- "Pay to" is the next unused address from deposit account (or you can choose it, not quite sure anymore)
- **"Insufficient funds" warning and greyed out "Create transaction" button prevents creation of the RBF-transaction**
- Lowering the transaction amount so that more sats are available for the miners (i.e. to increase the fee) doesn't change the "Insufficient funds" warning up until the warning "Amount to low" 
- Sliding the fee slider doesn't help either.

# Expected behavior

- A send from the Badbank account should go back to the Badbank account if a RBF is done (not be send out into the Deposit account)
- I expected that - once I lowered the transaction amount of the RBC transaction - I would be able to increase the miner fee and create the RBF transaction.

**Comment by craigraw** [comment] 2022-05-11 07:32
I was unable to reproduce this behaviour, but in addition there are some notes here:

> A send from the Badbank account should go back to the Badbank account if a RBF is done (not be send out into the Deposit account)

An RBF (Replace by Fee) seeks to replace the transaction in the mempool with one with a higher fee rate. It does not mean "replace address" - that is left to the discretion of the user. If a user wants to replace their original address with another (perhaps from the same wallet) that is up to them. Presumably, in your case the original transaction was sending to Deposit.

> I expected that - once I lowered the transaction amount of the RBC transaction - I would be able to increase the miner fee and create the RBF transaction.

I suspect that the Badbank wallet did not have enough funds to increase the miner fee, although it's not clear why reducing the amount did not help with this. I want to note there is nothing special about the Badbank wallet in this context - to the RBF functionality, it behaves like any other wallet. Sparrow's RBF implementation looks first if there is a change output of sufficient size to accommodate the maximum fee rate known by Sparrow. If not, it tries to add additional UTXOs from the wallet to increase the change available, as far as possible. It then constructs the replacement transaction and presents it, using the coin control to ensure that the UTXOs are not replaced if changes are made. From there, Sparrow behaves like another other coin control transaction, except that it is using already spent UTXOs.

I suspect there is something else going on here (have you enabled 'Allow Unconfirmed' in the Preferences?) but hopefully the information above may be of use to dig further.

**Comment by RequestPrivacy** [comment] 2022-05-11 08:09
> An RBF (Replace by Fee) seeks to replace the transaction in the mempool with one with a higher fee rate. It does not mean "replace address" - that is left to the discretion of the user

Right, and in my case the original transaction was send from a Badbank account to an external service. Following my above described steps I recall that once I clicked on the dropdown menu there were already 2 choices provided for the "Pay to"-Field: one was Deposit (which I clicked and which pulled a correct unused address from said account) and the Paynym option.

Of course I could have tried to manually copy&paste the next unused Badbank address into the field. But why is the deposit option provided in the dropdown but not a Badbank one, since the transaction originated from the latter?

> I suspect that the Badbank wallet did not have enough funds to increase the miner fee, although it's not clear why reducing the amount did not help with this.

Maybe my understanding of RBF is flawed: the transaction spend the whole Badbank balance with not change back. I thought I could do a RBF by minimizing the amount send and increasing the miner fee of the one and single fully spend input (e.g. original send was 50.000sats divided in 49.000sats send with 1000sats miner fee, so in the RBF send menu I specify 40.000sats send with 10.000sats miner fee) so that miners see two transactions with the same input but one has a higher fee and therefore is chosen for the block. But if I understand your further explanations maybe that isn't how this feature works?

If that's the case maybe a little hint would be helpful for users like me. Like instead of simply saying "Insufficient funds" in the send tab something more precise like "No change or other wallet UTXOs available for facilitating a RBF"?!

**Comment by craigraw** [comment] 2022-05-11 13:18
> But why is the deposit option provided in the dropdown but not a Badbank one, since the transaction originated from the latter?

Good point. This was done to prevent users receiving directly to premix, postmix and badbank - but Sparrow shouldn't prevent consolidation sends. Now fixed.

> I thought I could do a RBF by minimizing the amount send and increasing the miner fee of the one and single fully spend input

This understanding is correct, and I've tested this behaviour to ensure it is indeed possible. What I believe happened here is that the amount was reduced by a value that created a dust change output, which Sparrow doesn't allow. What I've done to resolve this is simply enable the Max button when only one output was present in the original transaction - this allows free adjustment of the fee range slider as Sparrow automatically deducts from the payment amount to increase the fee, and no change is attempted.

Implemented in b06df38.

**Closed by craigraw** 2022-05-11 13:18 UTC

**Comment by craigraw** [comment] 2022-05-12 09:06
On further investigation, I've found the bug that caused this issue. Fixed in https://github.com/sparrowwallet/drongo/commit/eddd6406efc20b83e659d59faa16189417b0f5ed.

**Comment by RequestPrivacy** [comment] 2022-05-12 14:58
Thanks for sticking on the topic. So it was an issue of not counting the unconfirmed spend into the possible RBF spend?

**Comment by craigraw** [comment] 2022-05-12 15:15
Yes, not counting spent utxos in one of the sanity checks triggered the bug when the spending tx was a full wallet sweep.
