### ISSUE TITLE
Wrong menu size. Bottom options partially visible or invisible. Tooltips invisible.

### ISSUE THREAD

**Issue by Akira45-0** [sparrowwallet/sparrow#1556] opened 2024-12-09 10:58 UTC
Hi, I have a problem with menu options either invisible or partially visible. I am using Linux with XFCE.
By default the menus look like this:
![Screenshot_2024-12-09_11-47-42](https://github.com/user-attachments/assets/36ded0a9-0f59-402b-95f9-d50d1d6f5b72)
![Screenshot_2024-12-09_11-48-32](https://github.com/user-attachments/assets/bf3cfb55-2f8b-4e9e-a7a3-4c8d0392507c)
![Screenshot_2024-12-09_11-49-41](https://github.com/user-attachments/assets/4bd60a90-adb3-426d-8727-e8049d462ed3)
Notice that the lowest options (at the bottom) are visible partially and the tooltip is completely invisible, it's just a black line. Actually the tooltip text appears for a moment and then it just becomes the black line.

After setting the scale to 150% with `_JAVA_OPTIONS=-Dglass.gtk.uiScale=150% /opt/sparrow/bin/Sparrow` it looks like this:
![Screenshot_2024-12-09_11-52-01](https://github.com/user-attachments/assets/fa034246-6267-45b6-9803-554b7c3f6c61)
![Screenshot_2024-12-09_11-52-40](https://github.com/user-attachments/assets/36a74eb2-3c5c-4a94-9ba9-57d5106aef6e)
Notice that the lowest/bottom menu options are visible (although there's no bottom menu border) and the tooltip becomes partially visible.

After setting the scale to 50% it looks like this:
![Screenshot_2024-12-09_11-56-06](https://github.com/user-attachments/assets/029cacad-0b91-4e60-a1d1-4d408d7b48f7)
![Screenshot_2024-12-09_11-56-52](https://github.com/user-attachments/assets/b1e144b2-76a4-4553-9ba9-97882dfa2ed5)
Notice that some menu options are completely invisible, but the tooltips magically become visible.

Both menus and tooltips should be completely visible regardless of the scale.

**Comment by craigraw** [comment] 2024-12-09 11:25
Duplicate of #1531. Thank you for the additional information on the menus though.

**Closed by craigraw** 2024-12-09 11:25 UTC
