### ISSUE TITLE
[Bug] Mismatch between postmix UTXO count and rows in table

### ISSUE THREAD

**Issue by kobiebotha** [sparrowwallet/sparrow#604] opened 2022-06-22 16:18 UTC
# Sparrow 1.6.5 macOS M1 Native build

My postmix screen is showing 16 UTXOs, and I also have 16 UTXOs in the exported CSV

However, as you can see in the screenshot, there are 19 rows being displayed.

In addition, I can use the down arrow to move selected rows all the way down to row 16 (blue row in screenshot), however I can't down arrow further down to 17, 18 and 19.

Thusfar I've been unable to identify any patterns so this is all the info I have.

<img width="282" alt="selection-screenshot-Wed Jun 22 10:13:09 MDT 2022" src="https://user-images.githubusercontent.com/277659/175082645-4b7e7e23-02bd-48d4-ad51-9601a3d8cbd0.png">

**Comment by kobiebotha** [comment] 2022-06-22 17:44
Bad news: a restart of Sparrow fixed this, so now I can't reproduce...

I'm guessing leaving the mix running for multiple days got me into this state. I'll see if I can get into it again.

**Comment by craigraw** [comment] 2022-06-24 11:45
Not following completely here: You say "My postmix screen is showing 16 UTXOs" and then "there are 19 rows being displayed". Can you clarify what you meant?

Errors like this can be caused by a faulty Electrum server - what kind of server are you connected to?

**Comment by kobiebotha** [comment] 2022-06-27 16:03
Sorry, words. Was hoping the screenshot would make it clear. If you look at the screenshot, it says `UTXOs: 16`, however if you then literally count the rows below that, you will count there are 19 and not 16. Hope that makes sense.

I'm using my own local ElectrumX server.

**Comment by craigraw** [comment] 2022-07-11 10:00
Actually, I now think this is caused by some kind of a JavaFX framework issue. Both the UTXO count label and the table below are updated from the same data structure at the same time, and your inability to arrow down to the last 3 rows suggests that the table itself had some kind of an internal error whilst updating its display. If you can find anything in the Sparrow log (Help menu) from around this time (look for `UTXOController` lines), it might be helpful to diagnose this further.

**Comment by kobiebotha** [comment] 2022-07-12 03:21
Ah, it never struck me to check the logfile at the time. Unfortunately going back in time isn't very fruitful, since the logs are super spammy with whirlpool warnings and errors. I searched for `UTXOController` and couldn't find anything. Happy to close this as "can't reproduce" or whatever since it seems like a once-off, and if it happens again I'll check the logs

**Comment by craigraw** [comment] 2022-07-12 06:03
Ok, let's close this off for now then - thanks for the quick response.

**Closed by craigraw** 2022-07-12 06:03 UTC
