### ISSUE TITLE
error scanning QR

### ISSUE THREAD

**Issue by kkdao** [sparrowwallet/sparrow#119] opened 2021-05-03 17:05 UTC
using win10, and i get this error when trying to scan a QR code under the Script Policy and Keystores tab: java.util.concurrent.ExecutionException:com.github.sarxos.webcam.WebcamException: Cannot execute task

Here is the full stacktrace as requested: https://pastebin.com/W2Asrx87

**Comment by craigraw** [comment] 2021-05-04 06:40
Duplicate of #102 - it would be much appreciated if you could try checking what the problem is with loading the .dll as described in https://github.com/sparrowwallet/sparrow/issues/102#issuecomment-821070058. Is this a Windows Surface Pro machine?

**Closed by craigraw** 2021-05-04 06:40 UTC
