### ISSUE TITLE
Premix tab doesn't show anything except transaction history

### ISSUE THREAD

**Issue by Transisto** [sparrowwallet/sparrow#231] opened 2021-10-01 01:23 UTC
Send, Address, UTXO, and Setting show this empty page

Most likely related to `date must not be null` https://github.com/sparrowwallet/sparrow/issues/230

Wallet was just created in sparrow, has a passphrase.

![image](https://user-images.githubusercontent.com/388716/135551248-17455ba2-668b-4136-9b41-290c6edf3c5e.png)

**Comment by craigraw** [comment] 2021-10-01 05:27
Which public server are you using? 

Please try switching the public server and refreshing the wallet through the View menu. 

In this case, the server has provided TXO data on confirmed transactions without a date - which can only be a server error, since all blocks have a date.

**Comment by Transisto** [comment] 2021-10-01 05:44
Been checking most of the public server suggested and restarting sparrow, trying to check those left tabs.

Little by little they've been coming back,  I got "addresses" to show up first then send,  Setting wasn't showing up, not it is.

UTXOs doesn't show any.

**Comment by craigraw** [comment] 2021-10-01 06:56
Closing this off as a server issue.

**Closed by craigraw** 2021-10-01 06:56 UTC

**Comment by Transisto** [comment] 2021-10-05 01:36
I'm getting `java.lang.NullPointerException: date must not be null` with an elecrumX server,  

likechilds server
`Connected to ElectrumX 1.16.0 on protocol version 1.4`

Any server still has that behavior for this wallet.

**Comment by Transisto** [comment] 2021-10-05 02:07
I clicked "Refresh-wallet" all the tx disappeared, and never showed up. Connecting and reconnecting.

Restarted Sparrow and it now fetched the correct balance.

It's as if the wallet has a very hard time getting rid of a previous downloaded "date=null" packet.

**Comment by craigraw** [comment] 2021-10-05 08:43
The `date must not be null` issue has been "fixed" in d6ad7f4, but it's still unclear what's at the root of this - overloaded public servers perhaps, although I've never had any similar reports.
