### ISSUE TITLE
Error opening wallet-> Error parsing JSON: {"error": "hwi-2.0.218251586833274950946.tmp: error: the following arguments are required: command", "code": -2}

### ISSUE THREAD

**Issue by marcosdub** [sparrowwallet/sparrow#350] opened 2021-12-09 16:48 UTC
Hi, I can't open Trezor One wallet when I enter my passphrase, that throws the following text:

`Error parsing JSON: {"error": "hwi-2.0.218251586833274950946.tmp: error: the following arguments are required: command", "code": -2}`

Is a known issue of special characters used eg:    `,#*:"|`   Tested in Windows 10 - Not solved in new version 1.5.3

Is similar error [https://github.com/sparrowwallet/sparrow/issues/312](https://github.com/sparrowwallet/sparrow/issues/312)

Logs:

```
2021-12-09 14:35:02,100 ERROR [Thread-61] c.s.s.i.Hwi [null:-1] Error parsing JSON: {"error": "hwi-2.0.218251586833274950946.tmp: error: the following arguments are required: command", "code": -2}

com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 2 path $
	at com.google.gson@2.8.6/com.google.gson.Gson.fromJson(Unknown Source)
	at com.google.gson@2.8.6/com.google.gson.Gson.fromJson(Unknown Source)
	at com.google.gson@2.8.6/com.google.gson.Gson.fromJson(Unknown Source)
	at com.google.gson@2.8.6/com.google.gson.Gson.fromJson(Unknown Source)
	at com.sparrowwallet.sparrow@1.5.3/com.sparrowwallet.sparrow.io.Hwi.enumerate(Unknown Source)
	at com.sparrowwallet.sparrow@1.5.3/com.sparrowwallet.sparrow.io.Hwi$EnumerateService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.5.3/com.sparrowwallet.sparrow.io.Hwi$EnumerateService$1.call(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 2 path $
	at com.google.gson@2.8.6/com.google.gson.stream.JsonReader.beginArray(Unknown Source)
	at com.google.gson@2.8.6/com.google.gson.internal.bind.ArrayTypeAdapter.read(Unknown Source)
	... 15 common frames omitted
```
Screenshot https://drive.google.com/file/d/1RzMDXZouJ3U-Lbe4L0-e2Sbcf8U-2V_W/view?usp=sharing

Are you know about this issue?

```

**Comment by craigraw** [comment] 2021-12-13 12:31
Duplicate of #312, fixed in d76aecb.

**Closed by craigraw** 2021-12-13 12:31 UTC

**Comment by marcosdub** [comment] 2021-12-13 13:16
Hi, not fixed in the last version 1.5.4 of Windows 10 with Trezor One. You shouldn't close this issue!

Last logs here:
```
2021-12-13 14:09:34,080 ERROR [Thread-24] c.s.s.i.Hwi [null:-1] Error parsing JSON: {"error": "hwi-2.0.25818746436391111155.tmp: error: the following arguments are required: command", "code": -2}

com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 2 path $
	at com.google.gson@2.8.6/com.google.gson.Gson.fromJson(Unknown Source)
	at com.google.gson@2.8.6/com.google.gson.Gson.fromJson(Unknown Source)
	at com.google.gson@2.8.6/com.google.gson.Gson.fromJson(Unknown Source)
	at com.google.gson@2.8.6/com.google.gson.Gson.fromJson(Unknown Source)
	at com.sparrowwallet.sparrow@1.5.4/com.sparrowwallet.sparrow.io.Hwi.enumerate(Unknown Source)
	at com.sparrowwallet.sparrow@1.5.4/com.sparrowwallet.sparrow.io.Hwi$EnumerateService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.5.4/com.sparrowwallet.sparrow.io.Hwi$EnumerateService$1.call(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 2 path $
	at com.google.gson@2.8.6/com.google.gson.stream.JsonReader.beginArray(Unknown Source)
	at com.google.gson@2.8.6/com.google.gson.internal.bind.ArrayTypeAdapter.read(Unknown Source)
	... 15 common frames omitted
```
Please, you fix these and reply me!

**Comment by craigraw** [comment] 2021-12-13 13:19
I think you misunderstand :)

The problem has now been fixed in source (as of today). The 1.5.4 release was last week. The next release (1.5.5) will have the fix in it. You can also run from source if you want it sooner (or use a different OS).

**Comment by marcosdub** [comment] 2021-12-13 13:35
Ah sorry, all right, I I misunderstood, I will wait the next release. Thank you! 

I'm going to close the new issue.
