### ISSUE TITLE
Sign and Verify with Taproot

### ISSUE THREAD

**Issue by bensig** [sparrowwallet/sparrow#869] opened 2023-02-28 23:36 UTC
Are there any plans to support sign/verify message with taproot addresses? 

Seems to only support P2PKH, P2SH-P2WPKH, and P2WPKH currently.

![image](https://user-images.githubusercontent.com/1872138/221992548-4a8da265-9db0-44ad-8153-3801d2344595.png)

**Comment by bensig** [comment] 2023-02-28 23:37
Aside from `bitcoin-cli` is there a way to sign a message and verify that a taproot address is owned by someone?

**Comment by craigraw** [comment] 2023-03-01 05:42
Duplicate of #691, closing this in favour of the original issue. It's on the list to support.

**Closed by craigraw** 2023-03-01 05:42 UTC
