### ISSUE TITLE
UI bug: Optimise for efficiency is grayed out

### ISSUE THREAD

**Issue by haromz** [sparrowwallet/sparrow#452] opened 2022-03-03 19:43 UTC
**Steps to reproduce:**

1. Click "Send"
2. In "pay to" field open the dropdown and select a "paynym"
3. On the paynym window select a contact and press "Select contact"
4. When the paynym window closes, on the send page the "efficiency" toggle button is greyed out, you can't select it anymore.
5. Fill in the "label" field.
6. For the amount press "max"

The efficiency toggle is still greyed out but if you click the "privacy" toggle (already on but press it anyhow) the "efficiency" toggle comes back to normal, not greyed out anymore and you can toggle normally between the two.

PS. if on step 6 you enter the amount manually and don't press "Max" this will also stop greying out the button.

**Tested on:** Macbook pro 2019
**OS version:** MacOS Moneterey 12.2.1

**Comment by craigraw** [comment] 2022-03-04 09:57
Thanks for the bug report, max button issue fixed in 58f20da.

> PS. if on step 6 you enter the amount manually and don't press "Max" this will also stop greying out the button.

This is actually expected behaviour. When sending collaboratively, you can send as little as 1 sat to a PayNym, since you won't actually create an output of 1 sat - it is just the difference transferred in the coinjoin. This means that the Privacy toggle is always enabled for any amount. As the entered amount increases above the minimum dust threshold, the Efficiency button becomes active as well.

**Closed by craigraw** 2022-03-04 09:57 UTC
