### ISSUE TITLE
Ledger Nano S - Creation of new wallet "Ledger Nano S Error"

### ISSUE THREAD

**Issue by Odellian** [sparrowwallet/sparrow#561] opened 2022-05-21 13:42 UTC
Actions: File > New Wallet > Connect Hardware Wallet > Scan
Result: "Ledger Nano S Error"
Error Details: "Could not open client or get fingerprint information: open failed"
OS: Ubuntu 22.04 Desktop (Fresh install this week)
Sparrow: 1.6.4 
Firmware: 2.1.0 Ledger Nano S
Additional notes: I'm having no issue connecting to Ledger Live.

**Comment by craigraw** [comment] 2022-05-21 15:26
Thanks, duplicate of #553.

**Closed by craigraw** 2022-05-21 15:26 UTC

**Comment by Odellian** [comment] 2022-05-26 16:01
### Issue Unresolved with Sparrow 1.6.5 update.    

### System Details
- Mac Mini - Intel
- OS: Ubuntu 22.04 Desktop (Fresh install last week), not using VM
- Sparrow: sparrow_1.6.5-1_amd64.deb
- Device: Ledger Nano S
- Firmware: 2.1.0 Ledger Nano S
- Bitcoin App: 2.0.4

### Steps in Sparrow to Create Error
- Actions: File > New Wallet > Connect Hardware Wallet > Scan
- Result: "Ledger Nano S Error"
- Error Details: "Could not open client or get fingerprint information: open failed"

### Additional notes 
- I tested Sparrow-1.6.5-aarch64.dmg on my M1 Mac and have _no_ issues.  
- I'm having _no_ issue connecting to Ledger Live on M1 Mac.  
- My USB ports (Mac Mini, Ubuntu 22.04) work fine with other drives.  

I greatly appreciate the work you all put into this.  I'm happy to test as needed.  I can try my ColdCard. Thanks!

**Comment by Odellian** [comment] 2022-05-26 17:41
### Fix for Ubuntu 22.04 LTS Users

1. wget -q -O - https://raw.githubusercontent.com/LedgerHQ/udev-rules/master/add_udev_rules.sh | sudo bash 
2. sudo add-apt-repository universe
3. sudo apt install libfuse2
4. reboot machine - I'm not sure if this is required, but I performed this anyhow.  

Ledger Documentation: https://support.ledger.com/hc/en-us/articles/4404389606417-Download-and-install-Ledger-Live?docs=true

**Comment by craigraw** [comment] 2022-05-27 06:19
Great - it should also be possible to install the the udev rules via the command shown in the Sparrow Tools menu.

**Comment by Creator222** [comment] 2022-05-27 22:09
> ### Fix for Ubuntu 22.04 LTS Users
> 1. wget -q -O - https://raw.githubusercontent.com/LedgerHQ/udev-rules/master/add_udev_rules.sh | sudo bash
> 2. sudo add-apt-repository universe
> 3. sudo apt install libfuse2
> 4. reboot machine - I'm not sure if this is required, but I performed this anyhow.
> 
> Ledger Documentation: https://support.ledger.com/hc/en-us/articles/4404389606417-Download-and-install-Ledger-Live?docs=true

Does using the Ledger Live udev rules in this fix connect Sparrow's Ledger wallet to Ledger Live in anyway? Particularly regarding the xpub information, does it make it so that when we create a new hardware wallet with the Ledger Nano S on Sparrow the XPub is leaked to the Ledger Live server? Assuming you are operating Sparrow while connected to your personal node. 

Just trying to seek maximum privacy when using Sparrow for my ledger wallet operations.

-- Thanks Craig for your outstanding product with Sparrow wallet, and all the support you give to the community.

**Comment by Creator222** [comment] 2022-05-27 22:33
Also, I am having persistent errors setting up a Ledger Nano S on Sparrow 1.6.5 after installing the udev rules via the command in the Sparrow Tools menu: "Could not open client or get fingerprint information: open failed."

I appreciate any tips to get this Ledger working with Sparrow.

**Comment by craigraw** [comment] 2022-05-28 08:07
@Creator222 Sometimes the command fails, and you need to install udev rules manually. Have you tried the instructions in https://github.com/sparrowwallet/sparrow/issues/561#issuecomment-1138842546?

See also https://github.com/bitcoin-core/HWI/blob/master/hwilib/udev/README.md

It's also possible that there are VirtualBox related issues - USB can be tricky in a virtualized environment. 

Finally, make sure the Ledger Live is not running, and that the Ledger is running the Bitcoin app.

**Comment by Creator222** [comment] 2022-05-28 18:18
> @Creator222 Sometimes the command fails, and you need to install udev rules manually. Have you tried the instructions in [#561 (comment)](https://github.com/sparrowwallet/sparrow/issues/561#issuecomment-1138842546)?
> 
> See also https://github.com/bitcoin-core/HWI/blob/master/hwilib/udev/README.md
> 
> It's also possible that there are VirtualBox related issues - USB can be tricky in a virtualized environment.
> 
> Finally, make sure the Ledger Live is not running, and that the Ledger is running the Bitcoin app.

@craigraw Looks like it is working. I didn't change anything from what I was doing yesterday when I had the issue. I guess I closed out my VM when I put my pc to sleep last night. Woke up today, tried it again after reading your reply just to be sure I still had the problem, and the ledger is suddenly connecting properly to Sparrow. I have no idea why that is, but it's great. I've had Ledger Live uninstalled this whole time, and my device was running the Bitcoin app for every connection attempt.

Thanks for your support!
