### ISSUE TITLE
UTXOs tab forgets the sort column

### ISSUE THREAD

**Issue by BTCAlchemist** [sparrowwallet/sparrow#1051] opened 2023-08-05 00:52 UTC
In macOS (Intel) Sparrow 1.7.8, after the application is closed then re-opened, the 'UTXOs' section loses the column sort (the 'Transactions' section remembers the column sort). Each time the user re-opens the application, they must select the appropriate UTXOs column sort. Could you update this so the wallet file remembers the UTXO column sort?

<img width="937" alt="image" src="https://github.com/sparrowwallet/sparrow/assets/56145569/684af292-59fe-44e5-b389-dd8e513f80c1">

**Comment by craigraw** [comment] 2023-08-07 07:30
Duplicate of #328.

**Closed by craigraw** 2023-08-07 07:30 UTC
Labels: duplicate
