### ISSUE TITLE
Cannot Open Specter-Desktop Wallet

### ISSUE THREAD

**Issue by mflaxman** [sparrowwallet/sparrow#35] opened 2020-11-01 23:42 UTC
Just tested on `0.9.6` to see how progress is coming on #18 and this has gotten much worse :(

`File` > `Open Wallet...` > Choose file:
![Screen Shot 2020-11-01 at 5 23 15 PM](https://user-images.githubusercontent.com/448644/97818227-fd7cf980-1c66-11eb-8d2c-3bd89a372577.png)

File for reference:
```
$ cat any_recovery.json
{ "label": "Any Recovery", "blockheight": 1863986, "descriptor": "wsh(sortedmulti(1,[c7d0648a/48h/1h/0h/2h]tpubDEpefcgzY6ZyEV2uF4xcW2z8bZ3DNeWx9h2BcwcX973BHrmkQxJhpAXoSWZeHkmkiTtnUjfERsTDTVCcifW6po3PFR1JRjUUTJHvPpDqJhr/0/*,[12980eed/48h/1h/0h/2h]tpubDEkXGoQhYLFnYyzUGadtceUKbzVfXVorJEdo7c6VKJLHrULhpSVLC7fo89DDhjHmPvvNyrun2LTWH6FYmHh5VaQYPLEqLviVQKh45ufz8Ae/0/*,[3a52b5cd/48h/1h/0h/2h]tpubDFdbVee2Zna6eL9TkYBZDJVJ3RxGYWgChksXBRgw6y6PU1jWPTXUqag3CBMd6VDwok1hn5HZGvg6ujsTLXykrS3DwbxqCzEvWoT49gRJy7s/0/*,[f7d04090/48h/1h/0h/2h]tpubDF7FTuPECTePubPXNK73TYCzV3nRWaJnRwTXD28kh6Fz4LcaRzWwNtX153J7WeJFcQB2T6k9THd424Kmjs8Ps1FC1Xb81TXTxxbGZrLqQNp/0/*))#tatkmj5q" }
```
--

Btw, `File` > `Import Wallet...` is worse. The file is greyed out and I can't select anything. I can hit `Scan` but then Sparrow immediately crashes.
![Screen Shot 2020-11-01 at 5 28 46 PM](https://user-images.githubusercontent.com/448644/97818387-c2c79100-1c67-11eb-96af-791f9a8a4892.png)

Even if the functionality worked all of these UIs would be confusing. I just want to copy-paste in a descriptor, there's no reason for me to be saving files or scanning QR codes (if Specter is on my local machine).

--

There's also creating a new wallet and then hitting `Edit...`, but this also doesn't work with SD's copy-paste formatting (it adds `\`s that Sparrow can't parse):
![Screen Shot 2020-11-01 at 5 32 32 PM](https://user-images.githubusercontent.com/448644/97818473-3ff30600-1c68-11eb-94fe-7f464c47a41d.png)

If I manually edit the `wsh` entry from SD to look like what's in `any_recovery.json` I'm able to make it to this error message:
![Screen Shot 2020-11-01 at 5 35 24 PM](https://user-images.githubusercontent.com/448644/97818561-b09a2280-1c68-11eb-81b0-3c2864f7bce8.png)

I don't see anywhere to tell sparrow that tpub is testnet, is testnet supported?

**Comment by craigraw** [comment] 2020-11-02 05:55
Testnet is supported. In fact, the majority of these issues are caused by simply not enabling testnet, which can be done in a number of ways and is documented in the project root README.md: https://github.com/sparrowwallet/sparrow#configuration

With testnet running, I have:

1. Opened the file above
2. Cut and pasted the output descriptor into the dialog presented by the Edit descriptor button on the Wallet Settings page

Both of the above worked without issues.

There is a minor bug in the current release with the file selection dialog with the 'All files' filter selected - it was a fix for Linux but unfortunately that fix caused a regression in OSX. The workaround until the next release later this week is to choose the JSON/TXT file filter in that dialog.

I wasn't aware the Specter was adding (illegal) `\` characters - I have removed those from the output descriptor when copy pasting in https://github.com/sparrowwallet/sparrow/commit/13a486597c3f6410e222c33707e8a946bc1846b7. 

I'd appreciate it if you can share any errors in `sparrow.log` in the Sparrow home folder regarding the crash you experienced with the Scan button - I imagine this may have something to do with the native webcam library.

**Comment by craigraw** [comment] 2021-03-10 12:56
All bugs noted in the previous comment have been fixed in previous versions, so closing this off.

**Closed by craigraw** 2021-03-10 12:56 UTC
