### ISSUE TITLE
I can not create a wallet on Sparrow

### ISSUE THREAD

**Issue by Projectedguy** [sparrowwallet/sparrow#625] opened 2022-07-15 15:34 UTC
I am trying to create a wallet but I can't. All gray and disabled. Although it says l am connected to public server. when l try to create a wallet all l see is a empty gray screen and l can not see any wallet file in wallet folder.

![screen](https://user-images.githubusercontent.com/109364790/179256846-c3d31c4b-27a0-4a65-86e7-1b366c4ede5a.PNG)
![screen2](https://user-images.githubusercontent.com/109364790/179256894-e7fb9743-e806-45cb-ba0f-a7e1d00f16c3.PNG)
.

**Comment by craigraw** [comment] 2022-07-15 16:50
Take a look in the log file (Help menu) to see if there are any errors.

**Comment by Projectedguy** [comment] 2022-07-15 19:38
ERROR [JavaFX Application Thread] c.s.s.MainApp [null:-1] Exception in thread "JavaFX Application Thread"
java.lang.IllegalStateException: Location is not set.

That is the problem but l do not know how to solve that

**Comment by craigraw** [comment] 2022-07-18 06:31
A strange error. Are you running on Windows? If so, what version? Is there anything unusual about your setup? How did you install Sparrow?

**Comment by Projectedguy** [comment] 2022-07-18 17:08
my computer is a mac, using both macos and windows on the same computer. it is windows 10 pro. l have the same problem on macos catalina. l installed sparrow regularly and l verified the signature of the it before installing. I can use any other sofware wallet programs like electrum, wasabi wallet etc.

**Comment by craigraw** [comment] 2022-07-19 06:51
Thanks. Can you copy paste the entire exception that you screenshotted part of above? Or even just the entire log file.

**Comment by Projectedguy** [comment] 2022-07-19 11:14
Yeah;


![screenn](https://user-images.githubusercontent.com/109364790/179737309-780d961f-868f-4271-8ad4-ed0444a433b6.PNG)

**Comment by craigraw** [comment] 2022-07-22 07:15
I've spent a few days thinking about this but unfortunately I'm no closer to understanding the cause. The error is so fundamental in nature it's difficult to see why it should occur at all. On Windows my best suggestion at this time is to try reinstalling, using the `.zip` installation file instead. 

Another question is whether the same error is printed in the logs when you run Sparrow on macOS? You mentioned that it occurred there as well, but I wanted to check this.

**Comment by Projectedguy** [comment] 2022-07-23 09:41
> I've spent a few days thinking about this but unfortunately I'm no closer to understanding the cause. The error is so fundamental in nature it's difficult to see why it should occur at all. On Windows my best suggestion at this time is to try reinstalling, using the `.zip` installation file instead.
> 
> Another question is whether the same error is printed in the logs when you run Sparrow on macOS? You mentioned that it occurred there as well, but I wanted to check this.

I tried it on macOS but result is the same. lt does not create a wallet and show the same errors. Also l tried to install the .zip file a few mins ago but nothing changed :(

**Comment by craigraw** [comment] 2022-07-25 06:55
It would be useful to know if the same occurs when you run from source. Doing so is a bit technical, but not too difficult. On Windows, I first install [Git Bash for Windows](https://git-scm.com/download/win) so that I have a Unix-like shell/command line. 

Using that command line, I then install a package manager for Java called [sdkman.io](https://sdkman.io/) with
```
curl -s "https://get.sdkman.io" | bash
```

I then install Java 17 with:
```
sdk install java 17.0.2-tem
```

From there, run:
```
GIT_TAG="1.6.5"
git clone --recursive --branch "${GIT_TAG}" https://github.com/sparrowwallet/sparrow.git
cd sparrow
./sparrow
```

Sparrow will then be running from source, which might solve this problem, and at the same time provide some useful information that might track the cause of the issue down.

**Comment by Projectedguy** [comment] 2022-07-26 15:37
Thank you, reall appreciated but l got such failures:
 When l enter the code : curl -s "https://get.sdkman.io" | bash, it says this;
![screen23](https://user-images.githubusercontent.com/109364790/181047611-a85fb6f6-eef0-4db5-aeca-ac80c6d62470.PNG)

Although l got zip, and l downloaded zip and re-install

l entered the command ;

GIT_TAG="1.6.5"
git clone --recursive --branch "${GIT_TAG}" https://github.com/sparrowwallet/sparrow.git
cd sparrow
./sparrow

without     sdk install java 17.0.2-tem but now it says; 
![screen22](https://user-images.githubusercontent.com/109364790/181048662-b7f3d674-4ab1-4999-a1b0-f89650758d56.PNG)

l tried online to fix the zip issue but it did not work. Thank you for your help tho. Do not waste your time for me, l should try it on another computer maybe.

**Comment by craigraw** [comment] 2022-07-27 09:42
Thanks - we're almost there! It would be good to try understand this error better.

You can do the following to install zip into Git Bash:
1. [Navigate to this sourceforge page](https://sourceforge.net/projects/gnuwin32/files/zip/3.0/)
2. Download zip-3.0-bin.zip
3. In the zipped file, in the bin folder, find the file zip.exe.
4. Extract the file zip.exe to your mingw64 bin folder (for me: C:\Program Files\Git\mingw64\bin)

Then try again with
```
sdk install java 17.0.2-tem
```

**Comment by Projectedguy** [comment] 2022-07-28 11:54
> Thanks - we're almost there! It would be good to try understand this error better.
> 
> You can do the following to install zip into Git Bash:
> 
> 1. [Navigate to this sourceforge page](https://sourceforge.net/projects/gnuwin32/files/zip/3.0/)
> 2. Download zip-3.0-bin.zip
> 3. In the zipped file, in the bin folder, find the file zip.exe.
> 4. Extract the file zip.exe to your mingw64 bin folder (for me: C:\Program Files\Git\mingw64\bin)
> 
> Then try again with
> 
> ```
> sdk install java 17.0.2-tem
> ```

Thank you, 

l finally installed using the command;

sdk install java 17.0.2-tem

Then l entered the commands; 

GIT_TAG="1.6.5"
git clone --recursive --branch "${GIT_TAG}" https://github.com/sparrowwallet/sparrow.git
cd sparrow
./sparrow
![scr](https://user-images.githubusercontent.com/109364790/181498857-422c42f9-e8c3-4032-b5d2-2a64e21144ee.PNG)
![scr1](https://user-images.githubusercontent.com/109364790/181498876-fd4eac4f-4a3c-4427-954d-a78acda437bb.PNG)
![scr3](https://user-images.githubusercontent.com/109364790/181498890-0e649521-da46-4661-9866-e22c20bc263f.PNG)

**Comment by craigraw** [comment] 2022-07-28 12:20
Great - press Enter on that last command and Sparrow should start.

**Comment by Projectedguy** [comment] 2022-07-28 12:32
> Great - press Enter on that last command and Sparrow should start.

Unfortunately, it is the same
![scr](https://user-images.githubusercontent.com/109364790/181505678-bc50a208-82d2-4360-be42-e2a7459d1917.PNG)
![scrr](https://user-images.githubusercontent.com/109364790/181505689-a15f53ee-2f78-40a0-90ea-92d43fa598aa.PNG)

**Comment by craigraw** [comment] 2022-07-28 13:14
Ok, let's try another step. I've added a little code which might fix things, but will at least tell me a little more if it fails.

First, in the same folder, run
```
git checkout master
```

Then, run again
```
./sparrow
```

**Comment by Projectedguy** [comment] 2022-07-28 13:33
> Ok, let's try another step. I've added a little code which might fix things, but will at least tell me a little more if it fails.
> 
> First, in the same folder, run
> 
> ```
> git checkout master
> ```
> 
> Then, run again
> 
> ```
> ./sparrow
> ```

l did it but;
![sss](https://user-images.githubusercontent.com/109364790/181518077-4cb0e832-a06c-4cf7-a740-d1924a2eedc0.PNG)
![sss1](https://user-images.githubusercontent.com/109364790/181518092-239b86d8-0ea2-4488-a1b2-7424bc5e4dd9.PNG)
![sss2](https://user-images.githubusercontent.com/109364790/181518105-3ba8f61e-034f-4720-87f1-da5e4e049845.PNG)

**Comment by craigraw** [comment] 2022-07-28 13:37
Sorry, my bad. Run
```
git pull --recurse-submodules
```
first, before
```
./sparrow
```

**Comment by Projectedguy** [comment] 2022-07-28 13:58
Unfortunately it shows the same error saying;

2022-07-28 16:55:29,890 ERROR Exception in thread "JavaFX Application Thread"
java.lang.IllegalStateException: Cannot find wallet/sett▒ngs.fxml
![ssss](https://user-images.githubusercontent.com/109364790/181523651-a713683c-b002-449f-a613-0b9249a4b9b6.PNG)

**Comment by craigraw** [comment] 2022-07-28 14:10
Aha - the strange ▒ character in 'Cannot find wallet/sett▒ngs.fxml' is clearly where things are going wrong.

I've made a change that may help here. Please run again
```
git pull --recurse-submodules
```
followed by
```
./sparrow
```

**Comment by Projectedguy** [comment] 2022-07-28 14:16
You finally did it brother, l guess now it works. I am really appreciated. Anything that l should know about it? Like, should l run it alwasy using git bash or just from the .exe file?
![finally](https://user-images.githubusercontent.com/109364790/181532094-b452b29b-6f4e-49bf-b653-66ef0bd7d105.PNG)
?

**Comment by craigraw** [comment] 2022-07-28 16:12
Thanks for your patience in figuring this out! 

It turns out to be some String operations (in this case, turning a String to lowercase) are locale specific: https://stackoverflow.com/questions/11063102/using-locales-with-javas-tolowercase-and-touppercase

This seems to particularly affect Turkish locales. I'm fixing this now throughout the app - I'll have updated it for you to test tomorrow.

**Comment by Projectedguy** [comment] 2022-07-28 17:11
> 

Thank you for your help and patience too!

Sparrow wallet is a really nice and usefull software. Looking forward to test it.

**Comment by Projectedguy** [comment] 2022-07-28 17:11
> Thanks for your patience in figuring this out!
> 
> It turns out to be some String operations (in this case, turning a String to lowercase) are locale specific: https://stackoverflow.com/questions/11063102/using-locales-with-javas-tolowercase-and-touppercase
> 
> This seems to particularly affect Turkish locales. I'm fixing this now throughout the app - I'll have updated it for you to test tomorrow.

Thank you for your help and patience too!

Sparrow wallet is a really nice and usefull software. Looking forward to test it.

**Comment by craigraw** [comment] 2022-07-29 07:49
Ok, the uppercase and lowercase functions have all now been converted to be locale-insensitive in e0a14fde.

You can run
```
git pull --recurse-submodules
```

and then
```
./sparrow
```

to test it out.

**Comment by Projectedguy** [comment] 2022-07-29 16:08
> Ok, the uppercase and lowercase functions have all now been converted to be locale-insensitive in [e0a14fd](https://github.com/sparrowwallet/sparrow/commit/e0a14fdea6bb2ad887fded6d41227e2737392670).
> 
> You can run
> 
> ```
> git pull --recurse-submodules
> ```
> 
> and then
> 
> ```
> ./sparrow
> ```
> 
> to test it out.

Thank you brother,

l guess now it works well. Thank you.

![scrr](https://user-images.githubusercontent.com/109364790/181799940-42e8a496-5822-4098-8456-2f838b257020.PNG)

**Comment by craigraw** [comment] 2022-08-01 09:41
Great, thanks again for your help. Closing this off.

**Closed by craigraw** 2022-08-01 09:41 UTC

**Comment by Projectedguy** [comment] 2022-08-01 10:27
> Great, thanks again for your help. Closing this off.

Lastly, will there be a software update related to this issue? 1.6.5 version still have the same problem. I will be waiting for the update.

**Comment by craigraw** [comment] 2022-08-01 11:16
Yes, will be in the next release, coming soon.

**Comment by craigraw** [comment] 2022-08-08 10:03
FYI Sparrow v1.6.6 contains the fix for this issue.

**Comment by Projectedguy** [comment] 2022-08-09 08:34
> 

Already downloaded, thank you for fixing it. I'm really happy to have made a small contribution to making this software available to people in my country tho.
