### ISSUE TITLE
Debian 11/bullseye apt/dpkg does not support zst compression used by sparrow_1.7.2-1_amd64.deb

### ISSUE THREAD

**Issue by gStart9** [sparrowwallet/sparrow#834] opened 2023-02-12 17:39 UTC
Thanks for 1.7.2, so many amazing changes, can't wait to use it.  But!
```
sudo dpkg -i ./sparrow_1.7.2-1_amd64.deb 
dpkg-deb: error: archive './sparrow_1.7.2-1_amd64.deb' uses unknown compression for member 'control.tar.zst', giving up
dpkg: error processing archive ./sparrow_1.7.2-1_amd64.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 ./sparrow_1.7.2-1_amd64.deb
 ```

I found this which seems to explain it:
https://unix.stackexchange.com/questions/669004/zst-compression-not-supported-by-apt-dpkg

**Comment by craigraw** [comment] 2023-02-12 17:50
Duplicate of https://github.com/sparrowwallet/sparrow/issues/829 - see that issue for a temporary fix to repackage the .deb, an updated release will follow shortly.

Also (since this is relevant to Start9) I only noticed that btc-proxy-server doesn't support named parameters for JSON-RPC after the release. I've reported to that project and have updated Sparrow's new Cormorant server to use array-based parameters.

**Closed by craigraw** 2023-02-12 17:50 UTC
