### ISSUE TITLE
[Feature] Fiat currency amount selection

### ISSUE THREAD

**Issue by marcocattaneogotam** [sparrowwallet/sparrow#1273] opened 2024-02-20 07:22 UTC
I think it is critical to give the ability to select the amount of an outgoing transaction in fiat currency, rather than being forced to type it in bitcoin/sats.

Thanks

**Comment by craigraw** [comment] 2024-02-20 07:25
Duplicate of #147

**Closed by craigraw** 2024-02-20 07:25 UTC
