### ISSUE TITLE
Multisig wallet, signature fails on hw wallets on 1.7.2 but are ok in 1.7.1

### ISSUE THREAD

**Issue by fzuleta** [sparrowwallet/sparrow#868] opened 2023-02-28 21:09 UTC
hi,

ok this one gave me a good scare 😅

when signing a tx in 1.7.2 made by a multisig (2/3) wallet in 1.7.1, Im getting `Could not parse signed PSBT` in any of the 3 hardware wallets.

<img width="1394" alt="image" src="https://user-images.githubusercontent.com/3056157/221978738-cb89f061-08ab-4e28-ab84-73d73b7d633a.png">

when signing in 1.7.1, signature is accepted and ok.

not sure if it's an indication of sth, but the derivation path is `m/48'/0'/0'/2'` , I did notice that new wallets in 1.7.2 start with `m/84`.

should I recreate the multisig an move all funds over?

**Comment by craigraw** [comment] 2023-03-01 05:39
Duplicate of #839 - it's an HWI bug. I suggest waiting for the a new version of Sparrow, which will be out imminently.

**Closed by craigraw** 2023-03-01 05:39 UTC
