### ISSUE TITLE
Sparrow will not re-connect to BTC node on Local Machine

### ISSUE THREAD

**Issue by jonbon7** [sparrowwallet/sparrow#1135] opened 2023-10-20 23:01 UTC
I know there have been several questions asked about this before. I've read them over many times now and it still does not seem to fix this issue I'm experiencing.

I've followed the directions to connect sparrow to btc core on the setup guide religiously, and I still cannot get Sparrow to reliably connect to bitcoin core. I'm running the latest versions of both Sparrow 1.79, and Core 25.1.0. The only time Sparrow ever connects to BTC core for me is when I launch BTC core fresh, and then sparrow fresh with wallet, or no wallet loaded. (it doesn't seems to matter in my case.) And even then it's spotty at best. The main issue is that if I connect by chance upon startup, disconnect, and then try to connect again, Sparrow wallet is stuck "connecting" until I stop its attempt . I noted there was a solution floating around:

"The current solution is to stop both Bitcoin Core and Sparrow, delete the Bitcoin Core wallet, restart both and then make sure to create a wallet in Sparrow before restarting either application (to ensure some keys are added to the Bitcoin Core wallet first"

Is the solution here really to shut btc core and sparrow down before wanting to establish a connection again?

I am also unable to connect remotely... but I'd like to start small and address the local inconsistency first.

Apologize if this is not the right forum for this, but I can't find a solution to this anywhere. I've attached my log file, as this problem seems to have no rhyme or reason about it. I would focus on the activity from 10/20 onward.

[sparrow.log](https://github.com/sparrowwallet/sparrow/files/13059103/sparrow.log)

**Comment by PrinceOfEgypt** [comment] 2023-10-20 23:04
I am also having the exact same issue.

**Comment by craigraw** [comment] 2023-10-21 07:10
@jonbon7 are you running any other software that is connecting to Bitcoin Core? It appears something is unloading the wallet that Sparrow is using.

**Comment by jonbon7** [comment] 2023-10-21 12:35
@craigraw not that I am aware of. Like another wallet? The answer to that is no. There are very few programs on this pc other than btc core, sparrow. Any way I can verify what else is connecting to btc core? I am receiving several inbound and outbound requests (20+) via the node connections but I don’t think that is what you are referring to.

**Comment by PrinceOfEgypt** [comment] 2023-10-21 15:03
@craigraw  I just tried again and this is the behavior I'm observing:

1. When I click on "test connection" in the server preferences a new wallet called "cormorant" is created in bitcoin core. bitcoin-cli listwallets shows that it is loaded (to answer your earlier question, yes I do have other wallets / apps connected to core (bwt and fully noded)

![image](https://github.com/sparrowwallet/sparrow/assets/2649235/54fcfa3e-124e-43ef-8e96-975cb997d7bd)

2, the test connection never succeeds - it remains stuck on "connecting":

![image](https://github.com/sparrowwallet/sparrow/assets/2649235/4c05c42a-c7a8-4476-8003-6f08333c3c9e)

3. If I close and reopen sparrow and try to flip the switch on the lower right to connect, it is stuck on "connecting" in the status bar:

![image](https://github.com/sparrowwallet/sparrow/assets/2649235/ca075140-0fc1-4137-bb7f-d997b576def4)

4. bitcoin-cli still shows the cormorant wallet is loaded.
5. nothing shows up in sparrow.log

**Comment by craigraw** [comment] 2023-10-21 15:11
@PrinceOfEgypt Can you try all of this again, but with DEBUG logging?
1. Close all wallet tabs, then close Sparrow and delete sparrow.log
2. Run Sparrow with DEBUG logging:
```
Sparrow.exe -l DEBUG
```
3. Use the Test Connection
4. Attach sparrow.log here

**Comment by PrinceOfEgypt** [comment] 2023-10-21 15:22
@craigraw this time the test connection worked, but after closing the server preferences sparrow would not reconnect (again stuck on "connecting").

sparrow and bitcoin log files are attached
[debug.log](https://github.com/sparrowwallet/sparrow/files/13061077/debug.log)
[sparrow.log](https://github.com/sparrowwallet/sparrow/files/13061082/sparrow.log)

**Comment by craigraw** [comment] 2023-10-21 15:54
@PrinceOfEgypt I assume all the log lines in sparrow.log appeared before Sparrow got stuck on connecting?

If not: Please indicate which log lines appear after.

If so: I can't see any errors in the log, so I am starting to think this is some kind of network related issue. I'm not sure how technical you are, but what I would do is use [Wireshark](https://www.wireshark.org/download.html) and filter on port 8332 traffic to try determine what is going on when Sparrow fails to connect. It's possible that the packets Sparrow is sending are simply being dropped for some unknown reason.

**Comment by PrinceOfEgypt** [comment] 2023-10-21 16:58
@craigraw if you look at the sparrow.log there's a section at the end that appears to be repeating - sparrow appears to be calling getblockhash over and over for the same block (813195) and getting a response. Is it somehow getting stuck in an infinite loop?

To answer your question, the repeated calls to getblockhash are happening while sparrow is stuck on "connecting"

DEBUG [Timer-1] c.s.s.n.c.b.BitcoindTransport [null:-1] > {"jsonrpc":"2.0","method":"getblockhash","params":[813195],"id":1}
2023-10-21 10:19:26,180 DEBUG [Timer-1] c.s.s.n.c.b.BitcoindTransport [null:-1] < {"result":"000000000000000000014aeeaf9304117771240a137984d2a645a8c161b1da82","error":null,"id":1}
2023-10-21 10:19:26,182 DEBUG [Timer-1] c.s.s.n.c.b.BitcoindTransport [null:-1] > {"jsonrpc":"2.0","method":"listsinceblock","params":["000000000000000000014aeeaf9304117771240a137984d2a645a8c161b1da82",1,true,true,true],"id":1}
2023-10-21 10:19:26,515 DEBUG [Timer-1] c.s.s.n.c.b.BitcoindTransport [null:-1] < {"result":{"transactions":[],"removed":[],"lastblock":"000000000000000000014aeeaf9304117771240a137984d2a645a8c161b1da82"},"error":null,"id":1}
2023-10-21 10:19:30,910

**Comment by PrinceOfEgypt** [comment] 2023-10-21 19:52
@craigraw  I did another test, please see the steps I followed and attached logs:

1. Closed all wallets in Sparrow
2. unloaded and deleted "cormorant" wallet in cor
3. Started Sparrow, changed connection to bitcoin core and clicked "test connection", connection succeeded.
4. Closed connection settings, Sparrow showed a green switch in bottom right.
5. Opened an existing wallet, Sparrow showed "scanning" in the pane under transactions for about an hour (it showed % progress).
6. Waited until I got the "Fiinshed loading message"
7. Shut down sparrow
8. Restarted with debug log and wireshark running
9. Sparrow got stuck on "connecting", the status are said "Wallet loading history for <wallet name>"
10. if you look at the sparrow.log and wireshark capture, you'll see that sparrow was talking to core during that time. I let it run for about 5 minutes and it never showed as connected, but according to the log file it was continuously talking back and forth with core during this time

[sparrow.log](https://github.com/sparrowwallet/sparrow/files/13061688/sparrow.log)
[wireshark.zip](https://github.com/sparrowwallet/sparrow/files/13061689/wireshark.zip)

**Comment by craigraw** [comment] 2023-10-22 14:06
Thanks for the info. The issue is becoming clearer, even as the cause remains a mystery. 

The Cormorant server Sparrow uses internally to connect to Bitcoin Core provides an Electrum JSON-RPC interface that the Sparrow wallet uses to retrieve data. You can see Sparrow opening a socket to this interface with `c.s.s.n.TcpTransport` and talking to Cormorant with the `c.g.a.s.s.JsonRpcServer` lines. For example, on the first successful attempt:
```
2023-10-21 10:15:07,150 DEBUG [Thread-7] c.s.s.n.TcpTransport [null:-1] Created Socket[addr=/127.0.0.1,port=57428,localport=57429]
2023-10-21 10:15:07,159 DEBUG [pool-2-thread-1] c.g.a.s.s.JsonRpcServer [null:-1] Request : {"jsonrpc":"2.0","method":"server.version","params":["Sparrow","1.4"],"id":1}
2023-10-21 10:15:07,196 DEBUG [pool-2-thread-1] c.g.a.s.s.JsonRpcServer [null:-1] Response: {"id":1,"result":["Cormorant 1.7.9","1.4"],"jsonrpc":"2.0"}
2023-10-21 10:15:07,200 DEBUG [Thread-7] c.s.s.n.ElectrumServer [null:-1] Upgrading to batched JSON-RPC
2023-10-21 10:15:07,211 DEBUG [pool-2-thread-1] c.g.a.s.s.JsonRpcServer [null:-1] Request : {"jsonrpc":"2.0","method":"server.banner","params":[],"id":2}
2023-10-21 10:15:07,213 DEBUG [pool-2-thread-1] c.g.a.s.s.JsonRpcServer [null:-1] Response: {"id":2,"result":"Cormorant 1.7.9\n/Satoshi:25.1.0/","jsonrpc":"2.0"}
2023-10-21 10:15:07,249 DEBUG [pool-2-thread-1] c.g.a.s.s.JsonRpcServer [null:-1] Request : [{"jsonrpc":"2.0","method":"blockchain.estimatefee","params":[1],"id":3},{"jsonrpc":"2.0","method":"blockchain.estimatefee","params":[2],"id":4},{"jsonrpc":"2.0","method":"blockchain.estimatefee","params":[3],"id":5},{"jsonrpc":"2.0","method":"blockchain.estimatefee","params":[4],"id":6},{"jsonrpc":"2.0","method":"blockchain.estimatefee","params":[5],"id":7},{"jsonrpc":"2.0","method":"blockchain.estimatefee","params":[10],"id":8},{"jsonrpc":"2.0","method":"blockchain.estimatefee","params":[25],"id":9},{"jsonrpc":"2.0","method":"blockchain.estimatefee","params":[50],"id":10}]
2023-10-21 10:15:10,462 DEBUG [pool-2-thread-1] c.g.a.s.s.JsonRpcServer [null:-1] Response: [{"id":3,"result":1.5032E-4,"jsonrpc":"2.0"},{"id":4,"result":1.5032E-4,"jsonrpc":"2.0"},{"id":5,"result":1.2291E-4,"jsonrpc":"2.0"},{"id":6,"result":1.1874E-4,"jsonrpc":"2.0"},{"id":7,"result":1.1874E-4,"jsonrpc":"2.0"},{"id":8,"result":4.97E-5,"jsonrpc":"2.0"},{"id":9,"result":2.235E-5,"jsonrpc":"2.0"},{"id":10,"result":1.754E-5,"jsonrpc":"2.0"}]
continues...
```

On the second, unsuccessful attempt however, we only see
```
2023-10-21 10:15:31,616 DEBUG [Thread-9] c.s.s.n.TcpTransport [null:-1] Created Socket[addr=/127.0.0.1,port=57442,localport=57443]
2023-10-21 10:15:31,618 DEBUG [pool-3-thread-1] c.g.a.s.s.JsonRpcServer [null:-1] Request : {"jsonrpc":"2.0","method":"server.version","params":["Sparrow","1.4"],"id":1}
2023-10-21 10:15:31,622 DEBUG [pool-3-thread-1] c.g.a.s.s.JsonRpcServer [null:-1] Response: {"id":1,"result":["Cormorant 1.7.9","1.4"],"jsonrpc":"2.0"}
```

and nothing further. So it appears Sparrow is not properly receiving this response from Cormorant, but only occasionally. This is why Sparrow appears to be endlessly connecting, while Cormorant is running fine in the background. Why this happens is a mystery, but the intermittent nature and rarity of this problem still makes me think it is network related.

@PrinceOfEgypt is it possible to use Wireshark to try capture this `JsonRpcServer` traffic? It should be possible to capture all localhost traffic and then apply filtering to it once the port is known from the `TcpTransport` log lines. That should tell us if the data is actually being sent, and if there are any differences between successful and unsuccessful connection attempts.

**Comment by PrinceOfEgypt** [comment] 2023-10-22 14:11
@craigraw i can try, I'm guessing the ports are not going to be predictable? I would have to capture everything on the loopback adapter?

**Comment by craigraw** [comment] 2023-10-22 14:13
Yes correct.

**Comment by PrinceOfEgypt** [comment] 2023-10-22 14:21
Another question - to eliminate windows firewall from the picture, is the cormorant server running as a separate process or is it running in proc with sparrow? Should I try adding sparrow.exe to the exclusions in the firewall?

**Comment by craigraw** [comment] 2023-10-22 14:24
> is the cormorant server running as a separate process or is it running in proc with sparrow?

In process with Sparrow.

> Should I try adding sparrow.exe to the exclusions in the firewall?

Good idea!

**Comment by PrinceOfEgypt** [comment] 2023-10-22 15:03
@craigraw  here's a log file and wireshark capture. One thing I saw right away is that it tried to open the socket 3 times.

![image](https://github.com/sparrowwallet/sparrow/assets/2649235/232ee165-0d3c-4b1e-8973-a3f5336d874b)

sparrow.exe was already in the list of firewall exclusions unfortunately.. so that doesn't seem to make a difference :(
[sparrow.log](https://github.com/sparrowwallet/sparrow/files/13063733/sparrow.log)
[sparrow 20231022.zip](https://github.com/sparrowwallet/sparrow/files/13063734/sparrow.20231022.zip)

**Comment by craigraw** [comment] 2023-10-22 15:51
Yes, Sparrow opens a new socket every time it tries to connect. It looks like it tried twice with one instance of Cormorant, and then again with a second.

It's looking more like a network/firewall issue now. For the 3 times Sparrow tried to connect to Cormorant, the first and last seem to not return a response while the second actually fails:
```
com.sparrowwallet.sparrow.net.ElectrumServerRpcException: Error getting server version
	at com.sparrowwallet.sparrow@1.7.9/com.sparrowwallet.sparrow.net.SimpleElectrumServerRpc.getServerVersion(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.9/com.sparrowwallet.sparrow.net.ElectrumServer.getServerVersion(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.9/com.sparrowwallet.sparrow.net.ElectrumServer$ConnectionService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.9/com.sparrowwallet.sparrow.net.ElectrumServer$ConnectionService$1.call(Unknown Source)
....
Caused by: java.net.SocketException: Socket is closed
	at java.base/java.net.Socket.getOutputStream(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.9/com.sparrowwallet.sparrow.net.TcpTransport.writeRequest(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.9/com.sparrowwallet.sparrow.net.TcpTransport.pass(Unknown Source)
	... 17 common frames omitted
```

There's surprisingly little in the capture file, just a few packets indicating the start of communication with port 53540. If the capture was running the entire time, I suspect we're not getting all the communications, perhaps more fiddling with Wireshark may help:

<img width="1264" alt="Screenshot 2023-10-22 at 17 47 07" src="https://github.com/sparrowwallet/sparrow/assets/862166/df6e92da-5ccf-40eb-a502-ab6301276f23">

**Comment by PrinceOfEgypt** [comment] 2023-10-22 17:57
Yes, wireshark was running the entire time. 

Is there anything else you can think of that I can try?

**Comment by PrinceOfEgypt** [comment] 2023-10-22 18:25
@craigraw when I run the "test connection" from the server properties, shouldn't I see something listening on port 53540?

![image](https://github.com/sparrowwallet/sparrow/assets/2649235/8885753a-401a-4351-ab12-a5c21699b366)

**Comment by craigraw** [comment] 2023-10-23 06:24
> when I run the "test connection" from the server properties, shouldn't I see something listening on port 53540?

Yes, although the port number will change with each new connection attempt as per the logs.

> Is there anything else you can think of that I can try?

1. I think it's important to try figure out the Wireshark capture - there are clearly packets missing, which makes me doubt the results we are seeing. I just tested it myself and managed to capture the full communication on the Cormorant port. Try to get a capture of a successful connection (including the JSON requests and responses seen in the log) to make sure things are working.
2. We can try to get Sparrow to do a thread dump at this point of getting stuck on "Connecting..." to see what is going on internally. It is not simple to generate a thread dump on Windows unfortunately - you may need to install the Java JDK so you have `jstack.exe`. More here: https://access.redhat.com/solutions/19170

**Comment by PrinceOfEgypt** [comment] 2023-10-23 11:30
ok, can you share a screenshot of the successful connection in wireshark so I know what I'm looking for?

I'll look into the Java JDK and capturing a thread dump. I've done it plenty of times with .Net / C# apps so I understand the concept, just haven't ever done it with a Java app.

**Comment by PrinceOfEgypt** [comment] 2023-10-23 14:01
@craigraw Here are 3 thread dumps, taken 1 minute apart while the server properties dialog was stuck on "connecting". I've also included the output of netstat -aon and sparrow.log.
[core_connecting2.txt](https://github.com/sparrowwallet/sparrow/files/13071462/core_connecting2.txt)
[core_connecting3.txt](https://github.com/sparrowwallet/sparrow/files/13071463/core_connecting3.txt)
[netstat.txt](https://github.com/sparrowwallet/sparrow/files/13071464/netstat.txt)
[netstat2.txt](https://github.com/sparrowwallet/sparrow/files/13071465/netstat2.txt)
[netstat3.txt](https://github.com/sparrowwallet/sparrow/files/13071466/netstat3.txt)
[sparrow.log](https://github.com/sparrowwallet/sparrow/files/13071467/sparrow.log)
[core_connecting.txt](https://github.com/sparrowwallet/sparrow/files/13071468/core_connecting.txt)

**Comment by craigraw** [comment] 2023-10-24 09:20
Ok, I think I have found the issue - there is a thread race condition that can occur when Cormorant's Electrum server returns a response very quickly, and Sparrow's read thread has not yet started. This seems to occur on Windows (which might be a little slower starting the read thread) once the Cormorant server code has been Hotspot-optimized to run faster after it's first run.

I've fixed this issue in 158ecd4a, and created a pre-release binary for Windows for testing. 

@PrinceOfEgypt @jonbon7 please can you try this binary to see if the issue is resolved. You can download it from https://github.com/craigraw/beta/releases/tag/1.7.10-cormorant-race

**Comment by jonbon7** [comment] 2023-10-24 23:23
@craigraw @PrinceOfEgypt Thank you! this release fixed the issue for me as well. I am now able to consistently connect on my local machine. 

However, I have a second issue, and I'm afraid I'm not technically savvy enough to understand what's going on... I am trying to connect Sparrow to my node from a different PC (remotely) and I am unable to connect. I consistently get the message, connection timed out: connect. I modified my bitcoin conf. file as was described in the sparrow docs as follows:

rpcuser=bitcoin
rpcpassword=yourpassword

[main]
rpcbind=127.0.0.1
rpcbind=(the IP address of the machine running BTCcore)
rpcallowip=127.0.0.1
rpcallowip=(the IP address of the machine running BTCcore)/16

What does the rpcallowip= line specify? What IP address do I need to set this to?
I'm attaching the log file in case there are any clues to whether this may be a firewall issue.

[sparrow.log](https://github.com/sparrowwallet/sparrow/files/13134095/sparrow.log)

**Comment by PrinceOfEgypt** [comment] 2023-10-25 00:51
@craigraw, thank you for the build. I can also confirm that it is working.

@jonbon7, I think your problem would be with the rpcallow line - that controls which IP addresses can connect to the node. depending on how your network is set up, you can use rpcallowip=192.168.1.0/24 (assuming your ip addresses are 192.168.1.1 - 192.168.1.254). if you're using a different range you will have to specify that range using the proper CIDR notation for it.

https://www.digitalocean.com/community/tutorials/understanding-ip-addresses-subnets-and-cidr-notation-for-networking#cidr-notation

**Comment by jonbon7** [comment] 2023-10-25 05:51
@PrinceOfEgypt My ranges are in 192.168.11-192.168.1.254 for both the node host and the pc attempting to connect, however inputting rpcallowip=192.168.1.0/24 still returns the connection timed out message.

**Comment by craigraw** [comment] 2023-10-25 06:10
Great to hear the issue has been resolved.

@jonbon7 Could be a firewall issue. For testing I like using telnet to try see a connection is possible from the remote machine, for example:
```
telnet 192.168.1.1 8332
```

**Comment by jonbon7** [comment] 2023-10-25 16:19
@craigraw I should add that I am able to remote desktop into the machine running btc core from the same PC running Sparrow, so I am definitely able to connect... it just seems that through Telnet I am not able to.

**Comment by PrinceOfEgypt** [comment] 2023-10-25 17:18
@jonbon7 just making sure - you did restart bitcoin core after updating the config file with the rpcallowip, right? the changes are not automatically reloaded.

**Comment by jonbon7** [comment] 2023-10-25 20:40
@PrinceOfEgypt Yes, I did restart btc core.

**Comment by craigraw** [comment] 2023-10-26 07:14
@jonbon7 if Telnet cannot connect, that means a simple socket connection cannot be made, which indicates this is a network issue. Unfortunately I don't know where the issue lies, but something somewhere is misconfigured. My approach would be: Test using Telnet on the machine running Core and work your way outwards, try other machines, and by doing this try to narrow the source of the issue down.

**Comment by jonbon7** [comment] 2023-10-26 16:49
Thanks @craigraw this really has me lost. I am unable to telnet localhost on port 8332 (on the same machine)... it says connect failed. I've also completely turned off windows firewall for testing purposes and still unable to connect.

I can connect on port 8333 via telnet however.. both locally and remotely (although not in sparrow wallet (I receive an unexpected file error).

**Comment by craigraw** [comment] 2023-10-27 06:39
Have you added server=1 to bitcoin.conf?

**Comment by craigraw** [comment] 2023-10-28 18:03
Great :)

**Closed by craigraw** 2023-10-28 18:03 UTC

**Comment by PrinceOfEgypt** [comment] 2023-10-28 18:48
@craigraw is there an expected date to release 1.7.10? I also have a Mac machine that exhibits the same behavior, so I'm not 100% sure this was a windows only issue..

**Comment by craigraw** [comment] 2023-10-31 09:34
Will be soon.
