### ISSUE TITLE
Cannot install on Debian anymore due to Debian bug

### ISSUE THREAD

**Issue by 4NobleTruths** [sparrowwallet/sparrow#851] opened 2023-02-19 04:27 UTC
Debian 11

dpkg error on install:

> dpkg-deb: error: archive 'sparrow_1.7.2-1_amd64.deb' uses unknown compression for member 'control.tar.zst', giving up

I think caused by:
[https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=892664](url)

**Comment by craigraw** [comment] 2023-02-20 06:34
Duplicate of #829. Please see that issue for a workaround to repackage the .deb.

**Closed by craigraw** 2023-02-20 06:34 UTC
