### ISSUE TITLE
Invalid password after closing Sparrow Wallet during a coinjoin

### ISSUE THREAD

**Issue by GarzotaBTC** [sparrowwallet/sparrow#638] opened 2022-08-01 05:07 UTC
Good night, I report this error: every time I close Sparrow Wallet while doing a coinjoin, when I reopen the program and re-enter my wallet password (in addition to the BIP39 password, I have an encryption password) I get "invalid password".

I use version 1.6.5 of Sparrow Wallet on Ubuntu 22.04 LTS.

**Comment by craigraw** [comment] 2022-08-01 07:45
>  every time I close Sparrow Wallet while doing a coinjoin

You said in the TG chat that your remix had progressed beyond the "Registered input" stage - can you confirm this? In other words, you are shutting Sparrow down during the period where the remix bar has progressed to "Joined a mix" or beyond (i.e. 50% or more).

Does it also happen if you are simply in the "Registered input" stage?

**Comment by GarzotaBTC** [comment] 2022-08-01 07:50
Yes, only during the "registered input" stage.

**Comment by craigraw** [comment] 2022-08-01 08:34
Are you sure this is not simply a case of mixing up the passphrase and the password? 

Shutting Sparrow down during mixing is entirely normal and works fine for many other users on a similar platform. 

Can you can check the Sparrow log and find out if there is anything written there when you close Sparrow while mixing?

**Comment by GarzotaBTC** [comment] 2022-08-01 14:00
I checked again the app and it doesn't show that error. However, I have the log
NOTE: Info about my name is scrambled.
`2022-07-31 17:43:00,867 ERROR [HikariPool-1 connection closer] h2database [null:-1] ?????? (Wallet Principal):database close
org.h2.message.DbException: IO Exception: "Closing"
IO Exception: "Closing" [90028-206]
	at com.sparrowwallet.merged.module@1.6.5/org.h2.message.DbException.get(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.5/org.h2.mvstore.db.Store.close(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.5/org.h2.engine.Database.closeOpenFilesAndUnlock(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.5/org.h2.engine.Database.closeImpl(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.5/org.h2.engine.Database.close(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.5/org.h2.engine.Database.removeSession(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.5/org.h2.engine.SessionLocal.close(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.5/org.h2.jdbc.JdbcConnection.close(Unknown Source)
	at com.zaxxer.hikari@4.0.3/com.zaxxer.hikari.pool.PoolBase.quietlyCloseConnection(Unknown Source)
	at com.zaxxer.hikari@4.0.3/com.zaxxer.hikari.pool.HikariPool.lambda$closeConnection$1(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: IO Exception: "Closing"
IO Exception: "Closing" [90028-206]
	at com.sparrowwallet.merged.module@1.6.5/org.h2.message.DbException.getJdbcSQLException(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.5/org.h2.message.DbException.getJdbcSQLException(Unknown Source)
	... 13 common frames omitted
Caused by: org.h2.mvstore.MVStoreException: File corrupt reading chunk at position 65536 [2.0.206/6]
	at com.sparrowwallet.merged.module@1.6.5/org.h2.mvstore.DataUtils.newMVStoreException(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.5/org.h2.mvstore.Chunk.readChunkHeader(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.5/org.h2.mvstore.MVStore.moveChunk(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.5/org.h2.mvstore.MVStore.compactMoveChunks(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.5/org.h2.mvstore.MVStore.compactMoveChunks(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.5/org.h2.mvstore.MVStore.compactMoveChunks(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.5/org.h2.mvstore.MVStore.compactFile(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.5/org.h2.mvstore.MVStore.closeStore(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.5/org.h2.mvstore.MVStore.close(Unknown Source)
	... 12 common frames omitted
Caused by: org.h2.mvstore.MVStoreException: Not a map: H0E!\00×aVÞ+ÎSÏçXW±W~&LõTEØyu&(ITì n2ôÛìFé|PÅh(ÐrEcòb° ´K,V!¼\00½úãmP].-±¬»Äî´¦$AkÇDH0E!\00¡ª%?\00´vmr¿Üg%ÝIÕ·®èCõL*½¨¾ íoçÿÙ(Ö7óien1²*Ï4º	ÚùÈ!:0Ì;PüÀä¤mD·ÒnLu2`êáwâíbH0E!\00º7Gý(Ô¦²Fn¿:U{§°¬öMîLðVÃä ``'ºÊ¦È2')MßZãìÖöØ5o,!)¾!ÑÓ7ÅXC¥\¢~E:þ'kXÂ@Cü\00\00\00\00\001	 <D"2:!äÏTóÒÑæv,>jóshåØü¥P]<N <D"2:!äÏTóÒÑæv,>jóshåØü¥P]<NÏ-ÿ?È¬\000
(Lavado de BTC (Post-Lavado) (31/07/2022)\00\00\00\009P(Ã¾ÝAªq²!YÔùÞx²GöBZç¬/g\00\00\00\00ÿÿÿÿÏöõË·tf³ëDÉÃÍìõ®ú\Øtµ§úBÇ\00\00\00\00ÿÿÿÿ* [2.0.206/6]
	at com.sparrowwallet.merged.module@1.6.5/org.h2.mvstore.DataUtils.newMVStoreException(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.5/org.h2.mvstore.DataUtils.parseMap(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.5/org.h2.mvstore.Chunk.<init>(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.5/org.h2.mvstore.Chunk.fromString(Unknown Source)
	... 20 common frames omitted
2022-07-31 17:47:53,149 WARN [Thread-1548] c.s.s.n.TcpTransport [null:-1] No response from server, setting read timeout to 34 secs
2022-07-31 17:47:54,149 ERROR [JavaFX Application Thread] c.s.s.t.TransactionController [null:-1] Error fetching transaction or input references
com.sparrowwallet.sparrow.net.ElectrumServerRpcException: Failed to retrieve verbose transactions for txids: [c8bc21670caeb74f2e20ccc28325c85891dfc993c5dcc09983c8b0225aa42abe, e0ad116b5d5cdc965701d3eb98d2e562503cfefffac4b997e7d0b27f28552e2f, d71f9e2f1bbd9746e3c402aae5fd5d9013a6056a40de6f91eb1ddb675c7e4823]
	at com.sparrowwallet.sparrow@1.6.5/com.sparrowwallet.sparrow.net.BatchedElectrumServerRpc.getVerboseTransactions(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.5/com.sparrowwallet.sparrow.net.ElectrumServer.getReferencedTransactions(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.5/com.sparrowwallet.sparrow.net.ElectrumServer$TransactionReferenceService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.5/com.sparrowwallet.sparrow.net.ElectrumServer$TransactionReferenceService$1.call(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.sparrowwallet.sparrow.net.ServerException: Retries exhausted
	at com.sparrowwallet.sparrow@1.6.5/com.sparrowwallet.sparrow.net.RetryLogic.getResult(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.5/com.sparrowwallet.sparrow.net.PagedBatchRequestBuilder.execute(Unknown Source)
	... 12 common frames omitted
Caused by: java.lang.IllegalStateException: Unspecified id: '3530' in response
	at simple.json.rpc.client@1.0/com.github.arteam.simplejsonrpc.client.builder.BatchRequestBuilder.processSingleResponse(Unknown Source)
	at simple.json.rpc.client@1.0/com.github.arteam.simplejsonrpc.client.builder.BatchRequestBuilder.processBatchResponse(Unknown Source)
	at simple.json.rpc.client@1.0/com.github.arteam.simplejsonrpc.client.builder.BatchRequestBuilder.execute(Unknown Source)
	... 14 common frames omitted
2022-07-31 17:52:53,829 WARN [Thread-1577] c.s.s.n.TcpTransport [null:-1] No response from server, setting read timeout to 34 secs
2022-07-31 18:17:59,106 WARN [Thread-1682] c.s.s.n.FeeRatesSource [null:-1] Error retrieving recommended fee rates from http://mempoolhqx4isw62xs7abwphsq7ldayuidyx2v2oethdhhj6mlo2r6ad.onion/api/v1/fees/recommended (Unexpected end of file from server)
2022-07-31 18:32:01,091 WARN [Thread-1745] c.s.s.n.FeeRatesSource [null:-1] Error retrieving recommended fee rates from http://mempoolhqx4isw62xs7abwphsq7ldayuidyx2v2oethdhhj6mlo2r6ad.onion/api/v1/fees/recommended (SOCKS: TTL expired)
2022-07-31 18:35:03,166 WARN [Thread-1757] c.s.s.n.FeeRatesSource [null:-1] Error retrieving recommended fee rates from http://mempoolhqx4isw62xs7abwphsq7ldayuidyx2v2oethdhhj6mlo2r6ad.onion/api/v1/fees/recommended (SOCKS server general failure)
2022-07-31 18:38:05,388 WARN [Thread-1769] c.s.s.n.FeeRatesSource [null:-1] Error retrieving recommended fee rates from http://mempoolhqx4isw62xs7abwphsq7ldayuidyx2v2oethdhhj6mlo2r6ad.onion/api/v1/fees/recommended (SOCKS: TTL expired)
2022-07-31 18:41:07,734 WARN [Thread-1781] c.s.s.n.FeeRatesSource [null:-1] Error retrieving recommended fee rates from http://mempoolhqx4isw62xs7abwphsq7ldayuidyx2v2oethdhhj6mlo2r6ad.onion/api/v1/fees/recommended (SOCKS: TTL expired)
2022-07-31 18:44:09,887 WARN [Thread-1793] c.s.s.n.FeeRatesSource [null:-1] Error retrieving recommended fee rates from http://mempoolhqx4isw62xs7abwphsq7ldayuidyx2v2oethdhhj6mlo2r6ad.onion/api/v1/fees/recommended (SOCKS: TTL expired)
2022-07-31 18:47:11,066 WARN [Thread-1805] c.s.s.n.FeeRatesSource [null:-1] Error retrieving recommended fee rates from http://mempoolhqx4isw62xs7abwphsq7ldayuidyx2v2oethdhhj6mlo2r6ad.onion/api/v1/fees/recommended (SOCKS: TTL expired)
2022-07-31 18:50:13,203 WARN [Thread-1816] c.s.s.n.FeeRatesSource [null:-1] Error retrieving recommended fee rates from http://mempoolhqx4isw62xs7abwphsq7ldayuidyx2v2oethdhhj6mlo2r6ad.onion/api/v1/fees/recommended (SOCKS: TTL expired)
2022-07-31 18:53:15,361 WARN [Thread-1828] c.s.s.n.FeeRatesSource [null:-1] Error retrieving recommended fee rates from http://mempoolhqx4isw62xs7abwphsq7ldayuidyx2v2oethdhhj6mlo2r6ad.onion/api/v1/fees/recommended (SOCKS: TTL expired)
2022-07-31 19:25:54,786 ERROR [Thread-3] h2database [null:-1] ?????? (Wallet Principal):database CREATE CACHED TABLE "wallet_Postmix"."mixConfig"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY SEQUENCE "wallet_Postmix"."SYSTEM_SEQUENCE_FC3E5D2D_C990_4AB6_89BE_E19C92152609" NOT NULL,
    "scode" CHARACTER VARYING(255),
    "mixOnStartup" BOOLEAN,
    "indexRange" CHARACTER VARYING(10),
    "mixToWalletFile" CHARACTER VARYING(1024),
    "mixToWalletName" CHARACTER VARYING(255),
    "minMixes" INTEGER,
    "receiveIndex" INTEGER NOT NULL,
    "changeIndex" INTEGER NOT NULL,
    "wallet" BIGINT NOT NULL
)
org.h2.jdbc.JdbcSQLNonTransientConnectionException: Error de Encriptación en archivo "/home/josue/.sparrow/wallets/?????? (Wallet Principal).mv.db"
Encryption error in file "/home/josue/.sparrow/wallets/?????? (Wallet Principal).mv.db"; SQL statement:
CREATE CACHED TABLE "wallet_Postmix"."mixConfig"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY SEQUENCE "wallet_Postmix"."SYSTEM_SEQUENCE_FC3E5D2D_C990_4AB6_89BE_E19C92152609" NOT NULL,
    "scode" CHARACTER VARYING(255),
    "mixOnStartup" BOOLEAN,
    "indexRange" CHARACTER VARYING(10),
    "mixToWalletFile" CHARACTER VARYING(1024),
    "mixToWalletName" CHARACTER VARYING(255),
    "minMixes" INTEGER,
    "receiveIndex" INTEGER NOT NULL,
    "changeIndex" INTEGER NOT NULL,
    "wallet" BIGINT NOT NULL
) [90049-206]
	at com.sparrowwallet.merged.module@1.6.5/org.h2.message.DbException.getJdbcSQLException(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.5/org.h2.message.DbException.getJdbcSQLException(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.5/org.h2.message.DbException.get(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.5/org.h2.mvstore.db.Store.convertMVStoreException(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.5/org.h2.mvstore.db.Store.createTable(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.5/org.h2.schema.Schema.createTable(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.5/org.h2.command.ddl.CreateTable.update(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.5/org.h2.engine.MetaRecord.prepareAndExecute(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.5/org.h2.engine.Database.executeMeta(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.5/org.h2.engine.Database.executeMeta(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.5/org.h2.engine.Database.<init>(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.5/org.h2.engine.Engine.openSession(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.5/org.h2.engine.Engine.openSession(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.5/org.h2.engine.Engine.createSession(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.5/org.h2.engine.SessionRemote.connectEmbeddedOrServer(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.5/org.h2.jdbc.JdbcConnection.<init>(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.5/org.h2.Driver.connect(Unknown Source)
	at com.zaxxer.hikari@4.0.3/com.zaxxer.hikari.util.DriverDataSource.getConnection(Unknown Source)
	at com.zaxxer.hikari@4.0.3/com.zaxxer.hikari.pool.PoolBase.newConnection(Unknown Source)
	at com.zaxxer.hikari@4.0.3/com.zaxxer.hikari.pool.PoolBase.newPoolEntry(Unknown Source)
	at com.zaxxer.hikari@4.0.3/com.zaxxer.hikari.pool.HikariPool.createPoolEntry(Unknown Source)
	at com.zaxxer.hikari@4.0.3/com.zaxxer.hikari.pool.HikariPool.checkFailFast(Unknown Source)
	at com.zaxxer.hikari@4.0.3/com.zaxxer.hikari.pool.HikariPool.<init>(Unknown Source)
	at com.zaxxer.hikari@4.0.3/com.zaxxer.hikari.HikariDataSource.<init>(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.5/com.sparrowwallet.sparrow.io.db.DbPersistence.createDataSource(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.5/com.sparrowwallet.sparrow.io.db.DbPersistence.getDataSource(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.5/com.sparrowwallet.sparrow.io.db.DbPersistence.getFlyway(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.5/com.sparrowwallet.sparrow.io.db.DbPersistence.migrate(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.5/com.sparrowwallet.sparrow.io.db.DbPersistence.loadWallet(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.5/com.sparrowwallet.sparrow.io.db.DbPersistence.loadWallet(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.5/com.sparrowwallet.sparrow.io.Storage.loadEncryptedWallet(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.5/com.sparrowwallet.sparrow.io.Storage$LoadWalletService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.5/com.sparrowwallet.sparrow.io.Storage$LoadWalletService$1.call(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.h2.mvstore.MVStoreException: File corrupted in chunk 2987, expected page length 4..32, got 10395 [2.0.206/6]
	at com.sparrowwallet.merged.module@1.6.5/org.h2.mvstore.DataUtils.newMVStoreException(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.5/org.h2.mvstore.Page.read(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.5/org.h2.mvstore.Page.read(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.5/org.h2.mvstore.MVStore.readPage(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.5/org.h2.mvstore.MVMap.readPage(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.5/org.h2.mvstore.MVMap.readOrCreateRootPage(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.5/org.h2.mvstore.MVMap.setRootPos(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.5/org.h2.mvstore.MVStore.openMap(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.5/org.h2.mvstore.MVStore.openMap(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.5/org.h2.mvstore.tx.TransactionStore.openMap(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.5/org.h2.mvstore.tx.TransactionStore.openVersionedMap(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.5/org.h2.mvstore.tx.Transaction.openMap(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.5/org.h2.mvstore.db.MVPrimaryIndex.<init>(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.5/org.h2.mvstore.db.MVTable.<init>(Unknown Source)
	... 37 common frames omitted`

**Comment by craigraw** [comment] 2022-08-01 14:33
Thanks for the logs. I suspect looking at them that this might be caused by an unusual character in one of your labels or wallet filenames. Can you confirm if any label contained a character not normally in the English alphabet? If you can provide them I can test each one out to see if I can recreate the error.

**Comment by GarzotaBTC** [comment] 2022-08-01 14:53
Since I'm in a Spanish speaking country, I normally use á é í ó ú and the characters ( ) and /.

**Comment by craigraw** [comment] 2022-08-02 08:50
Can you try recreating this wallet from your seed words (File > New Wallet, then use the Settings > Add Account to add the Whirlpool Accounts once the wallet is created) to see if this issue is reproducible? Close the existing wallet first so you don't have both mixing at the same time.

**Comment by GarzotaBTC** [comment] 2022-08-02 15:39
> Can you try recreating this wallet from your seed words (File > New Wallet, then use the Settings > Add Account to add the Whirlpool Accounts once the wallet is created) to see if this issue is reproducible? Close the existing wallet first so you don't have both mixing at the same time.

I did it and the wallet shows as normal.

**Comment by craigraw** [comment] 2022-08-02 15:48
Thank you. I suspect this may have been due to a (now fixed) H2 database bug - the next release will contain the update. I'll close this off for now as unreproducible, but please comment if it happens again.

**Closed by craigraw** 2022-08-02 15:48 UTC
