### ISSUE TITLE
Regtest doesn't work in version 1.8.5

### ISSUE THREAD

**Issue by arik-so** [sparrowwallet/sparrow#1386] opened 2024-04-16 23:52 UTC
When running Sparrow in regtest, it quits after a couple seconds with the following error message:

> Exception in Application start method
Exception in Application stop method
2024-04-16 16:50:52,459 ERROR Exception in thread "main"
java.lang.RuntimeException: Exception in Application start method
	at javafx.graphics@18/com.sun.javafx.application.LauncherImpl.launchApplication1(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: No enum constant com.samourai.wallet.constants.SamouraiNetwork.REGTEST
	at java.base/java.lang.Enum.valueOf(Unknown Source)
	at com.samourai.extlibj@1.0.6/com.samourai.wallet.constants.SamouraiNetwork.valueOf(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.5/com.sparrowwallet.sparrow.whirlpool.WhirlpoolServices.getSamouraiNetwork(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.5/com.sparrowwallet.sparrow.whirlpool.WhirlpoolServices.computeExtLibJConfig(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.5/com.sparrowwallet.sparrow.whirlpool.WhirlpoolServices.<init>(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.5/com.sparrowwallet.sparrow.AppServices.<init>(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.5/com.sparrowwallet.sparrow.AppServices.initialize(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.5/com.sparrowwallet.sparrow.SparrowDesktop.start(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics@18/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
Failed to launch JVM

Is there a way to disable the Samourai lookup so the wallet becomes usable again?

**Comment by craigraw** [comment] 2024-04-17 06:08
Duplicate of #1385. The two workarounds are noted in that issue.

**Closed by craigraw** 2024-04-17 06:08 UTC
