### ISSUE TITLE
Win 11 Monitor Sleep

### ISSUE THREAD

**Issue by OprahTheHutt** [sparrowwallet/sparrow#493] opened 2022-03-29 21:51 UTC
When running Sparrow Wallet on Win11 my monitor will not go to sleep.  "Prevent Computer Sleep" is unchecked.  Sparrow 1.6.2 and previous 2 versions.

**Comment by Transisto** [comment] 2022-03-30 21:30
Are you sure it is caused by sparrow? It's been so unreliable here that I conditioned myself to never rely on it and use WIN+L.

**Comment by OprahTheHutt** [comment] 2022-03-31 00:30
If Sparrow is running, no sleep.  Shut Sparrow down then monitor will sleep.  When mixing this is problematic.

**Comment by craigraw** [comment] 2022-03-31 06:01
I can't reproduce this. Can you test if
1. It happens with all tabs closed.
2. It happens on v1.5.6?

**Comment by OprahTheHutt** [comment] 2022-03-31 16:12
Close both wallet tabs goes to sleep.  Close my single sig wallet, leave whirlpool wallet open, goes to sleep.  Close Whirlpool wallet tab leave single sig wallet open, Does not go to sleep.

Running 1.6.3 now.  If you really want me to go back and test 1.5.6 I will but hopefully this gets to where we are going.  I am fine only leaving the whirlpool wallet open.

**Comment by craigraw** [comment] 2022-04-01 05:44
Is the single sig wallet using a connected USB hardware device? If so can you try unplugging it and keeping the singlesig wallet open to see if the issue still occurs?

**Comment by OprahTheHutt** [comment] 2022-04-01 14:53
Not Connected, just tab open.  Close tab and it goes to sleep after 3 mins like its set to do.

**Comment by OprahTheHutt** [comment] 2022-05-05 16:39
Every other wallet I have added into Sparrow works fine.  Only the wallet I created in Sparrow with a Nano S keeps the monitor awake if the wallet is open.

**Comment by craigraw** [comment] 2022-05-12 12:52
I can only imagine this is due to a scheduled service in Sparrow that checks to see what devices are plugged in (when a wallet with USB keystores is opened). Why this is causing your monitor to stay awake is strange though, as there are no other reports of this behaviour.

In e0b0051 I've made the period of that scheduled service configurable. It is by default set to 30 seconds, but you can increase it to a value higher than your monitor sleep delay so that it turns itself off.

**Comment by craigraw** [comment] 2022-05-26 12:22
> This is not (yet, anyway) configurable in the UI - to change it you will need to edit the Sparrow config file and change the value for the enumerateHwPeriod entry.

@OprahTheHutt can you try the above in Sparrow v1.6.5 and report back? You may need to run Sparrow first so the field is created in the `config` file (see FAQ to find it). Set it to a high value like `3600`.

**Comment by OprahTheHutt** [comment] 2022-05-27 03:57
Success!

**Comment by craigraw** [comment] 2022-05-27 06:22
Great, closing this off. If others experience this, please comment below.

**Closed by craigraw** 2022-05-27 06:22 UTC
