### ISSUE TITLE
Error opening wallet - Failed to open database file

### ISSUE THREAD

**Issue by mattmcgiv** [sparrowwallet/sparrow#482] opened 2022-03-23 13:57 UTC
Hi! First I'd like to say thanks for all of the great work on Sparrow wallet.

Unfortunately I'm having an issue where my wallet file will not open.
![Screenshot from 2022-03-23 07-38-04](https://user-images.githubusercontent.com/2454581/159714540-328cda03-7b4b-4e82-a276-87b20ecb08a3.png)

The full text of the screenshot: 
Error opening wallet
Failed to open database file.
Failed to initialize pool: File corrupted while reading record: null. Possible solution: use the recovery tool [90030-206]

I'm running the latest release (1.6.2) at this time, and this error started on v 1.6.1 for what it's worth.

I've searched the issues here on GitHub and looked at the documentation on sparrowwallet.com but can't seem to find a fix. If there is a recovery tool available as mentioned in the error message, I'm not able to find documentation for it.

I do have a workaround: I'm able to successfully load a backup from `~/.sparrow/wallets/backup`, however I wanted to post this here for anyone else who might run into this issue.

Thanks again.

sparrow.log says:
`2022-03-23 07:36:56,702 ERROR [Thread-7] h2database [null:-1] {{ redacted wallet name}}:database flush
org.h2.message.DbException: General error: "org.h2.mvstore.MVStoreException: File is corrupted - unable to recover a valid set of chunks [2.0.206/6]" [50000-206]
	at com.sparrowwallet.merged.module@1.6.2/org.h2.message.DbException.get(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.h2.message.DbException.convert(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.h2.mvstore.db.Store.lambda$new$0(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.h2.mvstore.MVStore.handleException(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.h2.mvstore.MVStore.panic(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.h2.mvstore.MVStore.<init>(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.h2.mvstore.MVStore$Builder.open(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.h2.mvstore.db.Store.<init>(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.h2.engine.Database.<init>(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.h2.engine.Engine.openSession(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.h2.engine.Engine.openSession(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.h2.engine.Engine.createSession(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.h2.engine.SessionRemote.connectEmbeddedOrServer(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.h2.jdbc.JdbcConnection.<init>(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.h2.Driver.connect(Unknown Source)
	at com.zaxxer.hikari@4.0.3/com.zaxxer.hikari.util.DriverDataSource.getConnection(Unknown Source)
	at com.zaxxer.hikari@4.0.3/com.zaxxer.hikari.pool.PoolBase.newConnection(Unknown Source)
	at com.zaxxer.hikari@4.0.3/com.zaxxer.hikari.pool.PoolBase.newPoolEntry(Unknown Source)
	at com.zaxxer.hikari@4.0.3/com.zaxxer.hikari.pool.HikariPool.createPoolEntry(Unknown Source)
	at com.zaxxer.hikari@4.0.3/com.zaxxer.hikari.pool.HikariPool.checkFailFast(Unknown Source)
	at com.zaxxer.hikari@4.0.3/com.zaxxer.hikari.pool.HikariPool.<init>(Unknown Source)
	at com.zaxxer.hikari@4.0.3/com.zaxxer.hikari.HikariDataSource.<init>(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.2/com.sparrowwallet.sparrow.io.db.DbPersistence.createDataSource(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.2/com.sparrowwallet.sparrow.io.db.DbPersistence.getDataSource(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.2/com.sparrowwallet.sparrow.io.db.DbPersistence.getFlyway(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.2/com.sparrowwallet.sparrow.io.db.DbPersistence.migrate(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.2/com.sparrowwallet.sparrow.io.db.DbPersistence.loadWallet(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.2/com.sparrowwallet.sparrow.io.db.DbPersistence.loadWallet(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.2/com.sparrowwallet.sparrow.io.Storage.loadUnencryptedWallet(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.2/com.sparrowwallet.sparrow.io.Storage$LoadWalletService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.2/com.sparrowwallet.sparrow.io.Storage$LoadWalletService$1.call(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "org.h2.mvstore.MVStoreException: File is corrupted - unable to recover a valid set of chunks [2.0.206/6]" [50000-206]
	at com.sparrowwallet.merged.module@1.6.2/org.h2.message.DbException.getJdbcSQLException(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.h2.message.DbException.getJdbcSQLException(Unknown Source)
	... 39 common frames omitted
Caused by: org.h2.mvstore.MVStoreException: File is corrupted - unable to recover a valid set of chunks [2.0.206/6]
	at com.sparrowwallet.merged.module@1.6.2/org.h2.mvstore.DataUtils.newMVStoreException(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.h2.mvstore.MVStore.readStoreHeader(Unknown Source)
	... 34 common frames omitted
2022-03-23 07:36:56,705 ERROR [Thread-7] h2database [null:-1] {{ redacted wallet name }}:database opening /home/mattmcgivney/.sparrow/wallets/{{ redacted wallet name}}
org.h2.message.DbException: File corrupted while reading record: null. Possible solution: use the recovery tool [90030-206]
	at com.sparrowwallet.merged.module@1.6.2/org.h2.message.DbException.get(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.h2.mvstore.db.Store.convertMVStoreException(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.h2.mvstore.db.Store.<init>(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.h2.engine.Database.<init>(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.h2.engine.Engine.openSession(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.h2.engine.Engine.openSession(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.h2.engine.Engine.createSession(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.h2.engine.SessionRemote.connectEmbeddedOrServer(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.h2.jdbc.JdbcConnection.<init>(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.h2.Driver.connect(Unknown Source)
	at com.zaxxer.hikari@4.0.3/com.zaxxer.hikari.util.DriverDataSource.getConnection(Unknown Source)
	at com.zaxxer.hikari@4.0.3/com.zaxxer.hikari.pool.PoolBase.newConnection(Unknown Source)
	at com.zaxxer.hikari@4.0.3/com.zaxxer.hikari.pool.PoolBase.newPoolEntry(Unknown Source)
	at com.zaxxer.hikari@4.0.3/com.zaxxer.hikari.pool.HikariPool.createPoolEntry(Unknown Source)
	at com.zaxxer.hikari@4.0.3/com.zaxxer.hikari.pool.HikariPool.checkFailFast(Unknown Source)
	at com.zaxxer.hikari@4.0.3/com.zaxxer.hikari.pool.HikariPool.<init>(Unknown Source)
	at com.zaxxer.hikari@4.0.3/com.zaxxer.hikari.HikariDataSource.<init>(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.2/com.sparrowwallet.sparrow.io.db.DbPersistence.createDataSource(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.2/com.sparrowwallet.sparrow.io.db.DbPersistence.getDataSource(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.2/com.sparrowwallet.sparrow.io.db.DbPersistence.getFlyway(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.2/com.sparrowwallet.sparrow.io.db.DbPersistence.migrate(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.2/com.sparrowwallet.sparrow.io.db.DbPersistence.loadWallet(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.2/com.sparrowwallet.sparrow.io.db.DbPersistence.loadWallet(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.2/com.sparrowwallet.sparrow.io.Storage.loadUnencryptedWallet(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.2/com.sparrowwallet.sparrow.io.Storage$LoadWalletService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.2/com.sparrowwallet.sparrow.io.Storage$LoadWalletService$1.call(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)`

**Comment by craigraw** [comment] 2022-03-26 09:32
Unfortunately, the wallet database file was corrupted somehow. This is AFAIK a rare issue, and there's no known bug causing it in Sparrow - it might be due to external factors. I'm closing this off as a result, but thanks for adding it - it may be useful in future.

**Closed by craigraw** 2022-03-26 09:32 UTC

**Comment by tanuck** [comment] 2022-04-14 16:19
@craigraw I'm getting this regularly with a watch-only wallet on Sparrow 1.6.3 on MacOS. Will try to get a consistent reproduction.
