### ISSUE TITLE
Signature failed Ledger

### ISSUE THREAD

**Issue by DeGxx** [sparrowwallet/sparrow#558] opened 2022-05-21 07:32 UTC
Hello, i can't sign a transaction with my ledger, here is the script, thank you for help.

2022-05-21 09:22:13,563 ERROR [JavaFX Application Thread] c.s.s.c.DevicePane [null:-1] Signing Error: ('0x6a80', 'Error in <BitcoinInsType.SIGN_PSBT: 4> command', '')
com.sparrowwallet.sparrow.io.SignTransactionException: ('0x6a80', 'Error in <BitcoinInsType.SIGN_PSBT: 4> command', '')
	at com.sparrowwallet.sparrow@1.6.4/com.sparrowwallet.sparrow.io.Hwi.signPSBT(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.4/com.sparrowwallet.sparrow.io.Hwi$SignPSBTService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.4/com.sparrowwallet.sparrow.io.Hwi$SignPSBTService$1.call(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by craigraw** [comment] 2022-05-21 15:27
Thanks, duplicate of #553.

**Closed by craigraw** 2022-05-21 15:27 UTC
