### ISSUE TITLE
tor broadcast indication

### ISSUE THREAD

**Issue by 6102bitcoin** [sparrowwallet/sparrow#130] opened 2021-05-20 22:13 UTC
Clearly indicate to users that transactions will be broadcast to one of 3 .onion addresses over tor even if connected to your own electrum server over tor.

Outstanding Action: Add note on send screen / broadcast button.
Proposed Priority: Medium (Could cause confusion or frustration to users to find that this happens in the background)

**Comment by craigraw** [comment] 2021-05-21 07:21
I'd like to add a Tor icon to the status bar - it looks like FontAwesome are going to support a Tor icon soon, which would be the correct way to implement that.

That said the remote broadcast itself is a relatively technical feature - consideration must be given to potential confusion caused by trying to explain this feature on the broadcast interface. I'm not sure I can see any good solutions right now.

**Comment by 6102bitcoin** [comment] 2021-05-21 14:02
Broadcast Toggle: `self` | `3rd Party` ?

**Comment by nyxnor** [comment] 2021-09-13 00:35
just pinging cause I find this important.

**Comment by craigraw** [comment] 2021-09-21 10:05
Added in e12f7a6. The presence of a Tor proxy is indicated in the status bar. For example, in the case of an externally configured Tor proxy:

<img width="228" alt="Screenshot 2021-09-21 at 11 53 10" src="https://user-images.githubusercontent.com/862166/134151034-069da5f5-aacf-4c13-a1b6-c2ceb5047246.png">

If an external Tor proxy is configured, and a connection to it cannot be established, the icon indicates an error:

<img width="258" alt="Screenshot 2021-09-21 at 11 57 34" src="https://user-images.githubusercontent.com/862166/134151549-84613028-598d-46ff-9f70-3b7313477cbf.png">

Note that it is now possible to configure an external Tor proxy even if the Electrum server specified is a local network IP. Sparrow will not use the Tor proxy when connecting to the Electrum server in this case, but will use it for all remote services.

Re broadcasting, I can't think of a good reason not to broadcast using a remote service if Tor is enabled, so I'd prefer to avoid adding a toggle to give optionality on this. I'm going to close this off, but please comment if you disagree.

**Closed by craigraw** 2021-09-21 10:05 UTC
Labels: enhancement, low

**Comment by nyxnor** [comment] 2021-09-21 10:14
> Sparrow will not use the Tor proxy when connecting to the Electrum server in this case, but will use it for all remote services.

So user need to configure the proxy two times? One for Electrum Server and one for broadcasting? How to keep it understandable? If using proxy with the wallet, broadcasting it should be done over that proxy, which is Tor.

**Comment by craigraw** [comment] 2021-09-21 10:26
> So user need to configure the proxy two times?

No - sorry if this was not clear. There is only one Tor proxy configuration, and Sparrow will use that for everything if configured (except a local network connection, which would fail anyway if tried).
