### ISSUE TITLE
Coinjoin : input rejected 

### ISSUE THREAD

**Issue by imacfan** [sparrowwallet/sparrow#234] opened 2021-10-03 15:45 UTC
I was experimenting with Coinjoin feature.

Few of the UTXO's were mixed and moved to post mix. But rest are stuck in pre-mix and getting "Input rejected" error.

<img width="307" alt="image" src="https://user-images.githubusercontent.com/54225190/135761489-4f9e7baa-7c49-4d5e-a34c-3156610f872e.png">

How to resolve this?

**Comment by calkob** [comment] 2021-10-03 19:34
I have had a few inputs rejected also.  All have now had at least 1 mix but the mixing seems to have stalled, been running for days now.   Log below for info. 

Thanks

[sparrow log.txt](https://github.com/sparrowwallet/sparrow/files/7274426/sparrow.log.txt)

**Comment by craigraw** [comment] 2021-10-04 06:00
This is generally caused by connection problems. For example, if the computer Sparrow is running on is configured to sleep automatically, then the Whirlpool client will "disappear" to the server after it has registered an input for mixing. If the client does this several times, it may get temporarily banned. Make sure the computer is configured to not sleep, or use the Amphetamine app (for example).

It's clear from the log file in the second comment that there were connection problems involved (e.g. see `No such host is known` - this indicates DNS was down at that moment, so probably no connection to the internet at that moment.

Banned UTXOs (the tooltip will improve in the next release) are generally unbanned after about 12 hours. You can also email help@samourai.support.

**Comment by craigraw** [comment] 2021-10-05 07:14
Closing this off.

**Closed by craigraw** 2021-10-05 07:14 UTC
