### ISSUE TITLE
Like-type change outputs

### ISSUE THREAD

**Issue by AndySchroder** [sparrowwallet/sparrow#1392] opened 2024-04-20 00:17 UTC
Samourai Wallet has a feature called Like-type change outputs. See:

- https://samourai.kayako.com/article/53-like-type-change-outputs
- https://docs.samourai.io/wallet/basic-concepts#like-type-change

Basically, the purpose is to avoid the following problem:

User sends a single UTXO from a native segwit address to a legacy address and then a native segwit change address. Basic review of the transaction will imply that the legacy address is the receiver and the native segwit address is the change address since the sending UTXO was native segwit.

With Like-type change outputs both outputs of a transaction are of the same script type. So, in the example above, both outputs would be a legacy address. This results in a little "back tracking" of the script type potentially, but offers more privacy. It also makes the wallet it bit more challenging to design, especially if the seed was already used for another wallet that used an older script type.

Therefor I'm not sure if you want to implement this, but I at least wanted to bring it up for discussion. I think native segwit and taproot addresses appear as the same format, so maybe this issue will start to go away in the future and it is not worth wasting the time on it?

**Comment by craigraw** [comment] 2024-04-22 09:56
Duplicate of #466 (as it is effectively required to support this). Fwiw I have moved even further away in the intervening period.

**Closed by craigraw** 2024-04-22 09:56 UTC

**Comment by craigraw** [comment] 2024-04-23 06:57
> You're just saying you likely may never fix https://github.com/sparrowwallet/sparrow/issues/466

You are suggesting this is something to be "fixed" - rather it is a deliberate design decision made on the basis of understanding the tradeoffs of both options. In fact the codebase has evolved since to make this easier to do, but the same problems with UX apply, while the actual need has reduced as legacy script type usage has dropped.

For example, when a user links a BIP47 wallet, Sparrow must create and manage 3 wallets for P2PKH, P2SH-P2WSH and P2WSH script types. Luckily, since BIP47 wallets are not top level wallets, much of this complexity can be placed into areas of the interface that are less frequently visited, but if multiple script types were a top level feature for all wallets this would be impossible.
