### ISSUE TITLE
Please Add AppImage version release of Sparrow Wallet.

### ISSUE THREAD

**Issue by decipher-random** [sparrowwallet/sparrow#794] opened 2022-12-29 22:08 UTC
### Please Add AppImage version of Sparrow Wallet.

This would be great if a AppImage binary of Sparrow was available for *TailsOS* users, Live users, or users that would like to have and executable for Sparrow saved on another drive etc. Currently in Tails the sparrow "debian software package" `.deb` binary can't be persistently installed on Tails persistence storage. You have to run `sudo dpkg -i sparrow_version_amd64.deb` evertime. However you can persist the Configuration files that you choose so you don't have to input *127.0.0.1:9050* or remote nodes each time by running this command then rebooting:
```
echo -e '/home/amnesia/.sparrow source=sparrow' | sudo tee -a /live/persistence/TailsData_unlocked/persistence.conf > /dev/null
```
**Releasing a AppImage similair to *Feather Monero Wallet* that saves the `wallet_data` ie the config/settings/wallets etc.  next to the AppImage binary in the directory wherever it is saved instead of the `/home` dir would be the way to go.** 
![Example](https://user-images.githubusercontent.com/120349503/210015182-a3221995-bce2-4439-8bec-cc0638033275.png)
Also noted Tails switched to Wayland to so it would need support for that. Which I believe it already does cause Sparrow has no issues launching/opening on Tails Version 5.8. Just no way to persist the install of it currently.

**Comment by craigraw** [comment] 2023-01-02 07:35
Duplicate of #1. While I appreciate this solution, I would rather put work into #372. 

Note you can specify the Sparrow home folder with the `-d` flag.

**Closed by craigraw** 2023-01-02 07:35 UTC

**Comment by eugenesan** [comment] 2024-07-20 04:26
For those interested in building AppImage, I've created a script for that.

In addition to creating AppImage it also can create and install Binary and Java packages.

Please find the script attached:
[sparrow.sh.txt](https://github.com/user-attachments/files/16318829/sparrow.sh.txt)

@craigraw 
Please consider adding AppImage build based on the script or the script itself somewhere in the tree.
