### ISSUE TITLE
local block explorer not accepted

### ISSUE THREAD

**Issue by pjw65** [sparrowwallet/sparrow#891] opened 2023-03-10 06:58 UTC
http://umbrel.local:3006/de/tx/{0}
will return an error "Invalid URL".

The port number seems to be the problem.

Try to change 
- File / Preferences / Block explorer 

using newest sparrow 1.7.3 on Ubuntu

**Comment by craigraw** [comment] 2023-03-10 08:54
Duplicate of #872. You can drop the path as a workaround for now, but then you get the English mempool.space.

**Closed by craigraw** 2023-03-10 08:54 UTC
