### ISSUE TITLE
UI Bug: Drop down menu closes instantly

### ISSUE THREAD

**Issue by f321x** [sparrowwallet/sparrow#1023] opened 2023-07-15 09:41 UTC
On qubes is in a fedora qube the drop down menus close right after clicking on them. 
Example: Click on "File" to create new wallet. After click on file you can see the menu but when lifting the mouse button it vanishes again. So it is not possible to use sparrow. USB mouse and touchpad, restart doesn't help. Version 1.7.7

**Comment by craigraw** [comment] 2023-07-16 06:25
Duplicate of #170.

**Closed by craigraw** 2023-07-16 06:25 UTC
Labels: duplicate
