### ISSUE TITLE
Minor Bug Fix - display unit : BTC > sats > BTC

### ISSUE THREAD

**Issue by TinF0ilHat1** [sparrowwallet/sparrow#1228] opened 2024-01-13 14:50 UTC
_Amount_ field on tab _Send_: 
Starting with _BTC_ as denomination, input whatever number (0.001) and then change to _sats_ (100.000) works flawlessly. Trying to get back to _BTC_ i get 1 and not 0.001 though.

**Comment by craigraw** [comment] 2024-01-15 05:40
> Trying to get back to BTC i get 1 and not 0.001 though.

I can't reproduce this - I get 0.001. Can you verify? What OS is this?

**Comment by craigraw** [comment] 2024-01-16 10:20
Ah - needed to have comma decimal separators configured.

Fixed in ad1ecfb8.

**Closed by craigraw** 2024-01-16 10:20 UTC
