### ISSUE TITLE
Feature Request: Timed tx Broadcast

### ISSUE THREAD

**Issue by apemithrandir** [sparrowwallet/sparrow#1426] opened 2024-05-27 23:10 UTC
# The Problem - Timing attacks

When a user is moving bitcoin from one wallet to another in a privacy preserving way (one utxo at a time), they are still exposed to timing attacks. For instance, they send all the tx at the same time into the mempool in the same way (via the same node or tx publisher). This can allow chain surveillance to associate a heuristic on these transactions.

## Potential Solution

One potential mitigation for this would be the option to queue up transactions and either have a random or a user set publishing schedule into the mempool. You may have 10 UTXOs to move and you decide you will publish them into the mempool at a random interval of between 4 and 8 hours each time.

## Issues with this Approach

Fee rate spikes would obviously cause issues with this not only for the delayed publication of the tx not getting confirmed but also if the user uses the same fee rate for all the tx and then uses delayed publication that would allow another method for heuristic matching.

### Mitigations

To mitigate this you may have to sign multiple tx with different fee rates and publish the one with the fee rate that best matches the mempool fee rate at the time of publish or withholds the publish of the tx if the fee rate is not sufficiently high.

## Alternative Solutions

I have not given the above excessive consideration so if there are better ways to automatically mitigate timing attacks on batch spending, I'm open to suggestions.

**Comment by craigraw** [comment] 2024-05-28 06:05
Duplicate of #1421.

**Closed by craigraw** 2024-05-28 06:05 UTC
