### ISSUE TITLE
File->Quit missing on some computers

### ISSUE THREAD

**Issue by AndySchroder** [sparrowwallet/sparrow#1565] opened 2024-12-23 04:05 UTC
I just upgraded to version 2.0.0. On one (but not all) of my computers there is no longer a "File->Quit" menu item to close the entire window. I only have "File->Close Tab", which is not what I want to do.

However, I noticed if I click on the File menu, then use the Up/Down arrows, the Quit menu is actually there, just chopped off to a very small part that does not include any text:

![image](https://github.com/user-attachments/assets/d3647ab4-a904-4c40-9200-a6b96722c414)

I've only tested on two computers so far, but this is very weird.

**Comment by craigraw** [comment] 2024-12-23 05:29
Duplicate of #1531.

**Closed by craigraw** 2024-12-23 05:29 UTC
