### ISSUE TITLE
Issue with using Jade in multi sig with Sparrow Wallet

### ISSUE THREAD

**Issue by wealthcollector** [sparrowwallet/sparrow#1203] opened 2023-12-19 00:47 UTC
Hi guys,

Just got a new Jade wallet and I'm using it in multi sig with sparrow wallet. I currently have 5 UTXOS in this wallet. When I tried to sign with my jade for the 2 smallest UTXOS in the wallet, everything works fine. However, when I try to sign a transaction on the 3 bigger UTXOS, it says processing for a long time,  then on sparrow it keeps showing "read nothing, apparent EOF", while other UTXOS say "failed to extract input_tx" or  "messaging/communication error".  The other hardware wallets in the multi sig are working fine and signing but can't get jade to work on these specific UTXOS. I've input the passcode and its "active" but just can't get it to sign a transaction. Hopefully someone can help me out. Not sure if this is a sparrow issue, jade issue, or specific jade issue. I think it's a specific jade issue cause I have another jade and it works just fine with a different multi sig set up.

Thanks.

**Comment by craigraw** [comment] 2023-12-19 07:22
Probably a duplicate of #1060 - upgrading the Jade driver solves this.

**Closed by craigraw** 2023-12-19 07:22 UTC

**Comment by wealthcollector** [comment] 2023-12-19 10:09
That worked. Thank you.
