### ISSUE TITLE
Null Pointer Exception on send tab

### ISSUE THREAD

**Issue by jlopp** [sparrowwallet/sparrow#1171] opened 2023-11-22 20:58 UTC
Running on Ubuntu 22.04 in testnet mode.

I created a 2 of 3 multisig wallet with 2 connected hardware devices and 1 xpub.

Deposited one transaction from another testnet wallet and then clicked on the 'send' tab to test sending.

However, the send tab doesn't render - it stays on the current tab. Looking at the logs I see this exception thrown:

```
~/Downloads/apps/Sparrow/bin/Sparrow --network testnet

(Sparrow:187033): Gdk-WARNING **: 15:55:07.846: XSetErrorHandler() called with a GDK error trap pushed. Don't do that.
2023-11-22 15:55:12,966 ERROR Exception in thread "JavaFX Application Thread"
java.lang.NullPointerException: null
	at java.base/java.util.Objects.requireNonNull(Unknown Source)
	at java.base/java.util.ImmutableCollections$List12.indexOf(Unknown Source)
	at java.base/java.util.ImmutableCollections$AbstractImmutableList.contains(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.0/com.sparrowwallet.sparrow.wallet.SendController.getPreferredOptimizationStrategy(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.0/com.sparrowwallet.sparrow.wallet.SendController.setPreferredOptimizationStrategy(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.0/com.sparrowwallet.sparrow.wallet.SendController.initializeView(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.0/com.sparrowwallet.sparrow.wallet.WalletFormController.setWalletForm(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.0/com.sparrowwallet.sparrow.wallet.WalletController.lambda$initializeView$0(Unknown Source)
	at javafx.base@18/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at javafx.base@18/javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(Unknown Source)
	at javafx.base@18/javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(Unknown Source)
	at javafx.base@18/javafx.beans.property.ObjectPropertyBase.markInvalid(Unknown Source)
	at javafx.base@18/javafx.beans.property.ObjectPropertyBase.set(Unknown Source)
	at javafx.controls@18/javafx.scene.control.ToggleGroup$3.set(Unknown Source)
	at javafx.controls@18/javafx.scene.control.ToggleGroup$3.set(Unknown Source)
	at javafx.controls@18/javafx.scene.control.ToggleGroup.selectToggle(Unknown Source)
	at javafx.controls@18/javafx.scene.control.ToggleButton$1.invalidated(Unknown Source)
	at javafx.base@18/javafx.beans.property.BooleanPropertyBase.markInvalid(Unknown Source)
	at javafx.base@18/javafx.beans.property.BooleanPropertyBase.set(Unknown Source)
	at javafx.controls@18/javafx.scene.control.ToggleButton.setSelected(Unknown Source)
	at javafx.controls@18/javafx.scene.control.ToggleButton.fire(Unknown Source)
	at javafx.controls@18/com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(Unknown Source)
	at javafx.controls@18/com.sun.javafx.scene.control.inputmap.InputMap.handle(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base@18/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.graphics@18/javafx.scene.Scene$MouseHandler.process(Unknown Source)
	at javafx.graphics@18/javafx.scene.Scene.processMouseEvent(Unknown Source)
	at javafx.graphics@18/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
	at javafx.graphics@18/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
	at javafx.graphics@18/com.sun.glass.ui.View.notifyMouse(Unknown Source)
	at javafx.graphics@18/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics@18/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by craigraw** [comment] 2023-11-23 05:08
Thanks for the report. 

Duplicate of #1163, and fixed in the v1.8.1 released yesterday :)

**Closed** 2023-11-23 05:08 UTC

**Comment by jlopp** [comment] 2023-11-23 15:54
I think I figured out why I was still experiencing the problem after updating to v1.8.1

Due to the permissions of the files in the release, one can run into errors that prevent all the files from being updated.

I tested this by running a v1.8.1 that I extracted to a fresh directory versus trying to extract into my old release directory.

![Screenshot from 2023-11-23 10-48-58](https://github.com/sparrowwallet/sparrow/assets/288011/48739a3c-60fc-4031-b49e-eef99cc85e1c)

**Comment by jlopp** [comment] 2023-11-24 00:27
Correct

**Comment by craigraw** [comment] 2024-04-18 09:00
Fixed in https://github.com/sparrowwallet/sparrow/commit/2354b061a9b05028a629dc8a61c4e69670f2da79 and followups.
