### ISSUE TITLE
[BUG] RPM packaging issue

### ISSUE THREAD

**Issue by suvayu** [sparrowwallet/sparrow#352] opened 2021-12-09 21:58 UTC
I think there's a packaging issue with how the desktop files are installed.  If you upgrade, the menu shortcuts get removed.  To fix/avoid this, you have to uninstall the old, and then install the new version.

```
# dnf install sparrow-1.5.3-1.x86_64.rpm  # sparrow-1.5.2-1.x86_64 is already installed
```
The above leads to a broken menu.

To avoid the problem, you need to do:
```
# dnf remove sparrow
# dnf install sparrow-1.5.3-1.x86_64.rpm
```

I'm on 5.15.6-100.fc34.x86_64

**Comment by craigraw** [comment] 2021-12-10 06:26
Sparrow v1.5.3 did make a change to the installation menu, specifying the menu folder to be 'Sparrow' rather than the 'Unknown' default. Possibly this is contributing. 

In what way is the menu broken?

**Comment by suvayu** [comment] 2021-12-11 03:07
Hi Craig,

Sparrow simply disappears from the list of applications.  When I search for "sparrow", there's no result.  I think I noticed this in the previous release also.

**Comment by suvayu** [comment] 2021-12-11 03:14
When "upgrading", I see these messages from dnf:

```
Remove sparrow-Sparrow.desktop default handler for application/psbt mime type from /usr/local/share/applications/defaults.list file
Remove sparrow-Sparrow.desktop default handler for application/bitcoin-transaction mime type from /usr/local/share/applications/defaults.list file
Remove sparrow-Sparrow.desktop default handler for x-scheme-handler/bitcoin mime type from /usr/local/share/applications/defaults.list file
Remove sparrow-Sparrow.desktop default handler for x-scheme-handler/aopp mime type from /usr/local/share/applications/defaults.list file
/usr/local/share/applications/defaults.list file updated
```

**Comment by craigraw** [comment] 2024-09-04 13:33
This is actually a duplicate of #722, closing in favour of that (longer) issue.

**Closed by craigraw** 2024-09-04 13:33 UTC
Labels: bug
