### ISSUE TITLE
No way to save a label for a receive address

### ISSUE THREAD

**Issue by statusquont** [sparrowwallet/sparrow#152] opened 2021-06-30 14:28 UTC
I click on the Receive tab, I type in a label for the address. 
I click on the Addresses tab, I see the label for that address is there, as expected.
I close down Sparrow. 
I re-open the app, the label is no longer there.

The use case was a sender asked me for an address, so I opened Sparrow to get the next unused address and then I emailed it to them. I wanted to add the label now, so I don't forget it's a used/doxed address, even though the sender has not yet broadcast the TX. There doesn't seem to be a way to save the label for an address if it's not yet tied to a UTXO. Unless I'm missing something?

Running v1.4.2

**Comment by kolya182** [comment] 2021-06-30 20:48
I have my labels disappeared after I changed `gap limit` and wanted to add them back again, but no option to do it.
@craigraw can you add `Lebel` field ?
<img width="1025" alt="Screen Shot 2021-06-30 at 1 44 20 PM" src="https://user-images.githubusercontent.com/3277207/124028938-6d37b580-d9a9-11eb-85be-310113d3a02d.png">

Running v1.4.2

**Comment by craigraw** [comment] 2021-07-01 07:45
> I re-open the app, the label is no longer there.

Thanks for the bug report, fixed in 143472b.

**Comment by craigraw** [comment] 2021-07-01 07:51
> I have my labels disappeared after I changed gap limit

Changing the gap limit should not lose labels. This may be related to the bug found by the OP, which affects the saving of labels in the first place (rather than changing the gap limit). I can't reproduce losing labels on a change of the gap limit - if you have a label that is saved across restarts but is lost with a gap limit change, please open a separate issue. I'll close this issue off here to keep things apart.

Also, you've highlighted the sign message functionality in the images - I'm not sure how that's connected to labels?

**Closed by craigraw** 2021-07-01 07:51 UTC
