### ISSUE TITLE
Starting in regtest mode fails - regression - No enum constant com.samourai.wallet.constants.SamouraiNetwork.REGTEST

### ISSUE THREAD

**Issue by abradshaw** [sparrowwallet/sparrow#1398] opened 2024-04-23 09:40 UTC
Thanks so much for having a regtest mode. I run Sparrow on two of my machines (both Linux)

On one machine with 1.8.5, when I try to run in regtest mode I get this error - on the machine with 1.8.4 I dont get this error

```
/opt/sparrow/bin/Sparrow --network regtest
Exception in Application start method
Exception in Application stop method
2024-04-23 11:08:31,627 ERROR Exception in thread "main"
java.lang.RuntimeException: Exception in Application start method
	at javafx.graphics@18/com.sun.javafx.application.LauncherImpl.launchApplication1(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: No enum constant com.samourai.wallet.constants.SamouraiNetwork.REGTEST
	at java.base/java.lang.Enum.valueOf(Unknown Source)
	at com.samourai.extlibj@1.0.6/com.samourai.wallet.constants.SamouraiNetwork.valueOf(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.5/com.sparrowwallet.sparrow.whirlpool.WhirlpoolServices.getSamouraiNetwork(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.5/com.sparrowwallet.sparrow.whirlpool.WhirlpoolServices.computeExtLibJConfig(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.5/com.sparrowwallet.sparrow.whirlpool.WhirlpoolServices.<init>(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.5/com.sparrowwallet.sparrow.AppServices.<init>(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.5/com.sparrowwallet.sparrow.AppServices.initialize(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.5/com.sparrowwallet.sparrow.SparrowDesktop.start(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics@18/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics@18/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics@18/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	... 1 common frames omitted
```

**Comment by craigraw** [comment] 2024-04-23 09:43
This is caused by the same issue in #1385, so marking as duplicate.

**Closed by craigraw** 2024-04-23 09:43 UTC
