### ISSUE TITLE
Not able to sign a transaction with Ledger

### ISSUE THREAD

**Issue by finned-palmer** [sparrowwallet/sparrow#361] opened 2021-12-14 15:50 UTC
I'm trying to combine several segwit UTXOs and spend them to a separate wallet, but each time I go to sign the TX via my Ledger I get this error "Non-witness UTXO does not match outpoint hash".

This is on Sparrow version 1.5.4 on Linux.

I have previously only sent single UTXOs using Sparrow, this is the first time I've tried combining them.

**Comment by craigraw** [comment] 2021-12-14 18:20
Thanks for bug report, duplicate of #356. Expect a new release shortly with this fixed.

**Closed by craigraw** 2021-12-14 18:20 UTC

**Comment by finned-palmer** [comment] 2021-12-14 18:23
Great, thanks for the quick response.

**Comment by craigraw** [comment] 2021-12-20 10:17
ICYMI - Sparrow v1.5.5 fixes this problem.
