### ISSUE TITLE
Dissappeared first address

### ISSUE THREAD

**Issue by wordkeepa** [sparrowwallet/sparrow#93] opened 2021-04-06 02:31 UTC
I have created a new software wallet, generated a new address (very first one). Then I've sent some btc to that address. It didn't arrive. Explorer shows confirmed transaction for that address. Sparrow doesn't have this address in the list of its addresses! What happened? Any idea?

**Comment by craigraw** [comment] 2021-04-06 06:12
Did you set a passphrase on this software wallet? (as opposed to the wallet password, which is different). Sparrow does not store the passphrase, but asks for it every time you open the wallet, and generates a different set of addresses. Here's where you would enter the passphrase on creating the wallet:

<img width="424" alt="Screenshot 2021-04-06 at 08 11 26" src="https://user-images.githubusercontent.com/862166/113666564-c1374480-96af-11eb-8ef7-0285e77262da.png">

**Comment by wordkeepa** [comment] 2021-04-06 14:47
> Did you set a passphrase on this software wallet? (as opposed to the wallet password, which is different). Sparrow does not store the passphrase, but asks for it every time you open the wallet, and generates a different set of addresses. Here's where you would enter the passphrase on creating the wallet:
> 

Yes I did. I use the same passphrase when I open the wallet.

**Comment by craigraw** [comment] 2021-04-06 15:41
I tested this functionality, and I'm able to reproduce a software wallet by re-entering the seed, passphrase and choosing the same script type. All addresses are the same.

It's hard for me to say what happened here, but it appears one of these inputs was different - I suggested the passphrase, since it is the only one that is re-entered when opening the wallet. Are the addresses consistent now between wallet re-opens?

**Comment by wordkeepa** [comment] 2021-04-06 15:49
Yes, addresses are consistent upon loading. It's very strange. I've written the wallet password and keystore passphrase, so it's hard to be wrong on this side. A mystery...

**Comment by craigraw** [comment] 2021-04-07 08:07
Possibly a mixup between passphrase and password? Or try creating without the passphrase? 

It feels there's going to some combination that retrieves that address in a deterministic way.

**Comment by craigraw** [comment] 2021-05-17 11:29
Can you check on the Addresses tab whether the addresses are sequential? You can do this by hovering over the address - you should see ../0/0, then ../0/1, then ../0/2 etc. If there is a break in the sequence it may be the missing address.

**Comment by wordkeepa** [comment] 2021-05-19 05:33
I have checked. All indexes are in order. It seems I didn't write down keystore passphrase. Really weird, I'm usually accurate, but this might the case when I did mistake...

**Comment by craigraw** [comment] 2021-05-19 06:26
Thanks for checking. It is weird, and I'm not 100% convinced there is no issue here. That said, I load and use BIP39 wallets on Sparrow every day many times without issue, and I've run tests to ensure that address generation is consistent over many thousand wallet loading iterations. I'll close this off since I can't think of any other ideas right now.

**Closed by craigraw** 2021-05-19 06:26 UTC
