### ISSUE TITLE
A bug with labels with multiple tx outputs

### ISSUE THREAD

**Issue by hokkanen** [sparrowwallet/sparrow#1318] opened 2024-03-14 09:13 UTC
Hi, thanks for a great software. 

I noticed that when I created a tx with a single input and 9 outputs all with different labels, the preview page (after hitting "Create Transaction") messed up all labels (showed just same label 1 for 8 outputs, and some other label for one output). It was still possible to distinguish transactions by their address and value though. Of these 9 outputs, 4 was sent to address AAA and 5 was sent to address BBB with different amounts of BTC. I was using Sparrow 1.8.4 standalone on Windows 10.

**Comment by craigraw** [comment] 2024-03-14 11:17
I can only reproduce this with identical addresses and values - since there is no way to tell these apart when interpreting the transaction, Sparrow is unable to distinguish them to reapply the labels.

Changing either the address or value is sufficient for the outputs to be distinguished though. So I'm not able to recreate what you are seeing based on your description.

**Comment by hokkanen** [comment] 2024-03-20 06:48
I believe this is not just a problem in case all addresses and values are identical. However, even if that is the case, I would personally then randomly assign the labels for each output for user friendliness. It may be confusing that suddenly some lables are missing (harder to do bookkeeping, verifying correctness, etc.).

However, the problem occurs also in the following scenario. I create the following multi-output tx:

tx1_1500sat (to address AAA, value 1500sat)
tx1_1500sat (to address AAA, value 1500sat)
tx1_1500sat (to address AAA, value 1500sat)
tx1_1500sat (to address AAA, value 1500sat)

**Comment by hokkanen** [comment] 2024-03-20 14:25
Bump after edited comment.

**Comment by craigraw** [comment] 2024-03-25 08:18
I can't recreate this. Here is the result of my attempt:

<img width="461" alt="Screenshot 2024-03-25 at 10 15 29" src="https://github.com/sparrowwallet/sparrow/assets/862166/5fbffb31-1a04-4774-bc8a-9fb9e21d0a8a">

As you can see all the odd numbered labels are applied correctly. It is only the even numbered labels (same address and amount) that get the same label. It is also very strange you are getting three change outputs.

**Comment by craigraw** [comment] 2024-05-06 11:02
Closing off as unreproducible.

**Closed by craigraw** 2024-05-06 11:02 UTC
