### ISSUE TITLE
Error broadcasting transaction

### ISSUE THREAD

**Issue by wordkeepa** [sparrowwallet/sparrow#362] opened 2021-12-16 02:39 UTC
Getting this error second day. Before that everything was fine.

![image](https://user-images.githubusercontent.com/55933816/146297900-d65c26cb-001c-475c-9de7-ff5a291d1a66.png)

Please help.

**Comment by craigraw** [comment] 2021-12-16 06:37
Thanks - this is (very likely) a duplicate of #356. There will be release out today to fix it.

**Closed by craigraw** 2021-12-16 06:37 UTC

**Comment by craigraw** [comment] 2021-12-20 10:17
ICYMI - Sparrow v1.5.5 fixes this problem.

**Comment by wordkeepa** [comment] 2021-12-20 16:39
Thank you!

Best,
WK

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
