### ISSUE TITLE
sparrow wallet don't save transaction labels

### ISSUE THREAD

**Issue by onlineapps-cloud** [sparrowwallet/sparrow#1523] opened 2024-10-20 13:04 UTC
hi, why sparrow wallet don't save all labels?, some label are saved, but many labels are not saved, but label is required, i cannot made transaction without label.
![image](https://github.com/user-attachments/assets/d0a4344c-52bb-4e1f-aced-39001f9092ae)

**Comment by craigraw** [comment] 2024-10-21 07:23
How are you broadcasting the transactions? Labels can only be saved when the transaction is created on Sparrow, broadcasted and then received in the same session.

**Comment by craigraw** [comment] 2024-10-22 11:54
> what this mean? what i need to receive in same session?

As in, you broadcasted and received the transaction without closing Sparrow. In this case, the label you set when creating the transaction should always be applied.

**Comment by craigraw** [comment] 2024-10-22 17:06
In the cases where it doesn't appear: After you broadcast the transaction, do you receive a notification, and does it appear in the transactions table?

**Comment by craigraw** [comment] 2024-10-22 17:46
I can't reproduce this - and I test many, many transactions, all of them have the label applied. Further, no other user is reporting this behaviour. You have already provided screenshots of your steps, which look normal, so I'm not sure what else to suggest other than creating a video of the process indicating the problem. If you do this, ideally use testnet so you don't need to blur anything out.

**Comment by craigraw** [comment] 2024-10-24 08:12
Rather use testnet4, testnet3 is deprecated. Create a new wallet. You can get testnet coins from (for example) https://coinfaucet.eu/en/btc-testnet4/.

**Comment by craigraw** [comment] 2024-11-18 06:43
Glad to hear. You should be able to close the transaction tab after the broadcasted transaction has been received into the wallet. Closing this off.

**Closed by craigraw** 2024-11-18 06:43 UTC
