### ISSUE TITLE
Unable to Sign Transaction with a Trezor on a Taproot Wallet

### ISSUE THREAD

**Issue by dotSpectrum** [sparrowwallet/sparrow#403] opened 2022-01-17 03:18 UTC
When I attempt to send and sign an UTXO on my Taproot account with my Trezor, my Trezor keeps saying "Path m/86'/0'/0'/0/1 is unknown. Are you sure? (Yes) (No). After selecting Yes, Sparrow reports that the "Provided spent UTXOs length does not equal the number of transaction inputs." I am unable to spend the UTXO at this point.

This issue does not occur when I import my Bip39 seed phrase onto the Taproot account and attempt to spend the UTXO. Maybe this is a Trezor issue? Not really sure.

**Comment by craigraw** [comment] 2022-01-17 07:32
Duplicate of #376 - the upstream HWI project that Sparrow uses to communicate with the Trezor does not yet support Taproot. Hopefully it will soon, development is ongoing. I'll leave this issue open though, it may help others.

**Comment by dotSpectrum** [comment] 2022-02-12 21:11
Just following up with this; HWI #554 adds support for receiving and spending taproot payments with Trezor hardware signing devices.

https://github.com/bitcoin-core/HWI/pull/544

**Comment by craigraw** [comment] 2022-02-13 05:49
Thanks, hopefully we'll see a HWI release soon.

**Comment by craigraw** [comment] 2022-09-06 10:50
Signing Taproot transaction with Trezor has been supported since Sparrow v1.6.4 - closing this off.

**Closed by craigraw** 2022-09-06 10:50 UTC
Labels: upstream
