### ISSUE TITLE
Sending With Taproot Issues

### ISSUE THREAD

**Issue by nbourbon** [sparrowwallet/sparrow#494] opened 2022-03-31 00:07 UTC
I'm trying to send coins with Sparrow connected to Ledger but I'm consistently getting the same error. "Provided Spent UTXOs Length does not equal the number of transaction inputs".

I've seen someone else reporting the same in Trezor's blog, in my case is with Ledger so I'm assuming is just a sparrow fix that is needed?

**Comment by craigraw** [comment] 2022-03-31 06:00
Duplicate of #403 - testing and bug reporting on the HWI 2.1.0 release candidate is underway.

**Closed by craigraw** 2022-03-31 06:00 UTC

**Comment by nbourbon** [comment] 2022-04-04 20:53
Just checking, do you have an ETA for it?. I just downloaded this latest version of sparrow but at the time of signing with my ledger it says "Bad Argument" now :(

**Comment by craigraw** [comment] 2022-04-29 09:36
In the order of weeks now :)
