### ISSUE TITLE
Post-mix Account Change Outputs

### ISSUE THREAD

**Issue by apemithrandir** [sparrowwallet/sparrow#1374] opened 2024-04-14 08:50 UTC
I do a bit of spending from my Post-mix account. In the current setup that leaves me with quite a few change output UTXOs in my Post-mix account to be managed. If I wanted to put these through whirlpool again I would need to send them to my deposit account first and then to whirlpool.

Potentially Post-mix change outputs could default to going back to the deposit account? Or allow mixing of selected UTXOs from their Post-mix account into Whirlpool directly?

 - Would defaulting Post-mix change to go back to deposit confuse users? I believe Samourai might do this with their wallet.
 - Does the Whirlpool protocol even allow mixing selected UTXOs if they are not found in the deposit account?

**Comment by RequestPrivacy** [comment] 2024-04-14 09:17
> Would defaulting Post-mix change to go back to deposit

Not sure if going back to `Deposit` would be a good thing as it could lead to linking pre- & post mix utxos. It should only be allowed to go directly from postmix -> premix account I guess.

That beeing said, seems to be a duplicate of #918

**Closed as completed** 2024-04-14 09:28 UTC
