### ISSUE TITLE
Unable to start the wallet in Windows 10

### ISSUE THREAD

**Issue by gustmp** [sparrowwallet/sparrow#138] opened 2021-06-15 18:42 UTC
I downloaded, verified the signature, installed, but when I click to open, the application is closed in less than half a second.
When I "%APPDATA%/Sparrow" the sparrow.txt is empty.

**Comment by craigraw** [comment] 2021-06-16 08:02
Can you take a look in the Sparrow installation folder (probably something like `~/AppData/Local/Sparrow`) to see if there are any dump files? They generally start with a name like `hs_err_pid*.log`.

**Comment by gustmp** [comment] 2021-06-17 00:06
I'm sorry, could not find any dump file
att
![Captura de tela 2021-06-16 210556](https://user-images.githubusercontent.com/77026980/122310418-ac183680-cee6-11eb-96af-b3ecb472588e.jpg)

**Comment by craigraw** [comment] 2021-06-17 13:37
Thanks for checking. 

Have you tried running it from this folder on the command line (`cmd` in Windows) to see there's anything useful shown? 
```
> Sparrow.exe
```

Also, there might be something logged in the Windows Event Viewer.

**Comment by gustmp** [comment] 2021-06-19 16:26
> Thanks for checking.
> 
> Have you tried running it from this folder on the command line (`cmd` in Windows) to see there's anything useful shown?
> 
> ```
> > Sparrow.exe
> ```
> 
> Also, there might be something logged in the Windows Event Viewer.

Same thing happened when trying to use the cmd to start it.
I'm a noob and couldn't find anything in windows event viewer.
Uninstalled and downloaded the standalone version, same problem still

**Comment by craigraw** [comment] 2021-06-22 07:01
Can you take another look for any `hs_err_pid*.log` files? My hope is that starting from the command line may have left one in that folder, or perhaps in the `app` or `runtime` subfolders.

**Comment by cd2357** [comment] 2021-09-10 11:16
Tried to reproduce with Sparrow 1.4.3 on Windows 10.

The first thing I get when trying to start it is this:

<img width="542" alt="Screenshot 2021-09-10 at 13 00 01" src="https://user-images.githubusercontent.com/15956136/132843790-56a599eb-d329-4260-9ded-900d0022edc8.png">

After clicking "More info" it changes to

<img width="541" alt="Screenshot 2021-09-10 at 13 00 13" src="https://user-images.githubusercontent.com/15956136/132843742-89952bbf-bee0-49d3-b672-74ef651e6fbf.png">

Clicking "Run anyway" then starts it and then it works fine for me.

I'm thinking that maybe MS Defender is interfering with the starting of the app on your system, maybe blocking it automatically due to some stricter protection rules or so.

Can you please try the following to disable MS Defender for this app:

In the standalone version, right click on Sparrow.exe > Properties and make sure to tick the following checkbox > OK:

<img width="364" alt="Screenshot 2021-09-10 at 13 08 13" src="https://user-images.githubusercontent.com/15956136/132845127-e8fb73bf-d49c-41fa-bea8-ec2f7df57752.png">

If you start Sparrow.exe now, does it work?

**Comment by gustmp** [comment] 2021-09-10 16:25
I got theese blue Windows info boxes when running the installer.
Only saw the option to "Unblock" when right clicking the installer also.
Tried running the app but it shutdowns immediatly.
I research and tried turning off some Windows Security Defender options (https://www.windowscentral.com/how-fix-app-has-been-blocked-your-protection-windows-10) and running again: same problem.
I will restart my PC with the changes in Security Defender and the run again.

**Comment by gustmp** [comment] 2021-09-10 21:16
I downloaded Sparrow for Linux using a VM and it worked fine.
I think my system is corrupted because it seems i'm the only one with this problem.
I'm going to close the issue.

**Comment by cd2357** [comment] 2021-09-11 10:12
One last thing you could try is see if Sparrow logged anything that could help pinpoint the issue.

Under `C:\Users\<YourUsername>\AppData\Roaming\Sparrow` you should see a file `sparrow.log`

Does it contain anything useful?

**Comment by Thomaasss** [comment] 2023-02-16 21:54
Hi,

I also have a problem with Sparrow on W11 Pro. I tried all solutions given above nothing worked for me.

The software installs successfully, but when I try to open it, Sparrow appears in my taskbar but nothing is displayed. It's as if I had a transparent veil on my screen, I cannot click on nothing. I have to do CTRL+ALT+DEL to move the window to the background. 
If I re-click on the taskbar icon, same problem. Even when disabling firewall, running as administrator, And nothing in logs about this problem..

**Some technical specs :** 
Processor : 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz   2.80 GHz
RAM : 32.0 GB
**Windows :** 
Edition : Windows 11 Pro
Version : 21H2

Thanks for your help

**Comment by craigraw** [comment] 2023-02-17 06:05
@Thomaasss You say nothing is displayed, but then suggest that the window is displayed, you just cannot interact with it. Have you tried interacting with the application menu bar?

**Comment by Thomaasss** [comment] 2023-02-17 15:09
@craigraw Yes that's right. No I cannot interact with nothing, I tried to play a video on YouTube while launching Sparrow and the result is that video is freezing (I have only sound). On the other hand if I open the task manager while lanching Sparrow, it continues to move, so it seems to be a freeze due to resources rather than a screen freeze.

Idk if it can help but I can leave a task manager screenshot : 
![image](https://user-images.githubusercontent.com/44288315/219691503-2bddd099-8606-4752-8087-66a4efd64649.png)

**Comment by sheepbild** [comment] 2023-06-30 11:35
I tried on ubuntu on vmware and re-tried on windows but always a problem... The software works 1 or 2 times and freeze or crash at once and even after desinstal/reinstalling, restarting my computer I have always an issue : 

On ubuntu it worked last time and not today (a crash and impossible to reopen the software) : maybe a ram problem on vmware ?
On windows it worked few months ago 1 or 2 time and now when I reopen de software appears transparent and I can't click anywhere. I tried other versions, same problem

Here is a video of this behavior on ubuntu and windows :
https://www.youtube.com/watch?v=vxmfbP-vI4A&ab_channel=SheepBild

**Comment by gustmp** [comment] 2023-06-30 12:55
After

> I tried on ubuntu on vmware and re-tried on windows but always a problem... The software works 1 or 2 times and freeze or crash at once and even after desinstal/reinstalling, restarting my computer I have always an issue :
> 
> On ubuntu it worked last time and not today (a crash and impossible to reopen the software) : maybe a ram problem on vmware ? On windows it worked few months ago 1 or 2 time and now when I reopen de software appears transparent and I can't click anywhere. I tried other versions, same problem
> 
> Here is a video of this behavior on ubuntu and windows : https://www.youtube.com/watch?v=vxmfbP-vI4A&ab_channel=SheepBild

After months, updated to windows11 and never had the same problem again

**Comment by craigraw** [comment] 2023-07-01 06:32
@sheepbild It's unclear what is causing your issue, but it appears localized to the machine you are using. Unfortunately without more information there's not much I can action here - it may be a hardware issue. This issue is old and rather vague, so I'm going to close it off again.

**Closed by craigraw** 2023-07-01 06:32 UTC
Labels: question

**Comment by Ayush170-Future** [comment] 2023-07-19 17:09
I'm facing the same problem on Windows 10. When I try to run the `.exe` file it starts and crashes immediately within a second.

**Comment by craigraw** [comment] 2023-07-20 05:59
@Ayush170-Future Have you tried all the advice above?

**Comment by sheepbild** [comment] 2023-07-20 06:03
I found a solution that finally worked for me : 
Uninstall Sparrow, and go to C:\Users\YourUser\AppData\Roaming and delete Sparrow folder
Then reinstall the app

Hope it'll help

**Comment by Ayush170-Future** [comment] 2023-07-20 07:04
> @Ayush170-Future Have you tried all the advice above?

It's now working. Actually, I reinstalled the executable and it crashed again shortly after starting, but this time it automatically built the App on the desktop, which works great.

**Comment by deadcoder0904** [comment] 2023-12-21 10:03
> Can you take a look in the Sparrow installation folder (probably something like `~/AppData/Local/Sparrow`) to see if there are any dump files? They generally start with a name like `hs_err_pid*.log`.

same error on windows 11 but i saw this in `C:\Users\<USERNAME>\AppData\Local\Sparrow` & it opens up fine from now on after i opened `.exe`.

![image](https://github.com/sparrowwallet/sparrow/assets/16436270/b5ec6d21-9357-4712-b3fb-6f42f25b3e0a)

i didn't defender warning either before. it just closed in half-a-second like the original poster said.
