### ISSUE TITLE
Unable to install release 1.7.2-1_amd64

### ISSUE THREAD

**Issue by LeoSpyke** [sparrowwallet/sparrow#832] opened 2023-02-12 10:36 UTC
It is not possible to install the new 1.7.2-1_amd64 release under Tails 5.8.

This is the error reported when running the command `dpkg -i package.deb`:

```
dpkg-deb: error: archive '/home/amnesia/sparrow_1.7.2-1_amd64.deb' uses unknown compression for member 'control.tar.zst', giving up
dpkg: error processing archive /home/amnesia/sparrow_1.7.2-1_amd64.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2
```

**Comment by craigraw** [comment] 2023-02-12 10:41
Duplicate of #829 - please see that issue for a temporary fix to repackage the .deb, an updated release will follow shortly.

**Closed by craigraw** 2023-02-12 10:41 UTC
