### ISSUE TITLE
Menus Auto-close

### ISSUE THREAD

**Issue by bettyvschmartz** [sparrowwallet/sparrow#325] opened 2021-11-23 19:07 UTC
Small issue which has been present in the last few versions. Any of the menus require _holding_ a left-click on the menu headings (similar to a Mac) otherwise the menus close. In order to navigate the menu I have to hold left-click and use the arrow keys to navigate down the menu and hit enter. I generally resort to keyboard shortcuts or alt+arrows. 

This is on a Debian machine. It isn't an issue with other apps so it doesn't seem to be a window manager problem but possibly something Java related. 

-- bvs

**Comment by craigraw** [comment] 2021-11-24 07:29
Thanks, duplicate of #170.

**Closed by craigraw** 2021-11-24 07:29 UTC
Labels: duplicate
