### ISSUE TITLE
electrs reports inefficient query methods being used by wallet

### ISSUE THREAD

**Issue by stripey679** [sparrowwallet/sparrow#694] opened 2022-09-24 13:09 UTC
Sparrow Version: 1.6.6
electrs Version:0.9.9
Date Observed: 2022-09-23

[Electrs](https://github.com/romanz/electrs) (Specifically, the [Start9Labs wrapper](https://github.com/start9labs/electrs-wrapper)) reports the following in the logs:
`INFO  electrs::electrum] your wallet uses less efficient method of querying electrs, consider contacting the developer of your wallet. Reason: blockchain.scripthash.get_balance called for unsubscribed scripthash`

Sparrow is the only wallet I have been using recently with this Electrum (Electrs) server, and I saw the logs appear as recently as yesterday, so I assume this must be an issue with Sparrow even though it doesn't identify the wallet in the message.

**Comment by craigraw** [comment] 2022-09-26 06:44
Duplicate of #593. Although the warning seems serious, it is really a non-issue.

**Closed by craigraw** 2022-09-26 06:44 UTC
Labels: duplicate
