### ISSUE TITLE
Fit to screen. Win 10

### ISSUE THREAD

**Issue by Panzer7** [sparrowwallet/sparrow#143] opened 2021-06-24 06:32 UTC
Hi. Just started using Sparrow. The page does not fit the screen. Top and bottom are off screen and I cannot find any way to resize the page.

**Comment by craigraw** [comment] 2021-06-24 07:56
Could you provide more details on your screen - is it perhaps a 4k? Could be a duplicate of #117.

**Comment by Panzer7** [comment] 2021-06-24 09:43
Hi Craig

It’s just a standard laptop screen. Asus Zenbook 13. Win 10. Top and bottom of the page are clipped and the sides are smaller than the screen with no way to resize.

Hope this helps

Regards

Ian

On 24 Jun,2021, at 11:57, craigraw ***@***.***> wrote:

﻿

Could you provide more details on your screen - is it perhaps a 4k? Could be a duplicate of #117<https://github.com/sparrowwallet/sparrow/issues/117>.

**Comment by Panzer7** [comment] 2021-06-24 09:51
[cid:916663A8-AF04-4724-8A95-452989A7E951][cid:118C4C57-F0AB-40B8-9BFA-7AA70B3337D6]

On 24 Jun,2021, at 11:57, craigraw ***@***.***> wrote:

﻿

Could you provide more details on your screen - is it perhaps a 4k? Could be a duplicate of #117<https://github.com/sparrowwallet/sparrow/issues/117>.

**Comment by craigraw** [comment] 2021-06-24 10:01
Ok - looks like you have a max resolution of 1920 x 1080 which is more than sufficient. Is this is configured resolution? Sparrow's minimum supported resolution is 1366 x 768. I am running Sparrow here on Win10 at 1920 x 1080 with scaling at 125%.

**Comment by Panzer7** [comment] 2021-06-24 12:06
Thanks Craig, that has answered my query

Regards

Ian

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by craigraw** [comment] 2021-06-24 12:17
Great, closing this off then.

**Closed by craigraw** 2021-06-24 12:17 UTC

**Comment by RequestPrivacy** [comment] 2021-08-16 08:47
> Sparrow's minimum supported resolution is 1366 x 768

I have the mentioned resolution and after every new startup of sparrow it cuts the lower part so that I can't see the connection toggle (the gray/yellow/blue one). I always have to resize the vertical window dimension manually. At the minimum window height which it allows me it fits just right between top and bottom panels of my linux desktop.

a) is there a way to reduce the vertical dimension even further, so that it doesn't sit that tight between the panels?
b) can I safe the reduced window size somewhere, so that I don't have to resize it manually at every startup?

**Comment by craigraw** [comment] 2021-08-16 09:29
Unfortunately reducing the vertical dimension even further is really difficult, and would require some significant UI changes (probably for the worse in the general case).

However, as of a3e4342, Sparrow will now retain the adjusted width and height across restarts.

**Comment by RequestPrivacy** [comment] 2021-08-16 09:41
Fantastic, that should be more than fine. I guess a 1366 x 768 resolution is also quit uncommon today, so it doesn't justify wasting resources on the major UI changes you mentioned.
