### ISSUE TITLE
Import from and export to extended private key wallet descriptors

### ISSUE THREAD

**Issue by icy-ux** [sparrowwallet/sparrow#1208] opened 2023-12-27 11:59 UTC
Right now the wallet descriptors exported by Sparrow only contain xpubs.

It's not possible to export a wallet descriptor containing xprv/yprv/zprv, because [drongo doesn't support it](https://github.com/sparrowwallet/drongo/blob/579c86b1a748e410c51f637cd79cbb701996b7e3/src/main/java/com/sparrowwallet/drongo/OutputDescriptor.java).

Importing a descriptor containing an extended private key results in a watch-only wallet. This is undesirable: if I give Sparrow an extended private key, I should get a full wallet.

Both of these should be fixed so that we can import from and export to wallet descriptors containing private keys.

**Comment by craigraw** [comment] 2023-12-27 13:44
Duplicate of #1137. Adding this functionality would add considerable complexity throughout the wallet, without (AFAIK) a strong use case.

**Closed by craigraw** 2023-12-27 13:44 UTC

**Comment by icy-ux** [comment] 2023-12-28 03:17
On Wed, Dec 27, 2023 at 05:44:26AM -0800, craigraw wrote:
>Duplicate of #1137. Adding this functionality would add considerable complexity throughout the wallet, without (AFAIK) a strong use case.

Without a strong use case?

Are you only ever using hardware wallets for everything, or something
like that?

If someone wants to import a non-watch-only-wallet using a descriptor,
how are they supposed to do that right now? Import the descriptor and
then add the seed phrase manually?

If someone wants to export a non-watch-only-wallet to a descriptor-based
wallet (e.g anything using BDK)... how are they supposed to do that
right now? Export the descriptor, and then -- break down and cry because
they only got a watch-only wallet, and that's the only option?

As it stands building a descriptor wallet that only handles public keys
seems fundamentally incomplete, as if Michaelangelo had sculpted David
but left off one leg.

**Comment by icy-ux** [comment] 2023-12-28 03:21
On Wed, Dec 27, 2023 at 05:44:26AM -0800, craigraw wrote:
>Duplicate of #1137.

#1137 is specific to importing non-master extended private keys. This
issue is also about importing master extended private keys.
