### ISSUE TITLE
Missing `1 sat`

### ISSUE THREAD

**Issue by kolya182** [sparrowwallet/sparrow#148] opened 2021-06-27 01:57 UTC
This is not the first time happen to me, just trying to understand what is going on.
Created tax this way with spend amount `0.00056` and after transaction signed and broadcasted actual spend amount `0.00055999`, where did one sat go ?.
<img width="1084" alt="Screen Shot 2021-06-26 at 6 46 14 PM" src="https://user-images.githubusercontent.com/3277207/123530446-2303bb00-d6af-11eb-8bf3-8d65d567a3e3.png">
<img width="1049" alt="Screen Shot 2021-06-26 at 6 47 32 PM" src="https://user-images.githubusercontent.com/3277207/123530530-39f6dd00-d6b0-11eb-9bc8-a6ad7d7a2b34.png">

**Comment by craigraw** [comment] 2021-06-27 06:39
I can't reproduce this. Can you provide steps that create this behaviour?

**Comment by kolya182** [comment] 2021-06-29 22:23
> I can't reproduce this. Can you provide steps that create this behaviour?

I will record a video next time, where I can send you a private message ?

**Comment by craigraw** [comment] 2021-06-30 06:56
Probably easiest on Telegram - I'm @craigraw. Also, the same on Keybase and Twitter. Thanks

**Comment by 6102bitcoin** [comment] 2021-10-04 22:47
@kolya182 were you able to replicate?

**Comment by kolya182** [comment] 2021-10-05 03:12
> @kolya182 were you able to replicate?

Can't confirm or deny. If no one else had this issue, please close it.

**Comment by craigraw** [comment] 2021-10-05 06:56
I haven't had any other similar reports, so closing this off as requested.

**Closed by craigraw** 2021-10-05 06:56 UTC
Labels: bug, question
