### ISSUE TITLE
Cannot connect to Bitcoin Core server

### ISSUE THREAD

**Issue by comminutus** [sparrowwallet/sparrow#1254] opened 2024-02-01 16:19 UTC
Hello, I compiled bitcoin core and am running it via a container image.  The blockchain is fully synchronized.  I can netcat to port 8442 on the same machine I am running Sparrow without issue.  I can also curl it with no issue.  When I try to connect with Sparrow, I see the following error message in the Sparrow log:

```
2024-02-01 16:14:37,106 ERROR [JavaFX Application Thread] c.s.s.p.ServerPreferencesController [null:-1] Connection error
java.lang.IllegalStateException: I/O error during request processing
	at simple.json.rpc.client@1.3/com.github.arteam.simplejsonrpc.client.builder.ObjectApiBuilder.execute(Unknown Source)
	at simple.json.rpc.client@1.3/com.github.arteam.simplejsonrpc.client.builder.ObjectApiBuilder.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy17.getNetworkInfo(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.2/com.sparrowwallet.sparrow.net.cormorant.bitcoind.BitcoindClient.initialize(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.2/com.sparrowwallet.sparrow.net.cormorant.Cormorant.start(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.2/com.sparrowwallet.sparrow.net.ElectrumServer$ConnectionService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.2/com.sparrowwallet.sparrow.net.ElectrumServer$ConnectionService$1.call(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.FileNotFoundException: http://bitcoind:8332/wallet/cormorant
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.2/com.sparrowwallet.sparrow.net.cormorant.bitcoind.BitcoindTransport.pass(Unknown Source)
	... 15 common frames omitted
Caused by: java.io.FileNotFoundException: http://bitcoind:8332/wallet/cormorant
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.base/java.net.HttpURLConnection.getResponseCode(Unknown Source)
	... 16 common frames omitted
```

The host, `bitcoind` is exposed over tailscale.  When I curl the URL it tries to hit (http://bitcoind:8332/wallet/cormorant), I receive a 404 HTTP error.

Any clue what might be going on?  I am running Sparrow v1.8.2, Bitcoin Core v26.0

**Comment by craigraw** [comment] 2024-02-02 06:36
Did you compile Bitcoin Core with wallet support? There may be a previous error in the sparrow log that is relevant.

Closing as it is not a feature or bug report.

**Closed by craigraw** 2024-02-02 06:36 UTC

**Comment by comminutus** [comment] 2024-02-02 10:38
@craigraw that is the entirety of the log. Here is how I compiled bitcoin core:
```
./autogen.sh
./configure --with-gui=no
make
```

As far as I can tell, this would produce a build with wallet support wouldn't it?

**Comment by craigraw** [comment] 2024-02-02 11:09
You can also disable wallets with `disablewallet=1` in bitcoin.conf.

That said, it may be more of a network configuration issue. Can you try running `bitcoin-cli` on the machine running Sparrow, configured to talk to your host?

**Comment by comminutus** [comment] 2024-02-03 12:57
`bitcoin-cli` seems to work (`rpcconnect`, `rpcport`, `rpcuser`, and `rpcpassword` are set appropriately in the `.conf` file referenced, `bitcoin-cli` running on the the same machine as sparrow):

```
./bitcoin-cli -conf=/var/home/comminutus/Downloads/bitcoin-26.0-x86_64-linux-gnu/bitcoin-26.0/bitcoin.conf getblockchaininfo
{
  "chain": "main",
  "blocks": 828730,
  "headers": 828730,
  "bestblockhash": "000000000000000000011dc7d7a93e128a9185c7cc855b8c334127b78abcbbbd",
  "difficulty": 75502165623893.72,
  "time": 1706964595,
  "mediantime": 1706960714,
  "verificationprogress": 0.9999992937843648,
  "initialblockdownload": false,
  "chainwork": "0000000000000000000000000000000000000000687d817cf16da11ee8d358e0",
  "size_on_disk": 620251956178,
  "pruned": false,
  "warnings": ""
}
```

**Comment by craigraw** [comment] 2024-02-05 05:56
> Does Sparrow support Bitcoin Core v26.0?

Yes.

It may be possible that `bitcoind` is not resolving properly in Sparrow to an IP address. Can you try an IP address instead?

**Comment by craigraw** [comment] 2024-02-07 07:35
> Is this value somehow cached?

I don't think so, but it does seem related to your `bitcoind` config. Asking the obvious here, you have `server=1`? It also looks like `bitcoind` sends a 404 with incorrect user credentials, so that's something to check you have correct in Sparrow as well.

**Comment by comminutus** [comment] 2024-02-07 12:47
`server=1` is indeed set, I don't think bitcoin-cli would work otherwise, right?  I tried changing the password to something very simple thinking perhaps it has something to do with character encoding but I get the same error.

Here's the entirety of the config:
```
estimatefee=1
printtoconsole=1
minrelaytxfee=0.00001
rpcallowip=10.0.0.0/8
rpcallowip=172.16.0.0/12
rpcallowip=192.168.0.0/16
rpcallowip=100.64.0.0/10
rpcbind=0.0.0.0
rpcuser=bitcoin
rpcpassword=<omitted>
server=1
txindex=1
zmqpubrawblock=tcp://0.0.0.0:28332
zmqpubrawtx=tcp://0.0.0.0:28332
zmqpubsequence=tcp://0.0.0.0:28332
```

**Comment by craigraw** [comment] 2024-02-09 07:47
If you use `curl` without the `/wallet/cormorant` path do you still get a 404?

**Comment by comminutus** [comment] 2024-02-09 16:40
No, it returns a `405`:
```
curl -s http://100.64.0.11:8332
JSONRPC server handles only POST requests

curl -w "%{http_code}" -o /dev/null -s http://100.64.0.11:8332
405
```

**Comment by craigraw** [comment] 2024-02-13 07:31
Ok - and do you get the same results if you perform these commands on the machine with Bitcoin Core running, talking to `localhost`? Apologies if you already covered this above.

**Comment by craigraw** [comment] 2024-02-19 07:08
Here's where my install is different - I get a `405` response for any wallet, including one to an imaginary wallet:

```
curl -w "%{http_code}" -o /dev/null -s http://localhost:8332/wallet/justmadethisup
405
```

So it looks like the problem is either with your install of Bitcoin Core, or the configuration of it. Are you able to interact with the wallet features - for example using `bitcoin-cli createwallet`?
