### ISSUE TITLE
Feature request: monospace font for dates and numbers in transactions overview.

### ISSUE THREAD

**Issue by rdouma** [sparrowwallet/sparrow#1524] opened 2024-10-20 23:09 UTC
In my opinion the transactions overview would look much better if dates are neatly aligned as well as the decimal point of the value and the balance. It'll probably look better if the transactions column also uses that same monospace font; I would prefer that over all columns _not_ having a monospace font.

**Comment by craigraw** [comment] 2024-10-21 08:40
I assume you are using macOS?

This actually looks like a regression, since Sparrow is using Helvetica Neue Regular to display values which is used in macOS Numbers for it's monospaced display of digits. It appears that in upgrading to JavaFX 22, this monospaced property was lost. I'll need to investigate if it's possible to get it back.

**Comment by rdouma** [comment] 2024-10-21 12:42
Indeed, I use MacOS, apologies for not adding that to the original issue. Here are some screenshots that illustrate what I mean.

![2024-10-21_09-40-25](https://github.com/user-attachments/assets/00d9509f-97dc-48f3-8aae-b4fc4c546a9e)
![2024-10-21_09-40-09](https://github.com/user-attachments/assets/99ed9b4a-df33-476c-b07b-b03c44d770e3)
![2024-10-21_09-39-17](https://github.com/user-attachments/assets/e699fe34-1913-4d52-9e40-cde06cd98f12)

**Comment by craigraw** [comment] 2024-10-22 17:58
It did turn out to be a regression introduced in the recent upgrade to JavaFX 22 in Sparrow 2.0.0. I'm working on a fix using the font Liberation Sans which provides monospaced characters for digits, but looks sufficiently similar to the system font to not be visually jarring:

<img width="874" alt="Screenshot 2024-10-22 at 19 54 35" src="https://github.com/user-attachments/assets/5862969f-d3d2-40b6-b6a2-e7a7e7f04fd9">

**Comment by craigraw** [comment] 2024-10-28 08:04
Regression fixed in d0bf55de.

**Closed by craigraw** 2024-10-28 08:04 UTC

**Comment by rdouma** [comment] 2024-10-28 15:00
Thanks! 🙏 Looking forward to the new release.
