### ISSUE TITLE
Issues with jade on sparrow wallet

### ISSUE THREAD

**Issue by HenryHerbert** [sparrowwallet/sparrow#1450] opened 2024-07-02 17:51 UTC
I am having issues signing transactions on sparrow wallet with my block stream Jade. When I click to sign the transaction on the Jade, it comes up with a error code on sparrow saying cannot read input transaction. Any ideas what I can do?

**Comment by craigraw** [comment] 2024-07-03 04:54
Probably a duplicate of #1060 - upgrading the Jade driver solves this.

**Comment by craigraw** [comment] 2024-07-10 15:50
Closing as duplicate.

**Closed by craigraw** 2024-07-10 15:50 UTC
