### ISSUE TITLE
fund and addresses disappear from wallet

### ISSUE THREAD

**Issue by heyambob** [sparrowwallet/sparrow#528] opened 2022-04-26 06:41 UTC
Yesterday I sent a bunch of transactions to my sparrow wallet. I generated new address for each transaction. Yesterday, I saw unconfirmed incoming transaction before getting new address for next transaction. I did not wait for those tx to confirm and I closed the app.

Today those tx has already confirmed. When I opened my sparrow wallet, nothing from yesterday showed up. I put those addresses that I sent to yesterday in the sign message to test signing message with them, but the app says the addresses are not in my wallet.

I tried to refresh wallet / recreated wallet from the seed, nothing has changed.

Please advise.

**Comment by Transisto** [comment] 2022-04-26 06:58
Do you have more than one account in the wallet?

Did you ever see the missing transaction coming in the Sparrow wallet?

Have you tried increasing the gap limit?

<img width="206" alt="image" src="https://user-images.githubusercontent.com/388716/165240426-7296a492-05c3-4d26-916c-c57cd1f43e6d.png">

Click advanced then change the number 20 for 200

**Comment by heyambob** [comment] 2022-04-26 07:27
right I'm using passphrase. I just noticed that it doesn't warn or error when entering wrong passphrase. What do I do ? Trying to guess what I typed wrong yesterday ?

**Comment by craigraw** [comment] 2022-04-26 07:56
You misunderstand what a BIP39 passphrase is (which is very common, so don't feel bad!). Every passphrase creates a valid wallet, and this feature is key to creating "decoy" wallets which are useful in coercion situations. There is no "wrong passphrase" in this sense, and in fact Sparrow stores nothing about it so it cannot even tell if the passphrase differs from a previous entry. This is intentional behaviour.

What you are looking for is a wallet password, which does what you are describing (fails when incorrect password is used). Closing this off as a passphrase issue.

**Closed by craigraw** 2022-04-26 07:56 UTC

**Comment by heyambob** [comment] 2022-04-26 09:12
How does user be sure that the passphrase he enters is what he intends to use?

For example, in offline mode, user wants to grab some new addresses to receive, he opens it, miss types passphrase, the app show tx history of when the app was online, he assumes it's the right wallet and uses those addresses.

**Comment by craigraw** [comment] 2022-04-26 10:58
> How does user be sure that the passphrase he enters is what he intends to use?

The passphrase in the BIP39 spec leaves this responsibility to the user. This is by design. If you choose to use a passphrase (it is optional, and considered an advanced feature) then it is your responsibility to remember it correctly.

> Or the public electrum server that he connects to is broken or he has bad internet connection, the app still shows the tx old history convincing him to believe it's the right wallet.

No, this will not happen. If on loading the wallet Sparrow finds that all the transaction history has changed, it will perform a full wallet refresh, showing a new empty wallet without any of the prior transactions.

> Btw, where do I have to look if I want to bruteforce the passphrases, programmatically. I think I might have miss typed a few combination of them and losing here and there without noticed

You will need to try each option to see if there are funds in that particular wallet.

**Comment by heyambob** [comment] 2022-04-26 12:39
> No, this will not happen. If on loading the wallet Sparrow finds that all the transaction history has changed, it will perform a full wallet refresh, showing a new empty wallet without any of the prior transactions.

Maybe this is a bug then, because when I turn off my wifi, open sparrow wallet, enter a wrong passphrase, it does not clear the transaction history.

Also another flaw is, supposed I just create my new empty wallet with a passphrase. Then I close the app, open it with a typo on the passphrase (I would have no idea that I miss typed it because it's a new empty wallet), then I use it to receive. Few days l later I typed the correct passphrase and don't see my transactions.

Shouldn't the sparrow app, show some short string derived from the seed+passphrase as an ID so that user would be able to notice right away that what he type isn't what he typed ?

**Comment by craigraw** [comment] 2022-04-26 12:55
> Maybe this is a bug then, because when I turn off my wifi, open sparrow wallet, enter a wrong passphrase, it does not clear the transaction history.

If Sparrow is offline it cannot know the transaction history has changed. Transactions are looked up from the server.

> Shouldn't the sparrow app, show some short string derived from the seed+passphrase as an ID so that user would be able to notice right away that what he type isn't what he typed ?

Sparrow already does this - see the Master Fingerprint field in the Settings tab. This will be different for every passphrase. Writing this down is a good idea if you keep it stored securely.

**Comment by heyambob** [comment] 2022-04-26 13:07
PS. you might wonder why I and some users messed it up in the first place, because we use a very long and complicated passphrase, didn't think that it's supposed to be something easy to type. Some warning when using this feature to create wallet, should reduce the rate of shooting our own foot.
