### ISSUE TITLE
i3wm and sparrow wallet

### ISSUE THREAD

**Issue by maximusmaximalistus** [sparrowwallet/sparrow#377] opened 2021-12-31 12:12 UTC
I like this wallet and I am testing it.
But since I use i3wm and i3wm is a tiling wm, there is a small issue with the top menu.

![image](https://i.imgur.com/jnf1VAG.png)
![image](https://i.imgur.com/svb7cdw.png)
![image](https://i.imgur.com/lwcKlmA.png)

All the other menus work fine. 
I created a wallet. Generated the seed and confirmed it. Every menu is working fine in the main window.
But in the top menu is not. 
I also tried to change the wm of my distro.
So I changed to Xfce and in there sparrow worked like it supposed to work. Everything was fine. All windows in the right place.
So this is just a small issue with i3wm. I think is because is a tiling wm. I tried to start sparrow as floating window but the problem with the top menu still happens.

**Comment by craigraw** [comment] 2022-01-03 07:23
Thanks, duplicate of #170.

**Closed by craigraw** 2022-01-03 07:23 UTC
