### ISSUE TITLE
Menu bar does not work in Qubes OS

### ISSUE THREAD

**Issue by WebDevPleb** [sparrowwallet/sparrow#813] opened 2023-01-22 13:46 UTC
When trying to click on 'File / View / Tools / Help' in the menu bar the drop down pops up for a split second and then disappears. When you hold left-click on the mouse the drop down will remain open but as soon as you let go it disappears.

I have tested on 2 different computers as well as in the Fedora, Debian, and Whonix VM's on Qubes OS. I have also tested the .deb, .rpm, and .AppImage installations all with the same result. 

To replicate, install Sparrow Wallet in Qubes OS
Click 'File / View / Tools / Help' 

As a temporary work around I have had success using Sparrow Terminal.

Thank you for the hard work on this amazing piece of software.

**Comment by craigraw** [comment] 2023-01-23 06:38
Thanks, duplicate of #170. It appears that a fix is in the works.

**Closed by craigraw** 2023-01-23 06:38 UTC
