### ISSUE TITLE
Donation button not showing invoice

### ISSUE THREAD

**Issue by jm9151821** [sparrowwallet/sparrow#1444] opened 2024-06-22 07:39 UTC
Attempted to donate but btc pay server throws an error on sparrow website

![image](https://github.com/sparrowwallet/sparrow/assets/32444279/c57a42e7-3acd-4918-8b09-7066cf7b8306)
attaching screenshot

**Comment by craigraw** [comment] 2024-06-25 10:40
I can't recreate this - I would guess from reading the error message that Kraken's rate service was temporarily down. Let me know if the issue is still present for you.

**Comment by craigraw** [comment] 2024-06-28 17:00
Closing this off as a temporary issue unrelated to sparrowwallet.com.

**Closed by craigraw** 2024-06-28 17:00 UTC
