### ISSUE TITLE
Error when trying to broadcast transaction

### ISSUE THREAD

**Issue by marnusminie** [sparrowwallet/sparrow#360] opened 2021-12-14 07:58 UTC
Been getting an error all morning when trying to send BTC. Please refer below for the relevant log file extract:

2021-12-14 09:55:54,616 ERROR [JavaFX Application Thread] c.s.s.t.HeadersController [null:-1] Error broadcasting transaction
com.sparrowwallet.sparrow.net.ServerException: the transaction was rejected by network rules.

non-mandatory-script-verify-flag (Signature must be zero for failed CHECK(MULTI)SIG operation)
[02000000000102a15d595c58a74f11f45d6d6e873ac3ff79bcd1a5125c8ddc5abe9b1ecd9792b10200000000fdffffff1a528c3f4e8e519957ed8a5c441a8bcfd8d0f3bbbc2d6edb0ed0874ac56ded370000000000fdffffff049e6000000000000016001417f72a23fb8c4895318a0e72e82ffb9980230d5435b109000000000017a914a0fb8594035d5c637fe4d05097cb7a159f5b290b87400c160000000000160014942db1e876b1a39e7dbaf81167ab1103e73ba2a93d273a0000000000160014b363ad19456f0072f7a08b8244575930b377a72602473044022045a23d5016fbf04e3a62d631969dec348f6d2f2edabf4a4b841d99e01d0fd7cc02204ff954dfdc1f40ad49342887a77115b2f51eb6dd8ef629732356bd5481e8f3900121034d3ce259ced0ef8ccb007705329130281dacb0ed129aa35fc8bc0659e2b5dfbe02473044022060922544bee5a8600f5175d5c097bc32c6e2adac65c6222a6b775fabdbd220a9022040e8c123478959261d9e5421bede2a5a6f059ffd8af17a8dfbf39d9705710a380121034d3ce259ced0ef8ccb007705329130281dacb0ed129aa35fc8bc0659e2b5dfbe6ae50a00]
	at com.sparrowwallet.sparrow@1.5.4/com.sparrowwallet.sparrow.net.ElectrumServer.broadcastTransaction(Unknown Source)
	at com.sparrowwallet.sparrow@1.5.4/com.sparrowwallet.sparrow.net.ElectrumServer.broadcastTransactionPrivately(Unknown Source)
	at com.sparrowwallet.sparrow@1.5.4/com.sparrowwallet.sparrow.net.ElectrumServer$BroadcastTransactionService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.5.4/com.sparrowwallet.sparrow.net.ElectrumServer$BroadcastTransactionService$1.call(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.sparrowwallet.sparrow.net.ElectrumServerRpcException: the transaction was rejected by network rules.

non-mandatory-script-verify-flag (Signature must be zero for failed CHECK(MULTI)SIG operation)
[02000000000102a15d595c58a74f11f45d6d6e873ac3ff79bcd1a5125c8ddc5abe9b1ecd9792b10200000000fdffffff1a528c3f4e8e519957ed8a5c441a8bcfd8d0f3bbbc2d6edb0ed0874ac56ded370000000000fdffffff049e6000000000000016001417f72a23fb8c4895318a0e72e82ffb9980230d5435b109000000000017a914a0fb8594035d5c637fe4d05097cb7a159f5b290b87400c160000000000160014942db1e876b1a39e7dbaf81167ab1103e73ba2a93d273a0000000000160014b363ad19456f0072f7a08b8244575930b377a72602473044022045a23d5016fbf04e3a62d631969dec348f6d2f2edabf4a4b841d99e01d0fd7cc02204ff954dfdc1f40ad49342887a77115b2f51eb6dd8ef629732356bd5481e8f3900121034d3ce259ced0ef8ccb007705329130281dacb0ed129aa35fc8bc0659e2b5dfbe02473044022060922544bee5a8600f5175d5c097bc32c6e2adac65c6222a6b775fabdbd220a9022040e8c123478959261d9e5421bede2a5a6f059ffd8af17a8dfbf39d9705710a380121034d3ce259ced0ef8ccb007705329130281dacb0ed129aa35fc8bc0659e2b5dfbe6ae50a00]
	at com.sparrowwallet.sparrow@1.5.4/com.sparrowwallet.sparrow.net.BatchedElectrumServerRpc.broadcastTransaction(Unknown Source)
	... 12 common frames omitted
Caused by: com.github.arteam.simplejsonrpc.client.exception.JsonRpcException: ErrorMessage{code=1, message=the transaction was rejected by network rules.

non-mandatory-script-verify-flag (Signature must be zero for failed CHECK(MULTI)SIG operation)
[02000000000102a15d595c58a74f11f45d6d6e873ac3ff79bcd1a5125c8ddc5abe9b1ecd9792b10200000000fdffffff1a528c3f4e8e519957ed8a5c441a8bcfd8d0f3bbbc2d6edb0ed0874ac56ded370000000000fdffffff049e6000000000000016001417f72a23fb8c4895318a0e72e82ffb9980230d5435b109000000000017a914a0fb8594035d5c637fe4d05097cb7a159f5b290b87400c160000000000160014942db1e876b1a39e7dbaf81167ab1103e73ba2a93d273a0000000000160014b363ad19456f0072f7a08b8244575930b377a72602473044022045a23d5016fbf04e3a62d631969dec348f6d2f2edabf4a4b841d99e01d0fd7cc02204ff954dfdc1f40ad49342887a77115b2f51eb6dd8ef629732356bd5481e8f3900121034d3ce259ced0ef8ccb007705329130281dacb0ed129aa35fc8bc0659e2b5dfbe02473044022060922544bee5a8600f5175d5c097bc32c6e2adac65c6222a6b775fabdbd220a9022040e8c123478959261d9e5421bede2a5a6f059ffd8af17a8dfbf39d9705710a380121034d3ce259ced0ef8ccb007705329130281dacb0ed129aa35fc8bc0659e2b5dfbe6ae50a00]}
	at simple.json.rpc.client@1.0/com.github.arteam.simplejsonrpc.client.builder.RequestBuilder.executeAndConvert(Unknown Source)
	at simple.json.rpc.client@1.0/com.github.arteam.simplejsonrpc.client.builder.RequestBuilder.execute(Unknown Source)
	at com.sparrowwallet.sparrow@1.5.4/com.sparrowwallet.sparrow.net.BatchedElectrumServerRpc.lambda$broadcastTransaction$7(Unknown Source)
	at com.sparrowwallet.sparrow@1.5.4/com.sparrowwallet.sparrow.net.RetryLogic.getResult(Unknown Source)
	... 13 common frames omitted

**Comment by craigraw** [comment] 2021-12-14 09:27
This suggests a signature error. Is this a Sparrow software wallet, or did a hardware wallet do the signing?

**Comment by marnusminie** [comment] 2021-12-14 10:05
Hi there

It is a Sparrow single sig wallet (no hardware wallet involved here).

I also tried to restart both the app and my computer, but the error kept
happening (four times in total)

Kind regards
[image: Untitled design (1).gif]
*Marnus Minie*
BitVice
| e: ***@***.***
| w: www.bitvice.io

**Comment by craigraw** [comment] 2021-12-14 10:35
Can you try running from source? Instructions in the project [README](https://github.com/sparrowwallet/sparrow/).

Also, what OS are you using?

**Comment by marnusminie** [comment] 2021-12-14 10:53
Really sorry but not technically-minded at all. I got to the part in the
README that said I could run it with ./sparrow, but I do not speak this
language :) Please help.

OS - Been using Windows 11 for some weeks now, and it has not given any
problems up until this morning.

Kind regards
[image: Untitled design (1).gif]
*Marnus Minie*
BitVice
| e: ***@***.***
| w: www.bitvice.io

**Comment by craigraw** [comment] 2021-12-14 18:26
No problem! Turns out this is a duplicate of #356, already fixed. Expect a release with the fix out shortly.

**Closed by craigraw** 2021-12-14 18:26 UTC

**Comment by craigraw** [comment] 2021-12-20 10:17
ICYMI - Sparrow v1.5.5 fixes this problem.

**Comment by marnusminie** [comment] 2021-12-20 10:46
It did seem to fix it thank you 🙏🏼
________________________________
