### ISSUE TITLE
Can't sign transaction with Ledger Nano X in sub accounts

### ISSUE THREAD

**Issue by bgaith** [sparrowwallet/sparrow#804] opened 2023-01-08 19:26 UTC
If I create a transaction in any account other than the default and try to sign it, nothing happens in the GUI.  Nothing gets sent to the Ledger.  In the background - hwi-2.1 process consumes 100% CPU of one core and has to be manually killed.

**Comment by bgaith** [comment] 2023-01-08 20:17
I also tried this with Ledger Nano S Plus.  Exact same result.

**Comment by bgaith** [comment] 2023-01-08 20:25
Just for clarity... I can sign transactions in acct#0 but not in any other account.

**Comment by craigraw** [comment] 2023-01-09 06:48
I've tried to reproduce this, without success. Using Ledger Nano X with app Bitcoin Testnet version 2.0.4. Sparrow v1.7.1 using account #1 with derivation path `m/84'/1'/1'`. The Ledger signs as normal. 

Is your firmware up to date? Do you see any errors in the Sparrow log? Help menu.

**Comment by bgaith** [comment] 2023-01-09 15:09
Yes, firmware is up to date on both Nano X and Nano S+.  I've tested on three different linux distros and two versions of Sparrow - v1.7.1 and v1.6.6.  Same result on every test case.

Nothing is logged until I kill the hwi-2.1 process.  This shows up after the kill:


2023-01-09 08:25:49,091 ERROR [JavaFX Application Thread] c.s.s.c.DevicePane [null:-1] Signing Error: Not a JSON Object: null
java.lang.IllegalStateException: Not a JSON Object: null
	at com.google.gson@2.8.6/com.google.gson.JsonElement.getAsJsonObject(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.1/com.sparrowwallet.sparrow.io.Hwi.signPSBT(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.1/com.sparrowwallet.sparrow.io.Hwi$SignPSBTService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.1/com.sparrowwallet.sparrow.io.Hwi$SignPSBTService$1.call(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by craigraw** [comment] 2023-01-10 17:01
Clearly HWI is getting hung up for some reason. What's strange is that
1. It seems to only happen for subaccounts on the Ledger
2. It seems to be local for your system

Do you have another computer around to see if the problem happens there as well?

Otherwise, it may be that you'll need to debug this by using `hwi` directly - see https://github.com/bitcoin-core/HWI. To do this, you'll need to call `hwi enumerate` to get your device details, and then `hwi -t <type> -d <path> signtx <psbt>` with the PSBT (you can retrieve the Base64 for it from the Sparrow File menu).

**Comment by bgaith** [comment] 2023-01-10 22:33
I have tested with two different computers.  Same result.  I could test on a third PC running windows...  I really want this running on Linux.

./hwi.py enumerate
[{"type": "ledger", "model": "ledger_nano_x", "label": null, "path": "1-2:1.0", "error": "Could not open client or get fingerprint information: unsupported hash type ripemd160", "code": -7}]

./hwi.py -t ledger -d 1-2:1.0 signtx CCM.psbt.txt
{"error": "Incorrect padding", "code": -13}

**Comment by craigraw** [comment] 2023-01-11 08:47
> ./hwi.py -t ledger -d 1-2:1.0 signtx CCM.psbt.txt {"error": "Incorrect padding", "code": -13}

Instead of providing it as a file, specify the PSBT as a string copied out of that file.

`./hwi.py -t ledger -d 1-2:1.0 signtx 'cHNid...'`

**Comment by bgaith** [comment] 2023-01-11 18:12
I created a new smaller PSBT.

As text I get
bash: ./hwi.py: Argument list too long

As a file I get 
{"error": "invalid magic", "code": -5}

**Comment by craigraw** [comment] 2023-01-12 06:21
Ok, you can also specify the command arguments this way:
```
./hwi.py --stdin
-t ledger -d "1-2:1.0" signtx "cHNid..."
```

Press Enter twice at the end. This should get around the `Argument list too long` problem.

**Comment by bgaith** [comment] 2023-01-13 00:22
I did some further testing with other sub accounts.  Apparently I was mistaken...  Every account except the account of interest can sign a transaction.  I've drained the bad account using a cold card.  I think we can close this.  

Thanks for your support Craig.  I'm a huge fan of the product.

**Comment by craigraw** [comment] 2023-01-13 05:29
Ok, closing this off. It remains a mystery...

**Closed by craigraw** 2023-01-13 05:29 UTC
