### ISSUE TITLE
[Feature Request] Aliases for Private Electrum Servers in Server Preferences

### ISSUE THREAD

**Issue by RequestPrivacy** [sparrowwallet/sparrow#681] opened 2022-09-08 08:54 UTC
Sparrow saves recent connections e.g. to a private electrum server in the preferences section under "Server". 

URLs and hostnames are displayed in plain text. So if you have a electrum server at home and want to use a local connection, the preference section may save the `IP` of the server. If your away from your home network you might wanna connect to you server via its hidden service. Sparrow saves and displays the `hostname.onion`.

But if you want to change your server while being in a public place I don't want everybody to see my local servers `IP` (minor issue as home networks are generally shielded by a firewall) or my `hostname.onion` (slightly greater issue but hard for people to remember the long address).

Still, both would benefit if one could hide them behind a manually chosen alias which maps internally to a saved `IP` / `hostname`.

Further benefit: if you have multiple servers (say 1 electrs, 1 fulcrum, for both onion addresses & a couple of others from friends) you could identify them better with hostname aliases instead of remembering whose sever is `reallylonghostname1.onion` vs another saved `reallylonghostname2.onion`.

An easy switch or menu entry to rapidly change between different aliases (and therefore servers) would be another cool feature.

Think:

HOME -> elctrs IP 192.168.1.2 with ssl and its corresponding certificate
HIDDEN_ELECTRS -> electrs hostname.onion witout ssl

where the `change server` menu entry just displays HOME and HIDDEN_ELECTRS and once chosen the Sparrow server settings change to the underlying mapped preferences.

**Comment by craigraw** [comment] 2022-09-12 13:49
This is actually a duplicate of #462 (although better motivated here!). 

Added in 1f676927. Sparrow now contains support for configuring server aliases (so that URLs are hidden in the interface), and switching servers via the Tools menu.

<img width="862" alt="Screenshot 2022-09-12 at 15 47 18" src="https://user-images.githubusercontent.com/862166/189670879-67ff6bb3-76cc-4fe9-a0ca-5af2ae9a7cb1.png">

<img width="792" alt="Screenshot 2022-09-12 at 15 46 57" src="https://user-images.githubusercontent.com/862166/189670907-c6a8bb0a-1dc5-4d8f-8108-98a38fb82172.png">

<img width="424" alt="Screenshot 2022-09-12 at 15 48 03" src="https://user-images.githubusercontent.com/862166/189670925-a26fbe92-4670-4e65-a994-898ff498b750.png">

**Closed by craigraw** 2022-09-12 13:49 UTC

**Comment by RequestPrivacy** [comment] 2022-09-13 06:42
Awesome implementation, thank you!
