### ISSUE TITLE
Feature suggestion: Wallet Summary View

### ISSUE THREAD

**Issue by sicbitm** [sparrowwallet/sparrow#1063] opened 2023-08-14 14:19 UTC
Every major software wallet (i.e. Trezor suite, ledger live, bitbox app...) has a summary screen with the sum of the total balance of all accounts in the wallet.

The more advanced you make use of bitcoin, the more accounts you use, the more you need a summary screen.

It would be great to have a single screen with a glimpse of the full wallet, with all the imported accounts.

Thanks

**Comment by craigraw** [comment] 2023-08-14 16:00
Duplicate of #438. Just implemented!

**Closed as completed by craigraw** 2023-08-14 16:00 UTC
