### ISSUE TITLE
Incorrect balance, requires refresh every time

### ISSUE THREAD

**Issue by btcsessions** [sparrowwallet/sparrow#297] opened 2021-11-01 17:48 UTC
I've been noticing upon opening Sparrow it will often show an incorrect balance (much higher than my real balance). This is accompanied by a "new transactions" notification, informing me of my updated balance. When checking the UTXOs in my wallet, they are correct but not reflected properly in the Balance field of the Transactions screen.

Upon using view, refresh wallet, it will be corrected to proper value. Restarting the wallet will often result in the same error and necessary correction.

I am running 1.5.2 on a Mac with OSX 11.6. This error was present in the previous version of Sparrow as well.

**Comment by craigraw** [comment] 2021-11-02 08:25
This is almost certainly caused by a faulty server. Are you using Electrs? If so make sure you are using the latest version (>+ v0.9.0).

**Comment by craigraw** [comment] 2021-11-03 09:28
I've had another report of this behaviour, and asked the user to go offline using the toggle in the lower right before restarting Sparrow. When this was done, the balance did not change, indicating this is likely a server issue. The user in this case was using MyNode (Electrs version unclear).

It would be useful to see a copy of the Loading Log (View menu) on startup when the issue occurs - it may reveal something that can be passed to the Electrs project maintainers.

**Comment by Transisto** [comment] 2021-11-11 05:13
I'm just having somewhat a similar problem.

The different derivation account don't agree with each others.

I send all the Deposit to Premix+Badbank
But deposit is still processing an incoming transaction sent earlier.
For example if Deposit account was 2 BTC, after the last deposit of 0.1 it's now 1.2, A seemingly arbitrary number.

The Premix tab is the only one that shows the big transaction.


Logs have about 30 of these, 

2021-11-10 23:45:08,456 WARN [JavaFX Application Thread] c.s.s.AppServices [null:-1] Failed to fetch wallet history from ssl://electrum.blockstream.info:50002, reconnecting to another server...
2021-11-10 23:45:08,456 ERROR [ElectrumServerReadThread] c.s.s.n.TcpTransport [null:-1] Error opening socket inputstream
java.net.SocketException: Socket is closed
	at java.base/sun.security.ssl.SSLSocketImpl.getInputStream(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.TcpTransport.readInputLoop(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.ElectrumServer$ReadRunnable.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2021-11-10 23:49:03,973 WARN [JavaFX Application Thread] c.s.s.w.TransactionEntry [null:-1] TransactionEntry .........for wallet YapLock_BC1-Deposit missing child for input null on output .......... :33
2021-11-10 23:49:03,974 WARN [JavaFX Application Thread] c.s.s.w.WalletTransactionsEntry [null:-1] Removing and not notifying incomplete entry

**Comment by Transisto** [comment] 2021-11-11 05:26
I restarted the wallet and connected to different servers.
The wallet now show this -2 but as a -1, If I expand it in "Transaction" tab it only show 47 UTXO while the Tx has about 80.

**Comment by craigraw** [comment] 2021-11-11 06:00
@Transisto this is very clearly a server issue. The log message `Removing and not notifying incomplete entry` is Sparrow saying that the information it has received from the server does not make sense. Sparrow does its best to try to recover from this situation, but ultimately the server is the source of all transaction information, so when it cannot deliver that reliably Sparrow cannot show the wallet history accurately.

**Comment by Transisto** [comment] 2021-11-11 06:27
What if Sparrow checked if the transactions are valid with it's txid before adding what seems like partial transaction to the transaction history resulting in off-balances?

**Comment by craigraw** [comment] 2021-11-11 06:36
That's effectively what it's trying to do with the `Removing and not notifying incomplete entry` logic. Ultimately though the wallet balance is still wrong if the removed entry was in fact a genuine (but incompletely reported) wallet transaction.

**Comment by craigraw** [comment] 2021-12-02 13:49
Closing this off.

**Closed by craigraw** 2021-12-02 13:49 UTC
Labels: bug, documentation, wontfix
