### ISSUE TITLE
[Signing Error] Can't sign Taproot transaction using Trezor One device - "Cannot sign external inputs"

### ISSUE THREAD

**Issue by twofaktor** [sparrowwallet/sparrow#695] opened 2022-10-01 15:35 UTC
### Issue

Hello,

I want to withdraw the amount of my Taproot wallet balance using Trezor One, but I can't sign the transaction because It shows me an error in the final step of the sign. It shows me "Signing Error" --> [Cannot sign external inputs]

Secondly, I can see another strange warning in the UTXOS section, in concrete in a UTXO, it says "Duplicate address --> Freeze?" I don't know if this is related to the signing issue

### Setup used

- Trezor One firmware: 1.11.2 Bitcoin-only version
- Sparrow Wallet 1.6.6
- Windows 10 Pro 21H2 Windows Feature Experience Pack 120.2212.4180.0

All in the latest version updated

### Logs related

```
2022-10-01 17:16:23,914 ERROR [JavaFX Application Thread] c.s.s.c.DevicePane [null:-1] Signing Error: Cannot sign external inputs
com.sparrowwallet.sparrow.io.SignTransactionException: Cannot sign external inputs
	at com.sparrowwallet.sparrow@1.6.6/com.sparrowwallet.sparrow.io.Hwi.signPSBT(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.6/com.sparrowwallet.sparrow.io.Hwi$SignPSBTService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.6/com.sparrowwallet.sparrow.io.Hwi$SignPSBTService$1.call(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

### Screenshots:

![Captura12312312](https://user-images.githubusercontent.com/89636253/193416728-75725230-80ac-4b71-bfee-1282ff5ddd7d.PNG)
![Captura32423423](https://user-images.githubusercontent.com/89636253/193416729-37f59b21-0b81-4cae-822d-72c17f8d6b55.PNG)
![Captura534534](https://user-images.githubusercontent.com/89636253/193416913-a8d38e11-9eba-43b5-8fdc-5e276a2a7036.PNG)

I would like to be able to withdraw, do you know why this is happening?

**Comment by craigraw** [comment] 2022-10-03 06:49
> I want to withdraw the amount of my Taproot wallet balance using Trezor One, but I can't sign the transaction because It shows me an error in the final step of the sign. It shows me "Signing Error" --> [Cannot sign external inputs]

The HWI library [notes a limitation](https://github.com/bitcoin-core/HWI/blob/e731395bde13362950e9f13e01689c475545e4dc/hwilib/devices/trezor.py#L360) of the Trezor - ```Transactions containing Taproot inputs cannot have external inputs.```

It would appear that the Trezor is unable to determine that one of the inputs to the transaction is from this wallet. Are you able to sign a transaction with a single input, to try isolate the cause?

> Secondly, I can see another strange warning in the UTXOS section, in concrete in a UTXO, it says "Duplicate address --> Freeze?" I don't know if this is related to the signing issue

It's unrelated. This is a small amount sent to an already used address, which might indicate a dust attack. Sparrow suggests freezing it.

**Comment by twofaktor** [comment] 2022-10-03 07:35
> > I want to withdraw the amount of my Taproot wallet balance using Trezor One, but I can't sign the transaction because It shows me an error in the final step of the sign. It shows me "Signing Error" --> [Cannot sign external inputs]
> 
> The HWI library [notes a limitation](https://github.com/bitcoin-core/HWI/blob/e731395bde13362950e9f13e01689c475545e4dc/hwilib/devices/trezor.py#L360) of the Trezor - `Transactions containing Taproot inputs cannot have external inputs.`
> 
> It would appear that the Trezor is unable to determine that one of the inputs to the transaction is from this wallet. Are you able to sign a transaction with a single input, to try isolate the cause?

Did you mean select only one UTXO? I have 4 UTXOs, I tried to submit by selecting each UTXO individually and It failed the same way, also, on some tries, I saw this new error, If it's any help:

![Captura43667879](https://user-images.githubusercontent.com/89636253/193523653-db669921-2eea-4407-ab51-9e65a568af47.PNG)

I tried also in an old version of Sparrow and it also showed me this new error, If it's any help:

![Captura23142131](https://user-images.githubusercontent.com/89636253/193523891-2966b4bd-13ae-4c19-9f1f-edc275c443f4.PNG)

**Comment by craigraw** [comment] 2022-10-03 07:55
Is the Taproot wallet using the standard derivation path of `m/86'/0'/0'`?

**Comment by twofaktor** [comment] 2022-10-03 08:00
> Is the Taproot wallet using the standard derivation path of `m/86'/0'/0'`?

yeah, of course

![tempsnip](https://user-images.githubusercontent.com/89636253/193528276-ead6c611-758a-4b13-b8c9-aff17eec0771.png)

**Comment by craigraw** [comment] 2022-10-03 08:13
Can you recreate this error using a testnet wallet? The error message is being created by HWI, which is matching on the master fingerprint and the taproot keypath internal key. For one of these, the value returned by the Trezor does not match the value produced by Sparrow in the PSBT. I assume you are not using a passphrase - it's probably the only way to change these values on the device.

**Comment by twofaktor** [comment] 2022-10-03 08:43
I don't have a testnet wallet, maybe I could do it in the medium term, I don't know. Meanwhile, this problem can not be solved before that? I need to withdraw the balance ASAP

BTW: I'm using a passphrase, look at this:

![Captura4575676](https://user-images.githubusercontent.com/89636253/193535973-bbc5d931-38d2-4109-abc1-df1d660e2c56.PNG)

**Comment by craigraw** [comment] 2022-10-03 08:57
> I don't have a testnet wallet, maybe I could do it in the medium term

It's quick to set one up. You can restart Sparrow in testnet using the Tools menu, import the Trezor and receive coins from a testnet faucet.

>  I'm using a passphrase, look at this

An incorrect passphrase may cause this, so that's the most likely thing to look at.

**Comment by craigraw** [comment] 2022-10-03 08:59
Try creating a new wallet in Sparrow, and reimporting the Trezor.

**Comment by twofaktor** [comment] 2022-10-03 10:38
> Try creating a new wallet in Sparrow, and reimporting the Trezor.

Yes, I am waiting for a transaction to be confirmed to a new Taproot wallet, oddly enough, I used the same passphrase of the old wallet but this time Sparrow was forwarded to me to a different wallet and the wallet and transaction history is empty (there are not any amount inside). I think you have reason, maybe I was wrong to save my passphrase :(
I confirm with you when the transaction is confirmed and try to withdraw the new wallet, but this looks bad... :(

**Comment by twofaktor** [comment] 2022-10-03 14:13
I confirm, in the new wallet I could sign the transaction of withdrawal... I guess I made a mistake when saving my passphrase, now I will have to propagate a bounty to recover this...😓 good thing it's not about much...for now...my first time contributing to the shortage 👨‍🦲

- Could Sparrow give us a more exact reason for the problem?
- Any way to find out the forgotten passphrase from the wallet file? I have the password for the wallet file and the seeds.

Thanks

**Comment by craigraw** [comment] 2022-10-03 14:24
> Could Sparrow give us a more exact reason for the problem for the next release?

It's actually HWI's error message (an internal library Sparrow uses). Unfortunately there is no way to tell if the "external input" is genuinely external, or the result of a changed seed.

> Any way to find out the forgotten passphrase from the wallet file? I have the password for the wallet file and the seeds.

No - Sparrow doesn't store this. This is kinda the point of using a passphrase (something you have, plus something you know). Passphrases are powerful but dangerous.

I'll close this off now. Good luck with finding the right passphrase. I should be guessable if you made a typo. If so, it helps to take it slow, be methodical and don't give up.

**Closed by craigraw** 2022-10-03 14:24 UTC
