### ISSUE TITLE
Sparrow wallet keeps gives error when connecting to Bitcoin Core on Mac.

### ISSUE THREAD

**Issue by Geeibiza** [sparrowwallet/sparrow#1053] opened 2023-08-05 15:19 UTC
I have Bitcoin core version v25.0.0 running on a MacBook Air 2017 / MacOS Monterey ... Node is installed on External HD Sandisk 1TB and the Port 8333 forwarded on router ... Incoming and outgoing is working. The node Node is showing up on Bitnodes.com ... 

They are both on a local machine so I used the instructions from Sparrow: https://sparrowwallet.com/docs/connect-node.html When I install the Sparrow wallet I followed the instructions to add server=1 to the bitcoin.conf. My Bitcoin core is installed on an external ssd and I change that aswell. In the settings as written.  

So when I start the Sparrow wallet and press Test connection it gives me the follow error.

![Screenshot 2023-08-05 at 16 52 26](https://github.com/sparrowwallet/sparrow/assets/67664045/0769d80b-057c-41cf-9a69-96cb9e58a1d3)
![Screenshot 2023-08-05 at 15 49 54](https://github.com/sparrowwallet/sparrow/assets/67664045/016f9aef-0126-4d81-a769-45b0d998d7b6)

This are the 2 error I keep getting what ever I try and what ever I do ... please help

**Comment by craigraw** [comment] 2023-08-07 07:24
`Wallet file verification failed` is an error produced by Bitcoin Core. I believe it occurs when the data folder is located on another drive (possibly due to another file system). That said, let's investigate further:

1. Please post the full related exception from the Sparrow log file. You can find it using the Help menu. You can also just post the entire file here.
2. What is the result of calling `bitcoin-cli listwalletdir`?

**Comment by Geeibiza** [comment] 2023-08-08 14:52
[sparrow.log](https://github.com/sparrowwallet/sparrow/files/12292705/sparrow.log)

**Comment by Geeibiza** [comment] 2023-08-08 14:59
This is the log file I hope you can help me.

this is  the contents of /Volumes/Bitcoin? Specifically, is the cormorant wallet folder present? YES

![Image 08-08-2023 at 16 58](https://github.com/sparrowwallet/sparrow/assets/67664045/c96f6c76-20f2-40c0-9ad0-5894bf04ae6e)

**Comment by craigraw** [comment] 2023-08-09 09:26
That's interesting - it looks like we might have some kind of Bitcoin Core bug. Note that `listwalletdir` is returning the other two wallets, but not `cormorant`. Some further questions:

- In the screenshot above, can you expand the file tree show the contents of the `cormorant` folder, and the `GeeBitcore` folder?
- What is the file system on the external drive (Sandisk 1TB)? Disk Utility should be able to tell you.

It may be that there is some kind of error creating the wallet database in Core, although I can't see anything in the log. Try the following:
1. Close Sparrow and stop Bitcoin Core
2. Delete the `cormorant` folder in the Bitcoin dir
3. Restart Bitcoin Core and then Sparrow
4. Sparrow will try to recreate the `cormorant` wallet in Core when it tries to connect. Watch sparrow.log to see if any new lines appear showing an error, and post them here if so.
5. See if the contents of the `cormorant` folder look the same as before, and what `listwalletdir` returns.

**Comment by Geeibiza** [comment] 2023-08-09 12:47
Ok now I restart and I make a new wallet and everything seems to work fine. But this happens always when I delete the cormorant dir. Now I try to close the computer and restart again because then it gives me the error that the dir already exists.

**Comment by Geeibiza** [comment] 2023-08-09 16:08
I got stuck here ... same as last time ... feels like Groundhog Day hahaha ... please help

**Comment by craigraw** [comment] 2023-08-10 11:49
Thanks for the additional info. It might not feel like it, but we are getting closer. It's now clear that Bitcoin Core is successfully creating the `cormorant` database, but then does not recognise it on restart at a later date. The question now is why. The Core code does do certain checks on the `wallet.dat` file when running `listwalletdir`, so it appears that for some reason these checks are failing.

Please could you attach `wallet.dat` and `wallet.dat-journal` to this issue (or alternatively email them to craig at sparrowwallet.com). If you have not loaded any wallets in Sparrow, there will be no privacy-sensitive data in these files.

**Comment by Geeibiza** [comment] 2023-08-10 12:58
[Archive.zip](https://github.com/sparrowwallet/sparrow/files/12312930/Archive.zip)

**Comment by craigraw** [comment] 2023-08-10 14:52
Thanks. And to be clear, when you run `listwalletdir` now you don't see `cormorant` in the output, even though the cormorant directory is present with these files in it?

**Comment by Geeibiza** [comment] 2023-08-11 03:05
Yes I see it 
![Image 11-08-2023 at 05 05](https://github.com/sparrowwallet/sparrow/assets/67664045/1b3bc9f0-0d66-4613-b1fc-ddd5090d90ac)

**Comment by craigraw** [comment] 2023-08-11 07:33
Have you restarted the computer yet? You mentioned previously
> The problem occurs when I restart the computer because then it gives me the error that the cormorant folder already exists.

What I am trying to determine is that `cormorant` is not present in `listwalletdir` when you experience the error in Sparrow.

**Comment by Geeibiza** [comment] 2023-08-11 11:24
Yes I restart the computer and the directory is there in listwallet . I start sparrow and it does not connect ... then I say test connection and it gives me the error that the cormorant directory already exists.

**Comment by craigraw** [comment] 2023-08-14 08:13
Ok, I've made a change in bebd7eeb that should fix this for the apparent Bitcoin Core bug where an empty result is returned from `listwalletdir`, even when there are loaded wallets returned from `listwallets`.

Since I can't reproduce the issue, I'd appreciate it if you could test the fix by installing this build which contains it: https://github.com/craigraw/beta/releases/tag/1.7.9-core-listwalletdir

**Comment by craigraw** [comment] 2023-08-17 07:19
@Geeibiza Any progress on giving this a try?

**Comment by craigraw** [comment] 2023-08-29 11:19
@Geeibiza can this be closed?

**Comment by Geeibiza** [comment] 2023-09-01 11:43
I have bin in Hospital with a virus this weekend I will try it sorry

**Comment by craigraw** [comment] 2023-09-01 14:51
No stress. This functionality has been released in Sparrow v1.7.9. Get better first and test it later.

**Comment by Geeibiza** [comment] 2023-09-01 16:18
@craigraw wow it worked ... great great job fam ...Oh my God ! So happy thank you so much 
What was the problem ???

**Comment by craigraw** [comment] 2023-09-03 08:21
Great! Thanks for verifying. It turns out Bitcoin Core has a small bug with it's `listwalletdir` command, where it does not list wallets on remote volumes sometimes, even as it successfully loads them. Sparrow now checks the output of both commands before trying to create a wallet.

**Closed by craigraw** 2023-09-03 08:21 UTC
