### ISSUE TITLE
Wallet Labels are not saved | 1.7.1 | OSX (Apple M1/M2)

### ISSUE THREAD

**Issue by confettimoney** [sparrowwallet/sparrow#778] opened 2022-12-14 18:33 UTC
Hope you could help with the following. 

For some of my wallet files I have the following strange behavior:

1) I open the wallet (.mv.db) and retrieve new TXs
2) I adjust the wallet labels
3) I close the mv.db file
4) I open it again
5) It again needs to retrieve the same TXs as retrieved in step 1) and the wallet labels are gone

Looking in the folder where my wallet files are stored I observe that for the wallets with this strange behavior there is no mv.db.tempFile (anymore?), while for the other wallets which are working properly there is.

Any thoughts on why this is happening and how to fix?

Thanks,

CM

**Comment by craigraw** [comment] 2022-12-15 05:35
What version of Sparrow?

**Comment by confettimoney** [comment] 2022-12-15 10:08
Hi Craig,

1.7.1 for OSX (Apple M1/M2) i.e. latest version.

**Comment by craigraw** [comment] 2022-12-15 10:39
What server are you connecting to? Sparrow should not "need to retrieve the same TXs as retrieved in step 1". There's something strange going on if it is. 

What happens if you take Sparrow offline using the bottom right toggle and then restart it? Are labels still lost?

**Comment by confettimoney** [comment] 2022-12-15 15:39
Thanks Craig. I am connecting to an Electrum Server (electrs). 

I performed the following steps:

1. Opened the wallet and retrieve the new TXs
2. Gave the TXs the correct label
3. Switched off the connection with my Electrum Server by switching off the toggle at the right bottom
4. Closed the wallet
5. Reopened the wallet

The TXs that I had labelled at step 2. are now missing at all and are obviously not retrieved (again), since I still have the toggle switched off. Please note this issue only persists for some of my wallets, while for others I have no whatsoever. 

Furthermore, I made an export of this wallet, i.e., 1:1 copy of this wallet, and tried to reproduce the issue. For this 1:1 copy I strangely do not encounter this issue anymore. What's striking is that the file size of this 1:1 copy is also significantly smaller in size (~40%) than the original one. Could it be that the original wallet file somehow got irreparably damaged/corrupted and the only fix if that happens is to export the information inside this wallet into a new version via the "Export Wallet" functionality within Sparrow?

**Comment by craigraw** [comment] 2022-12-16 11:49
Are there any relevant errors in the Sparrow log? (Help menu).

**Comment by confettimoney** [comment] 2022-12-19 10:03
I did some additional tests on my side. When using the wallet file from within my Downloads folder, there is no unusual behavior. Everything works as expected.

However, when I try to save the wallet files on a mounted decrypted volume, I observe errors like:

General error: "org.h2.mvstore.MVStoreException: Could not sync file /Volumes/XXX/YYY/ZZZ.mv.db [2.1.214/2]" [50000-214]

ERROR [H2-save] h2database [null:-1] ZZZ:database flush
org.h2.message.DbException: General error: "org.h2.mvstore.MVStoreException: Could not sync file /XXX/YYY/ZZZ.mv.db [2.1.214/2]" [50000-214]

Any thoughts on why this synchronization to the mounted decrypted volume causes these errors?

**Comment by Mistersx12** [comment] 2022-12-19 12:37
Ensure that the mounted decrypted volume is correctly formatted and mounted. Check the file permissions on the mounted decrypted volume to ensure that the wallet has sufficient permissions to write to the file. Check the disk and file system for errors or corruption. You can do this by running a disk check or file system check on the mounted decrypted volume. Make sure that the mounted decrypted volume has sufficient free space to accommodate the wallet file. If none of these steps resolve the issue, it may be helpful to try running the wallet on a different volume or on a different machine to see if the problem persists.

**Comment by craigraw** [comment] 2022-12-24 05:16
It's fairly clear (from reading the database code) that this error was caused by an IO error writing to the mounted volume, so I'm going to close this off.

**Closed by craigraw** 2022-12-24 05:16 UTC
