### ISSUE TITLE
Add option to send amount in USD.

### ISSUE THREAD

**Issue by zerotrust-community** [sparrowwallet/sparrow#1149] opened 2023-11-04 15:03 UTC
Hi, every time when i want to send like 100 in USD, i need to search like `100 usd to btc` , it's very uncomfortable. can you add this option in send tab?
![image](https://github.com/sparrowwallet/sparrow/assets/148634618/3a83c531-26b9-41f6-9cd0-4f5e32d05e7c)
very great if you add same option for fee. Thanks.

**Comment by RequestPrivacy** [comment] 2023-11-04 15:21
Please god no! 

Imagine you try to send 100 USD. Where does the exchange rate come from that sparrow should use for converting your input to btc? What happens if there is currently a lot of volatility. What happens if there's a glitch which serves a wrong exchange rate? You're comfortable loosing sats because of this?

To whom do you want to send USD? At which exchange rate? It makes no sense to base sends in USD.

You send BTC, not USD (or other fiats). Therefore the only reasonable input should be BTC...

**Comment by zerotrust-community** [comment] 2023-11-04 17:15
so, why this options is realised in other wallets? like electrum wallet on example:
i have 2 filed, i can enter btc or usd.
![image](https://github.com/sparrowwallet/sparrow/assets/148634618/69daa0fb-2f47-4346-b0ac-f7ad976cfce1)
i think that user can decide by itself if it's need for him, but not need to don't give this options

**Comment by zerotrust-community** [comment] 2023-11-04 17:21
safepal same options:
![image](https://github.com/sparrowwallet/sparrow/assets/148634618/2e13e17d-64fc-48d0-9de0-58f3512659a3)

**Comment by zerotrust-community** [comment] 2023-11-04 17:27
safepal:
![image](https://github.com/sparrowwallet/sparrow/assets/148634618/2e13e17d-64fc-48d0-9de0-58f3512659a3)
exodus:
![image](https://github.com/sparrowwallet/sparrow/assets/148634618/cbb604c9-0a87-470f-9a08-fcab16ae4cce)
feather wallet:
![image](https://github.com/sparrowwallet/sparrow/assets/148634618/2b26ef89-fdb0-462c-9464-30814756ffec)

**Comment by RequestPrivacy** [comment] 2023-11-04 17:29
I know that there are wallets with this option but I'm not sure what you try prove by providing the examples? That it's technically feasible? Sure, but you have to trust these wallets that all the things I mentioned are being taken care of.

And even if they have a proper technical implementation think about it: the guy who you owe the $5.73 in one of the screenshots told you to send $5.73 in BTC. But what happens if he applies another exchange rate than the wallet you used to send out?

**Comment by zerotrust-community** [comment] 2023-11-04 17:31
i just want to have this option, when i want to send for someone money, i can ask for him exact amount in BTC. done.

**Comment by RequestPrivacy** [comment] 2023-11-04 17:36
> when i want to send for someone money

But your wallet can't send or receive USD. This distinction is important imho. Maybe somewhere in the wallet there could be an converter to easily show exchange rates and get the sats amount based on an exchange rate.

But I as a user am strictly against "sending" an USD "based" btc amount i.e. implementing this in the payments flow...

**Comment by zerotrust-community** [comment] 2023-11-04 17:41
Let author decide if will implement this functionality, and end user wiil decide do send money or not using this "risky" methot.

**Comment by craigraw** [comment] 2023-11-05 10:52
Duplicate of #147.

**Closed by craigraw** 2023-11-05 10:52 UTC
