### ISSUE TITLE
Sparrow 1.6.0 is not displaying Fiat currency at MacBook Air M1

### ISSUE THREAD

**Issue by maxmanbtc** [sparrowwallet/sparrow#448] opened 2022-03-03 15:07 UTC
I just upgraded to ver. 1.6.0 at my MacBook Air with M1 and macOS Monterey 12.0.1 and now the fiat currency is not showed.
In Preferences there is no pssibilty to choose fiat currency, it's greyed out.

**Comment by craigraw** [comment] 2022-03-04 09:26
Duplicate of #451, will likely be fixed by 02e0fd1.

**Closed by craigraw** 2022-03-04 09:26 UTC
