### ISSUE TITLE
Two wallets on same Nano S, last transaction missing

### ISSUE THREAD

**Issue by super-e** [sparrowwallet/sparrow#555] opened 2022-05-20 10:09 UTC
Version Sparrow 1.6.4
Environment: Windows 11
Server: Private Electrum (Connected to electrs/0.9.3 on protocol version 1.4 - Batched RPC enabled)
Policy Type: Single Signature
Script Type: Native Segwit
Script Policy: wpkh(LedgerNanoS)

Issue: I have 2 wallets linked to the same Nano S, same master fingerprint, same derivation path. They see all the same transactions, excepting one. The last transaction from 10 days ago on one of the two wallets is missing. There maybe should be a button to reload the whole transaction history?

How to reproduce: Not really sure

Expected behaviour: The two wallets should show exactly the same balance and transactions.

Thanks

**Comment by craigraw** [comment] 2022-05-20 10:44
> There maybe should be a button to reload the whole transaction history?

There is actually. View menu > Refresh Wallet

It's probably an Electrs related issue, but a wallet refresh should sort it out. Check your loading log (Transactions tab) to ensure there are no failures.

**Comment by super-e** [comment] 2022-05-20 12:23
Hi, sorry it's embarassing I did not notice the Refresh button, I am new to Sparrow (loving it, btw). Unfortunately it did not solve the problem, actually made it worse, more transactions missing between the two.

I tried with public Electrum server but still finding discrepancies between the two wallets. A Core public server in the end worked fine. So I have a work-around, but there might be some issues in Electrum protocol.

**Comment by craigraw** [comment] 2022-05-20 14:01
> So I have a work-around, but there might be some issues in Electrum protocol.

The Bitcoin Core server option actually uses the Electrum protocol too, leveraging BWT behind the scenes to provide an Electrum interface to the Bitcoin Core wallet. I am confident the issue lies with the servers you were connected to (Electrs in particular has these kind of problems, but sometimes public servers can be spotty too). Missing transactions can also be caused by an insufficient gap limit, but if the problem is now sorted it doesn't seem like was the case here.

I am going to close this off as a server issue - the Electrum server client in Sparrow has been very heavily tested over many years and is unlikely to be the cause of the problem, especially given the problem was resolved using it. Consider upgrading to ElectrumX or Fulcrum instead of using Electrs - see the Sparrow documentation for more details on the performance and reliability benefits.

**Closed by craigraw** 2022-05-20 14:01 UTC
