### ISSUE TITLE
Make UI more compatible for small resolutions

### ISSUE THREAD

**Issue by itscz-org** [sparrowwallet/sparrow#1553] opened 2024-12-05 12:08 UTC
The padding of the buttons on the left side is far too high. I have serious problems using Sparrow on HD or smaller resolutions. Can you please add an option to reduce that padding or shrink it dynamically while resizing the window. By now, vertical resize is limited to the large left menu bar.

Thanks

**Comment by craigraw** [comment] 2024-12-09 11:06
What is your maximum vertical resolution? There has already been considerable effort into making Sparrow usable on very small screens, but taking this further is very difficult mainly due to the vertical space requirements of the Send tab, which is the actual limiting factor, not the navigation bar.

**Comment by itscz-org** [comment] 2024-12-09 11:29
For me it looks like its the nav bar and i face problems in 1440p. The window is larger than that and not fully visible. I guess its the DPI settings that cause this problem. On my primary screen (laptop), the Windows scaling setting is at 175%. Screenshot attached.
![Zwischenablage_12-09-2024_01](https://github.com/user-attachments/assets/0c7e002b-d3fd-4e8a-95bc-2695431ecfb0)

**Comment by craigraw** [comment] 2024-12-09 11:34
Have you tried https://sparrowwallet.com/docs/faq.html#sparrow-is-too-big-for-my-screen

**Comment by itscz-org** [comment] 2024-12-09 11:45
I tried setting it to 100% by the env variable. It fits to the screen then, but there is a reason i use 175%... with the 100% setting, the font height in Sparrow is ~2mm or less and unreadable. It is all about the nav bar and the great padding around the items. If this padding would be more flexible or removed, everything should be fine.

**Comment by itscz-org** [comment] 2024-12-09 11:54
If i use 175% system-wide and 100% in Sparrow, yes, all fonts in Sparrow are smaller then everything else. Just what i expected. I also tried 125% and 150% in Sparrow. No solution. Either the fonts are too small or the window is too large. Nav item padding :)

![Zwischenablage_12-09-2024_01](https://github.com/user-attachments/assets/9c0e64c0-d21b-4abd-ac55-904951d6d817)

**Comment by craigraw** [comment] 2024-12-09 11:58
Thanks for the screenshot. I'm marking this as a duplicate of #1518, a feature request to allow font size selection.

**Closed by craigraw** 2024-12-09 11:58 UTC

**Comment by itscz-org** [comment] 2024-12-09 12:01
Are u kidding me? Please use a high DPI screen yourself and find a better solution. Why should i configure Sparrow to scale down and then in addition scale the fonts up? Just fix this menu.

**Comment by craigraw** [comment] 2024-12-09 12:06
You stated previously

> I tried setting it to 100% by the env variable. It fits to the screen then, but there is a reason i use 175%... with the 100% setting, the font height in Sparrow is ~2mm or less and unreadable.

If you can simply adjust the font size, you should not need to set `glass.win.uiScale` to 175%, and you won't have any issue with the nav bar. Or do you disagree?

**Comment by itscz-org** [comment] 2024-12-09 12:18
I never used this variable until this conversation to scale it down as requested by you. This is my 175% setting:

![image](https://github.com/user-attachments/assets/c7b91588-200a-45a4-9079-887b6ffba1dd)

Wouldn't it be better, if i can just run Sparrow without the need to configure anything?

**Comment by craigraw** [comment] 2024-12-09 13:24
I agree. But my point remains that this is fundamentally a font sizing issue, and unrelated to the nav bar (which resizes itself automatically to the height of the content on the right in any case).

**Comment by craigraw** [comment] 2024-12-09 14:06
Just create a transaction and that space (in the content area) will be filled with the transaction diagram. Create a transaction with many inputs and outputs and it will become quite busy. Sparrow ensures there is enough vertical space to display the transaction diagram without other content items jumping around when it is displayed.

**Comment by craigraw** [comment] 2024-12-09 14:07
That said, can you measure the number of vertical pixels with the window resized to the minimum height?

**Comment by itscz-org** [comment] 2024-12-09 14:38
The minimum possible window size, no matter what content page is visible, is 1122x1231 px

**Comment by craigraw** [comment] 2024-12-10 05:47
Ok, that makes sense. The minimum window height is 708px, so 708px * 175% = 1239px, close enough to what you measured.

To demonstrate that the nav bar is not the limiting factor, I have removed the 708px limitation to create this screenshot:

<img width="1197" alt="Screenshot 2024-12-10 at 08 15 19" src="https://github.com/user-attachments/assets/5e394e5f-07ae-4502-92e5-5e918115fa47">

As you can see, the Send tab is no longer usable. 

I think the challenge here is a screen of small physical size. I don't think the font sizing is actually the issue any more. It's simply fitting Sparrow onto that screen. You said in your OP:

> I have serious problems using Sparrow on HD or smaller resolutions.

Can you describe what these problems are? I think I'm still missing the key issue here.

**Comment by itscz-org** [comment] 2024-12-10 10:54
Then just remove the limitation and let the user decide.

As said, the window overlaps my visible area on 1440p that makes the app unusable. No smaller resolutions.

**Comment by craigraw** [comment] 2024-12-10 11:24
Letting the user decide to make the app unusable is a poor option. It will simply lead to confusion and a poor user experience for the majority who have ample screen real estate.

If you have a 1440px height, 1239px should fit (albeit marginally). You effectively have a resolution of only 822px at 175%, but that is sufficient given a 708px constraint. Something is not adding up with the info you have provided.

**Comment by itscz-org** [comment] 2024-12-10 14:09
Then add scrollbars to the content side and everybody known that not everything is visible.

See my first screen, it is on 1440p and the top and bottom is invisible.

**Comment by itscz-org** [comment] 2024-12-10 14:13
See another screen. It's on 1440p and i dragged the window so the top is visible, the bottom isn't.

![Zwischenablage_12-10-2024_01](https://github.com/user-attachments/assets/b0564769-b165-42ec-bb61-c824ec5a8925)

**Comment by itscz-org** [comment] 2024-12-10 14:15
Windows display settings. It's in german, but it should be clear what is meant.

![image](https://github.com/user-attachments/assets/b4f536da-31b1-411f-90fb-bb4fcf1bcd4c)

**Comment by craigraw** [comment] 2024-12-12 06:56
From this I can deduce you have a usable and logical (ie without taskbar, magnified) screen height of around 600px. I can reopen and retitle this issue to try address this (as I said before, it's very challenging), but it's low priority given this resolution is is now very uncommon.

It's unclear to me whether you run Windows display settings at 175% just for Sparrow, or for other apps as well. If it's the former, I trying using `glass.win.uiScale` instead with a lower value like 150%. If it's the latter, you could try `glass.win.uiScale` at 80%. Maybe that makes the text small, but it's a least a workaround for now.

**Comment by itscz-org** [comment] 2024-12-12 09:54
I give up. You are unwillingly to understand or address the issue.

**Comment by craigraw** [comment] 2024-12-12 10:08
To the contrary, I have tried hard to understand the issue, and explain the solutions as best as I see them. Just because you do like the answers does not make them any less real. The challenges remain what they are. It is difficult to reduce the required application height to 600px. 

How you can read "I can reopen and retitle this issue to try address this" as "You are unwillingly to address the issue" is beyond me.

**Comment by itscz-org** [comment] 2024-12-12 10:20
I don't have 600px here. And downscaling to 80% makes it unreadable. As said, you are unwillingly to understand. I am out.

**Comment by craigraw** [comment] 2024-12-12 10:31
No, I think you're unwilling to understand how scaling works. [For example, a 4K screen (3840x2160 pixels) at 200% display scaling presents as 1920x1080 logical pixels](https://medium.com/@hodgskin.callan/logical-points-vs-physical-pixels-in-a-post-windows-world-712e76b5f5eb). 

At 175%, 1440px pixels means 822 logical pixels. Subtract the height of your (double height) taskbar and you're getting close to 600 logical pixels for Sparrow to fit into.
