### ISSUE TITLE
Displayed balance doesn't account for self-to-self transactions

### ISSUE THREAD

**Issue by fanismichalakis** [sparrowwallet/sparrow#168] opened 2021-08-05 20:38 UTC
**Issue:** Sparrow doesn't seem to count correctly when computing the "Balance" value to display to the user if there are self-to-self transactions.

**Context:** I've consolidated some UTXOs that were all locked on the same address and sent them as one output to the next empty 'Receive Address' of the wallet. The transaction is displayed in the transactions list, but only as a send and not as a receive. Moreover, the consolidated amount isn't taken into account in the displayed balance of the whole wallet. However, the consolidated UTXO does appear in the UTXOs panel.

I think such a self-to-self transaction should consist of 2 lines in the transactions list: one for the send and one for the receive. And, of course, the consolidated amount should be counted for the total balance.

**Comment by craigraw** [comment] 2021-08-06 09:16
I don't follow this logic entirely - there is only one consolidation (self-to-self) transaction, therefore there should only be one transaction in the transactions list. The wallet balance should just decrease by the miner fee in this situation. 

Do you different expectations, or is the behaviour you are seeing different to this?

**Comment by fanismichalakis** [comment] 2021-08-06 09:55
Hey! The wallet balance decreased by the whole consolidated amount, not just the miner fee. Same goes for the transaction displayed in the transactions list : it shows the transaction as a send of the full amount, not just the miner fee.

**Comment by fanismichalakis** [comment] 2021-08-06 10:02
Ok, so I just refreshed the wallet and this time everything shows as expected:
* the consolidation transaction only shows the miner fee as spent
* the balance is now correct

Not sure what caused the amount to display otherwise in the first place.  But this can be closed I think. Thanks for your reply (and kudos for Sparrow!).

**Comment by craigraw** [comment] 2021-08-06 10:06
Cool - I've seen this before, it's caused by the server not being updated completely when it informs Sparrow of the new transaction (was this Electrs?). Sparrow does try to prevent partial information from showing, but ultimately the server is the oracle. 

Server implementations are improving so hopefully this will be resolved in future. I'll close this off.

**Closed by craigraw** 2021-08-06 10:06 UTC
