### ISSUE TITLE
Ledger Nano S taproot

### ISSUE THREAD

**Issue by 03dom** [sparrowwallet/sparrow#596] opened 2022-06-11 09:44 UTC
Not sure if this is already supposed to work, but cannot sign transaction to send from a taproot account with Ledger Nano S.

<img width="507" alt="2022-06-09_taproot-send-fail" src="https://user-images.githubusercontent.com/35029091/173182667-5f9b21c0-d81e-4220-8340-82dcbb68f710.png">
.

**Comment by craigraw** [comment] 2022-06-12 07:30
Duplicate of #376 - this will be fixed in the next Ledger firmware release.

**Closed by craigraw** 2022-06-12 07:30 UTC
