### ISSUE TITLE
Use of needlessly technical wording, ex, UTXO, Mempool

### ISSUE THREAD

**Issue by Transisto** [sparrowwallet/sparrow#108] opened 2021-04-25 20:35 UTC
related to https://github.com/sparrowwallet/sparrow/issues/107

![image](https://user-images.githubusercontent.com/388716/116008137-067cd100-a5e1-11eb-8f92-aee0f16496f3.png)
I read over that, really didn't understand.

Most people will never understand what a UTXO mean, (Too cryptic abbreviation)
Most people will never understand what a mempool mean

![image](https://user-images.githubusercontent.com/388716/116008192-4479f500-a5e1-11eb-8e0c-5b1a32f33b2c.png)
I think the bitcoin community is already used to Coins, Coin Selection, (not UTXO selection)

Same thing with "Mempool change" vs "Unconfirmed coins"

**Comment by craigraw** [comment] 2021-04-26 06:47
Thanks for the feedback. 

Sparrow uses "UTXOs" rather than "Coins" as one of the major wallet tabs, so this was a conscious decision to not follow Electrum's example.  I just don't see the term "coins" being used much (for example, I don't hear "look at your coins" or "i spent some coins"). UTXOs on the other hand seem to be very common on major Bitcoin podcasts and recent articles, I think because the term is more specific. OTOH I've kept "Coin Selection" because again this seems to be the accepted term.

I've recently changed the UI for this preference setting (Sparrow will now support spending any unconfirmed UTXO by default):

<img width="550" src="https://user-images.githubusercontent.com/862166/116039600-37a1e380-a66b-11eb-84a6-0be6d0c889c0.png">

This uses both "unconfirmed" and "mempool" to make things clear (I hope). Although this argument is weaker, I'm still a little concerned that some will think a transaction with less than 6 confirmations is "unconfirmed", so mempool is there is remove any doubt.

**Comment by urza** [comment] 2021-04-27 17:48
I support the choice of using technically correct terms like UTXO and Mempool here rather then simplified abstractions. Peple who don't understand these, should probably use another wallet anyway. The reason why I switched to Sparrow is that it is advanced wallet that allows me to create transactions manually the way I want.

**Comment by Transisto** [comment] 2021-04-28 02:51
I thought more deeply about it and you're mostly right. It's a definitely a thought problem.

Here's another one that could use a retouch.
![image](https://user-images.githubusercontent.com/388716/116338993-aafe3f00-a7aa-11eb-9275-cfe5fcc05e0c.png)

I'd say "In mempool" or  "Pending (mempool)"




@urza I make custom RBF almost weekly by deleting transaction from console in electrum, Really if you want advanced feature electrum is still the go-to.  Advanced users are rare and they can read though any terminology.

**Comment by craigraw** [comment] 2021-04-28 06:24
> I'd say "In mempool" or "Pending (mempool)"

I'm not sure the first adds much? I like the second but unfortunately space is lacking to add it.

> @urza I make custom RBF almost weekly by deleting transaction from console in electrum, Really if you want advanced feature electrum is still the go-to. Advanced users are rare and they can read though any terminology.

Interesting - can you explain this custom use of RBF?

**Comment by Transisto** [comment] 2021-04-28 10:08
Electrum only RBF option are, cancel transaction (send to self) , increase
fees, increase fees by taking from payment.

By custom RBF I mean asking electrum to completely ignore some tx from
mempool and crafting a new, completely different transaction, that is
spending from at least the same utxos.

**Comment by Transisto** [comment] 2021-04-28 10:13
In other words, it's saving us the fees from skipping a Send To Self.

**Comment by craigraw** [comment] 2021-04-28 10:46
> By custom RBF I mean asking electrum to completely ignore some tx from
mempool and crafting a new, completely different transaction, that is
spending from at least the same utxos.

You can do this with Sparrow too, unless I'm missing something. After you click the RBF button the UTXOs and payment details are editable on the Send screen.

**Comment by Transisto** [comment] 2021-04-28 21:28
> You can do this with Sparrow too, unless I'm missing something. After you click the RBF button the UTXOs and payment details are editable on the Send screen.

There's an RBF button? I see an "increase fee" option on an unconfirmed transactoin. But I didn't even see an option to make the transaction RBF or not when building it.  There's good reasons to want to make an non-RBF transaction and that doesn't seems to be possible.

![image](https://user-images.githubusercontent.com/388716/116474864-0bdb5500-a847-11eb-9a8e-c17afc5586c8.png)

I'd expect the option to be around there?

**Comment by craigraw** [comment] 2021-04-30 11:10
RBF is actually part of the sequence field on a transaction input, so the option to turn it on and off exists on the input detail screen of a transaction:

<img width="373" alt="Screenshot 2021-04-30 at 12 25 03" src="https://user-images.githubusercontent.com/862166/116682983-495af200-a9af-11eb-9843-baa023abdd0c.png">

What I actually meant though in my previous comment was the 'Increase Fee (RBF)' button. I've changed the context menu to include these icons for better clarity:

<img width="326" alt="Screenshot 2021-04-30 at 13 04 36" src="https://user-images.githubusercontent.com/862166/116686917-c0df5000-a9b4-11eb-899c-6fb5941d7a40.png">

If there's anything that Electrum can do here that you can't with Sparrow, let me know.

**Comment by Transisto** [comment] 2021-05-01 05:49
> If there's anything that Electrum can do here that you can't with Sparrow, let me know.

Creating fully custom RBF mean I ignore the transaction, use the same UTXO, combine with other UTXO, and send the BTC elsewhere.

I can't think many users would need that but it saved me some fees in the past.

I just found where the RBF flag is located., Seems quite hidden for how basic that feature is, 

I didn't know it was possible to mark only part of the input as RBF, I feel more confused than before if that's the case.
Each input can be market as RBF or not?

**Comment by craigraw** [comment] 2021-05-03 12:37
> Creating fully custom RBF mean I ignore the transaction, use the same UTXO, combine with other UTXO, and send the BTC elsewhere.

True - with Sparrow you can remove UTXOs from a replacement tx but not add others.

> I just found where the RBF flag is located., Seems quite hidden for how basic that feature is,

Is it a basic feature? Disabling RBF is probably an expert level function IMO. Unfortunately space is lacking on the tx tree root screen to add a 'change all inputs RBF' toggle.

> Each input can be market as RBF or not?

Yes correct. Actually Sparrow probably needs work to handle a partial RBF transaction better - I don't think it will currently allow creating the replacement in this case.

**Comment by craigraw** [comment] 2021-05-17 10:01
> Yes correct. Actually Sparrow probably needs work to handle a partial RBF transaction better - I don't think it will currently allow creating the replacement in this case.

Sparrow now handles partial RBF (only some inputs marked RBF) as of c9cdf6e. Closing this off.

**Closed by craigraw** 2021-05-17 10:01 UTC
