### ISSUE TITLE
Can you add arm64 support?

### ISSUE THREAD

**Issue by P1xelfehler** [sparrowwallet/sparrow#577] opened 2022-05-29 10:44 UTC
Hi,

could you please add support for arm64? I want to run sparrow on my raspberry pi.

thanks

**Comment by craigraw** [comment] 2022-05-30 10:52
Duplicate of #563 (arm64 and aarch64 are equivalent). I will add that I don't think an RPi has enough power to do Sparrow justice, but I don't know tbh.

**Closed by craigraw** 2022-05-30 10:52 UTC
