### ISSUE TITLE
Windows Defender Alert

### ISSUE THREAD

**Issue by gfontaniere** [sparrowwallet/sparrow#1331] opened 2024-03-19 06:41 UTC
Hello,
When i install Sparrow, Windows Defender shows an alert about presence of a virus : Trojan:Win32/Wacatac.B!ml
![Capture d'écran 2024-03-19 073654](https://github.com/sparrowwallet/sparrow/assets/12762548/359f3afc-00b1-4dfd-8b16-ad6a4d7d0ff2)
Have a nive day.

**Comment by anon-dev-gh** [comment] 2024-03-19 16:52
+1

**Comment by gfontaniere** [comment] 2024-03-19 17:23
Same issue with standalone client or installable client.

**Comment by amavis442** [comment] 2024-03-19 21:28
+1

**Comment by amavis442** [comment] 2024-03-19 22:35
Looks like duplicate of #1310

**Comment by gfontaniere** [comment] 2024-03-20 10:20
So this is a false positive. Thank you.

**Comment by craigraw** [comment] 2024-03-20 14:01
It is a false positive yes. Marking as a duplicate of #1310.

**Closed** 2024-03-20 14:01 UTC
